- assets/js/edd-checkout-global.js
Hi Pippin,
Small PR, this adds the fields of the purchase form to the AJAX call to validate the coupon when pressing 'apply'.
In my scenario I want to validate the user email; which is possible when someone is logged in, but when a guest wants to checkout I want to verify the checkout email. 
The code is pretty global and can also be used for other purposes.
Let me know what you think.
Thanks and happy new year :fireworks:,
Jeroen
PS. what do you use for minification/uglification of JS?
> Add serialized form data to ajax call

- includes/class-edd-api.php
- tests/tests-html-elements.php
Contains fixes for #2906 and some whitespace cleanup. Also includes a unit test 'fix' for the hardcoded years in the HTML Year Dropdown test. I've #2907 to address this.
> API call for Yesterday should work on Jan 1

- includes/discount-functions.php
- includes/download-functions.php
* Don't double sanitize 'name' argument, it's already being sanitazed by `WP_Query`.
* Ref: #2918.
> Avoid using `query_posts()`

- includes/user-functions.php
As it stands, this code throws notices if the passed `$user` does not exist in the customers table. This ensures that a sensible value is always returned.
> Validate that the user is already in the customers database.

- .travis.yml
- travis-after.sh
- travis-tests.sh
Addresses the last comments on #2839 
Reduces to only testing multisite on one config (PHP 5.3 and latest WP)
Also only runs code coverage on 5.5, latest, non-multisite. This will run coverage on all commits, now that matrix is smaller and the builds faster, no harm in that.
> Further optimizations for Travis Build Matrix

- assets/js/edd-ajax.js
- includes/ajax-functions.php
When removing an item from the cart widget, it was removing the item we wanted it to, but not resetting the cart ID (data-cart-item). This means that if you had 3 items in the cart(0, 1, 2) and removed item 1, the items left were still labelled as 0 and 2, rather than 0 and 1. This meant that if you, then, removed item 3, it didn't exist. It would get removed from the screen using javascript BUT it didn't actually get removed from the PHP session. If you then refreshed the page you would see that the item is still in your cart - even though you thought you had removed it. This solves that problem by re-assigned the right data-cart-item ids after an item is removed.
Signed-off-by: Phil Johnston <support@mintplugins.com>
> Fixed incorrect remove by ajax cart IDs and amounts

- assets/js/edd-ajax.js
- includes/ajax-functions.php
- includes/cart/functions.php
Fixes #2931 and updates the ```edd_get_cart_quantity()``` to return the sum of the  cart quantities instead of a sum of the different products in the cart.
> Quantities on cart widget are incorrect when adding with quantities > 1

- templates/shortcode-receipt.php
Added new filter edd_receipt_no_files_found_text allowing filtering of the "No downloadable files found." message per $download_id.
> Added new filter edd_receipt_no_files_found_text.

- includes/download-functions.php
The price_id should be passed so those who need it to filter the price for variable priced products can
> Add $price_id to edd_price filters

- includes/admin/tools.php
- includes/admin/upgrades/upgrade-functions.php
- tests/tests-upgrades.php
Should address issues when we have multiple upgrades for a user who either jumps versions or a version has 2 upgrades in it's release. #2835
> Introduce upgrade completion functions and tests

- .travis.yml
Travis CI has a bug where when fast_finish is enabled, it doesn't let you cancel the builds:
https://github.com/travis-ci/travis-ci/issues/2658
> Don't use fast_finish for Travis

- includes/process-download.php
The file download count check which for legacy links are done in the deprecated edd_verify_download_link function are not done for the new download links. This pr solves that issue.
Solves #3259
This needs to be tested
> Checks for download limit for new urls #3259

- includes/ajax-functions.php
Right now, we save whether or not the ajax test works as a transient, but we never actually use it. So what happens is on every edd_notices call, which is done on every admin page, EDD related or not, we're running this (can be) performance harming remote_post. This pr uses the transient to return early, so we only check it once a day, not every single notices call
> Fix Ajax Test Works Function

- assets/js/edd-ajax.js
Solves #3270
When there are multiple `[purchase_link]` shortcodes for the same product on the same page, each with its own `price_id`, adding any of them to the cart results in the first one on the page being added instead of the one clicked. Example shortcodes below. Clicking the one for `price_id="2"` results in `price_id="3"` being added to the cart.
> Wrong price_id gets added to cart using multiple [purchase_link] shortcodes for same product (#3270)

- includes/gateways/functions.php
- includes/template-functions.php
Solves #3235
We gets users every now and then that encounter issues with trying to use Buy Now buttons and taxes but then not seeing taxes get calculated. This is because the general Checkout process is required for calculating the taxed amount.
I'm proposing that we automatically disable the buy now options if taxes are enabled. In the future, once we have introduced a way to calculate taxes and use buy now buttons, we can remove this.
> Disable Buy Now buttons when Taxes are enabled (#3235)

- includes/template-functions.php
Solves #3230
Make sure Item Quantities are enabled in the EDD settings. Set up a variable pricing product with multi-purchase mode enabled. View the single download page to confirm that the item quantity fields display for each variable pricing option. Once confirmed, use that product's [purchase_link] shortcode in a separate Post/Page. The item quantity fields don't seem to show.
> Item quantity fields not showing with [purchase_link] shortcode (#3230)

- includes/ajax-functions.php
- tests/ajax.php
Solves #3215
If the Airplane mode plugin is installed and enabled we should ignore the test. It's kind of annoying to see the error all the time.
> Don't check if ajax calls work if Airplane Mode plugin is active (#3215)

- assets/js/edd-ajax.js
- includes/template-functions.php
Solves #3275
If you have multiple [purchase_link] short codes for a product on the same page, they all get changed to Checkout when one is clicked.
When the buttons are all for the same price ID, it is the expected behavior but when each button has a different price ID, this should not happen.
> All add to cart buttons for same product changed to checkout when one is clicked  (#3275)

- includes/class-edd-api.php
Right now, the stats API uses the following query to get the customer
count:
```$count = $wpdb->get_col( "SELECT COUNT(DISTINCT meta_value) FROM
$wpdb->postmeta WHERE meta_key = '_edd_payment_user_email'" );```
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/49bba4499763ed571e7a9fa336e24ddd902663ba/includes/class-edd-api.php#L1110
This is great in that it works for everyone even if they didn't run the
EDD 2.3 updates.
On the downside, there's 2 significant issues with it:
- It's not cached
- Its a huge set of data (we ask MySQL to find all records, then limit
it)
Instead, what we should do is for the 99.999% who did the update routine
use the customer count from EDD_DB_Customers, which is both cached and
far more efficient (we don't need to sort out duplicates)
So our …
> Use the new customer count in EDD_DB_Customers for >= 2.3 installs

- .gitignore
I noticed this while making another recent PR. Git isn't configured to ignore the `vendor` folder or the temporary files (`*~`).
> Ignore vendor directory & temporary files.

- includes/class-edd-download.php
- includes/payments/functions.php
- tests/tests-downloads.php
Moves to a explicit `create` method for the `EDD_Download` class, and addresses the issues in #3312
> Introduce create() method for EDD_Download

- includes/payments/actions.php
- includes/payments/functions.php
- tests/tests-tax.php
Fixes bug with payment meta/tax backwards compatability code. Adds unit test. Fixes #3324.
Passes all tax unit tests. However I was only able to test 60% of all unit tests before I encountered an error (unrelated to this pull request):
> PHP Fatal error:  Call to undefined method Tests_Activation::assertNotFalse() in /var/www/html/plugins/edd/tests/tests-install.php on line 76
(Seems the phpunit version set by `composer.json` is out of date? I think it requires 4.4+)
> Ensure meta data contains tax key. Fixes #3324. 

- includes/country-functions.php
There's no "Cyprus Island", just "Cyprus". :)
> Rename "Cyprus Island" to just "Cyprus".

- includes/checkout/template.php
- includes/gateways/functions.php
- tests/tests-gateways.php
Addresses the concern in #3297 by allowing the list of enabled gateways to be returned with the default one first. It also implements it on the checkout template.
> Allow ordering of gateways with default first

- includes/ajax-functions.php
Depending on the load order of files, the global might not contain an instance of the Airplane Mode. Let's ensure it does
> Fix Airplane mode

- includes/plugin-compatibility.php
- tests/tests-plugin-compatibility.php
- tests/tests-scripts.php
- tests/tests-shortcodes.php
Wow, I've been lacking in doing commits lately!
Gonna try picking it up again :smile: 
This script has two `markTestIncomplete`, as it is generating some errors;
The error only occur when testing the full suite, not when only testing the tests-scripts.php file.
Maybe you got an idea why its happening (happens on the lines with `$this->go_to( get_permalink(..) );`
```
There were 2 errors:
1) Tests_Scripts::test_load_scripts_checkout
Trying to get property of non-object
/private/tmp/wordpress/wp-includes/query.php:4349
/private/tmp/wordpress/wp-includes/query.php:496
/Applications/MAMP/htdocs/edd/wp-content/plugins/Easy-Digital-Downloads/includes/checkout/functions.php:78
/Applications/MAMP/htdocs/edd/wp-content/plugins/Easy-Digital-Downloads/includes/plugin-compatibility.php:134 …
```
> Script tests

- includes/download-functions.php
#3416 
Correctly sets the GMT for the edd log. See below record of test payment:
> Set post date GMT for EDD Log

- includes/ajax-functions.php
Just adding a filter that is useful if you're doing anything in the checkout that needs to respond to changes in the cart. I'm working on an application that could really benefit from this. My current workaround is to fire off a second AJAX request after this one returns, which results in an odd delay and is certainly far from ideal.
Happy to explain in further detail if you want a better understanding of the use case.
> Add filter on cart item quantity ajax event.

- assets/css/edd-admin.css
- includes/admin/settings/register-settings.php
This little PR adds style improvements to EDD Settings tabs. The CSS updates improve the label and field section separators. Here's a preview:
I hope you like it! :)
> Settings style improvements for labels and field section separators

- uninstall.php
I noticed this option was being left behind if the user chooses to do a clean uninstall. I couldn't find any reason it's not being deleted.
> Remove edd_version option on uninstall

- includes/ajax-functions.php
This is useful (necessary) for VAT plugins to update the displayed tax rate everytime `edd_recalculate_taxes` is called, without having to perform an unnecessary additional AJAX request.
> Add more info to tax rate response

- includes/admin/class-edd-notices.php
- includes/admin/tools.php
- tests/ajax.php
Addresses concerns in #3475 & #3387
> Removing calls for edd_test_ajax_works for now

- includes/admin/downloads/dashboard-columns.php
- includes/admin/reporting/pdf-reports.php
- includes/class-edd-html-elements.php
- includes/post-types.php
- includes/widgets.php
- tests/tests-post-type-labels.php
Addresses the issue raised in #3212 but also makes a consistent usage of our taxonomy labels.
> Allow taxonomy labels to be used elsewhere easily

- includes/class-edd-session.php
Resubmit against `release/2.4` of PR #3172 
I've started using fastcgi caching with Nginx over caching plugins.  The down downside of this is that Nginx will not cache any page or serve a cached page for any request with a Set-Cookie, and unlike Varnish, you can't exclude cookies from the cache.
I've noticed that every page request on sites with EDD includes a Set-Cookie header from EDD in the form of `edd_items_in_cart`.  It defaults to `deleted`, but if any items are in the cart it is set to that number.
I can't figure out why it would be necessary to set this cookie on every single request, especially when a user hasn't initiated any shopping actions.  Nor does it feel like the kind of data that needs to be in a cookie. 
With EDD's strong AJAX coverage, I'd think there would be plenty …
> Cache busting cookies: edd_items_in_cart

- assets/js/edd-checkout-global.js
- Bind `EDD_Checkout` object to window
- Expose `recalculate_taxes` method so other plugins can call it
- Bind events in one place, for a clearer overview and better usage of variables etc.
- Don't use inefficient $('body') 
- Less anonymous functions
Together with #3457 this helps other plugins recalculate & show tax rates based (like after entering a VAT number in a field).
> Create window.EDD_Checkout object and expose some functions to it.

- includes/admin/settings/register-settings.php
- includes/emails/functions.php
I need to change the title of the "Purchase Receipt" but realized that the output is not filterable or able to be set as an option. This PR makes it possible to override as a filter, and enables a new setting in EDD settings to make it user controlled.
> allow for the heading in purchase receipt to be set overridden

- includes/template-functions.php
It would be nice to have filters on these HTML snippets. You can get around this now by unhooking the action callback, but then you have to run all the same checks that `edd_download_purchase_form_quantity_field()` and `edd_variable_price_quantity_field()` run. 
As an aside, would it make sense to bake an optional label into the HTML output here? As it stands, the quantity input just feels like a random input field without a clear context.
> Add filters to modify the quantity input fields in purchase forms.

- includes/checkout/functions.php
The `edd_get_payment_status()` function only accepts a `WP_Post` object. However the current version of `edd_listen_for_failed_payments()` passes a payment ID (post ID) to the function, causing it to return false instead of the actual payment status so that the payment status is never actually changed to 'failed'.
This commit fixes that behavior.
> fixed edd_listen_for_failed_payments()

- includes/download-functions.php
Hey,
Just noticed this and made a quick PR inside GH.
Use the sanitized and filtered `$download->get_price()` and `$download->get_prices()` values for the old backward compatible functions instead of the EDD_Download property.
> Use $download->get_price() function instead of property

- includes/checkout/functions.php
- includes/misc-functions.php
is_ssl() handles the same check and an additional port check for when servers fail to set the HTTPS var. This removes the check from edd_enforced_ssl_redirect_handler() since it's already checked with is_ssl above, and it swaps the check in edd_get_current_page_url() to is_ssl().
> Switch from $_SERVER["HTTPS"] check to is_ssl(). #3740.

- tests/tests-stats.php
Hi!
Long time since my last commit, have been quite busy! Trying to pick it back up..
Noticed the tests were failling locally and with other PRs, probably due to a typo that has been fixed.
This fixes the broken unit test.
> Fix broken test (due to typo being fixed)

- tests/tests-api.php
- tests/tests-emails.php
- tests/tests-payments.php
- tests/tests-roles.php
- tests/tests-stats.php
This may be related to my specific PHPUnit version, as I didn't see it on any of the TravisCI tests so far, but it seems like a improvements.
I was getting these warnings:
Which is fixed in this PR. 
Importing classes from the global namespace without any alias doesn't have any purpose as far as I know :smile_cat:
> Fix test warnings, removing useless 'use \CLASS'

- includes/admin/customers/customers.php
Corrected the spelling for the ```edd_customer_recent_purchases_actions``` action hook. 
It is written as ```edd_customer_recent_purcahses_actions``` instead of ```edd_customer_recent_purchases_actions```
> Corrected spelling for edd_customer_recent_purchases_actions hook

- includes/admin/payments/class-payments-table.php
Right now the links here just bring you to a filtered view of the customers payments. 99% of the time, when on the page, I sort of expect this link to bring you to the customers's profile, which after all contains all of their orders anyways.
This pr fixes it so it does that
Makes for a much better user experience and lets you more easily cross reference data for a customer
> Better Customer Links for the Payments Table

- easy-digital-downloads.php
In accordance with [PHP Documentation Standards](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/), this commit does the following
- Adds period at the end of single line comments, short/long descriptions (where needed)
- Adds short description for the `EDD()` function
> Better Documentation

- assets/js/edd-ajax.js
Disable the add to cart button during ajax requests to prevent items from being added multiple times due to user rapidly clicking the button (issue #3927). The add to cart button is re-enabled when the ajax request is complete, so that it can be used again in the event that the user removes the item from the cart and then needs to re-add it.
> Disable add to cart button during ajax request

- includes/country-functions.php
I just had a customer tell me that their credit card billing address is in Wairarapa, which is missing from the states list in New Zealand.
> Add Wairarapa to New Zealand regions

- includes/widgets.php
As per the [PHP documentation standards in the core handbook](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/), this commit helps make the documentation better by adding:
- Period endings
- A Long description
> Better Documentation: Period Endings

- includes/admin/class-edd-notices.php
- includes/admin/customers/class-customer-table.php
- includes/admin/reporting/class-gateway-error-logs-list-table.php
- includes/admin/settings/register-settings.php
- includes/admin/welcome.php
- includes/gateways/amazon-payments.php
In the next version of WordPress (4.4), we fixed many translation strings that used html tags.
See: https://core.trac.wordpress.org/query?milestone=4.4&component=I18N&reporter=ramiy&group=milestone&col=id&col=summary&col=milestone&col=type&col=priority&col=component&col=severity&col=resolution&order=priority
The same thing should be done in EDD.
> Avoid using HTML tags in translation strings

- includes/class-edd-cron.php
I'm not sure why it was capitalized but I standardized it to match other methods in the class
> Lowercase "e" for the schedule_events method in EDD_Cron class

- includes/admin/admin-pages.php
The reason for this change is that the tools page is hidden when the constant `DISALLOW_FILE_MODS` is defined. This is a bigger issue for me as the fraud monitor settings are in the tools page. 
There does not seem to be any reason to limit the access to those who can install plugins.
> Change capability for the Tools page

- includes/admin/reporting/class-export-payments.php
- includes/admin/reporting/export/class-batch-export-payments.php
- includes/checkout/template.php
Instead of having "Zip / Postal code" with a small "c" and "Zip Code" to have only "Zip / Postal Code". This reduces the number of strings slightly.
"Zip / Postal Code" already exists as a string.
> Standardize "Zip / Postal Code" string

- includes/admin/reporting/class-api-requests-logs-list-table.php
- includes/admin/reporting/class-file-downloads-logs-list-table.php
- includes/admin/reporting/class-gateway-error-logs-list-table.php
- includes/admin/reporting/class-sales-logs-list-table.php
(Submitting against release/2.5 per @pippinsplugins request)
Currently the method for switching between different reports and logs views in EDD is to choose a view from the select field in the bulk actions part of WP_List_Table. The problem with this is that bulk actions only display if there are items to show in the table which results in users losing their navigation if they select a view that contains no entries.
This solution ensures that the navigation will always display by simply setting the has_items() method to true no matter what on the tables that require bulk actions regardless of whether items exist.
Resolves #4092
> Always show reports and logs navigation

- includes/ajax-functions.php
- includes/country-functions.php
Makes it possible to add custom states without modifying core.
```php
function custom_edd_states($states, $country) {
if(empty($states) && $country === 'AR') {
$states['BA'] = 'Buenos Aires';
$states['EA'] = 'Mendoza';
}
return $states;
}
add_filter('edd_shop_states', 'custom_edd_states', 10, 2);
```
> Pass selected country to the edd_shop_states filter

- tests/tests-easy-digital-downloads.php
On a Windows environment this unit test will fail. 
This is purely a problem with phpunit and not an actual bug in EDD.
What happens is Windows sees the EDD constant declaration and ends the path with a "/" whereas the unit test declaration path ends in "\". This is simply a result of PHPUnit's path being called in a folder above the file versus the original file. In EDD since the constant is declared once, as it's a constant, this isn't a problem. The path removes the last character of each path, allowing the test to pass on Windows.
> Fix test constants plugin folder path check

- includes/class-edd-html-elements.php
I wanted to add another select field and came across a problem that the placeholder text was being added as a selected item once I selected an option.
This was not happening in the bundle option as the values were numbers but in my case I needed to values to be text.
The following will return `1`
```php
$array[0] = 'abc';
echo in_array( 0, $array );
```
Where as the following will not return a result.
```php
$array[0] = '123';
echo in_array( 0, $array );
```
By setting the check to strict the result will be the same for both situations.
P.s. You may want to think about making all of the checks strict.
> Set in_array check to strict

- includes/admin/payments/view-order-details.php
Just wrote this on a phone (untested). Solves #4187.
> If key not in payment status array then still show the correct payment status selected

- includes/query-filters.php
Introduce edd_refresh_permalinks_on_bad_404() to auto flush permalinks when a 404 error is thrown on an EDD post type or taxonomy page. #4205
> Introduce edd_refresh_permalinks_on_bad_404() - #4205

- includes/admin/admin-pages.php
The `edd_view_customers_role` filter is called in the render function but not on the `add_submenu_page` and thus you can never get there, even if you filter it.
> Make edd_view_customers_role filter work.

- includes/admin/reporting/class-sales-logs-list-table.php
- includes/payments/functions.php
Target
--
Ensuring that all the rows in the Sales Log show the currency currency symbol.
Changes
--
* Added currency to the data returned by the `edd_get_payment_meta_cart_details()` function.
* Tweaked the Sales Log to use the currency associated with each item.
Why
--
The Sales Log, and practically every other log, calls the `edd_currency_filter()` function without passing a currency. This is imprecise, as the currency associated with a payment may or may not be the "global" one (this is true in multi-currency environements, but also if the admin changes the base currency). Since the log export classes are pretty much hard-coded, it's quite difficult to intercept the call to `edd_currency_filter()` and "sneak in" the correct currency. It's much simpler to do that within the core, as it …
> Made Sales Log currency-aware

- includes/admin/payments/view-order-details.php
Also affected "Refund Charge in Stripe" checkbox placement.
> Add missing <p> wrapping payment status drop-down.

- includes/payments/class-edd-payment.php
- tests/tests-payment-class.php
For #4350, Originally submitted by @dancameron in #4351, just adds unit tests to verify the fix.
I removed the fix and added a unit tests, and it proved a failure. After re-enabling the fix from Dan, the unit tests passed with no errors.
> EDD_Payment::setup_fees_total with unit tests

- includes/checkout/template.php
When ajax is turned off, we give a back button from step 2 (checkout fields) to step 1 (gateway selection). Unfortunately, apparently you can't use Javascript to do the redirect when Javascript is disabled. Also the lack of query param stripping means that extensions that depend on edd_get_chosen_gateway() to work will find that there's a mismatch between what that function says the selected gateway is and what the radio buttons have selected (because those fallback to edd_get_default_gateway()). Crossref: https://github.com/chriscct7/edd-gateway-fees/issues/16 1 and 2
> Fix lack of JS support when ajax is turned off

- includes/cart/functions.php
For simplicity, we'll have a cart with 1 product, with an entered cost of $100. 
We've set the global tax rate to 10%, and have an active discount fee of 10%
As in the rest of EDD, we should always calculate tax after discounts.
When item price excludes tax
Total should be ($100 - 10%) * 1.10 = $99
of which the tax amount is ($100 - 10%) *.10 = $9
of which the product amount is ($100 - 10%) * 1 = $90
This part works fine.
Also calculating without taxes works fine. 
So why does this code only not work when prices are entered inclusive of taxes?
When item price includes tax
Raw product amount: ( 100 / 1.10 (this step makes the price exclusive of 10% tax) ) = $90.91 ******
Final raw product amount (post-discount) should be $90.91 - 10% = $81.82
Final product amount should be $81.82 * 1.1 = …
> Allow for the removal of tax from edd_get_cart_item_price

- includes/admin/customers/customers.php
- includes/admin/discounts/discount-codes.php
- includes/admin/payments/payments-history.php
In all admin pages Core uses now `H1` heading as main heading. This PR changes `H2` heading to `H1`. 
Reference issue is #4339.
> Change admin page heading from H2 to H1.

- includes/post-types.php
In issue #4338 there is more info about new `screen-reader-text` labels for Custom Post Types. This PR adds those new labels.
> Add new labels in Downloads list admin page.

- includes/admin/downloads/metabox.php
Screen reader users don't have an idea how they can change default price because there is no label or text in radio button. This PR adds the label and `screen-reader-text` text so that visually nothing changes. 
In issue #4340 there is more detailed info.
> Add label and screen reader text to variable pricing default price

- includes/admin/payments/class-payments-table.php
currently there is no way to include your own advanced filters (my use case is a filter for showing payments by a particular gateway). this allows that.
> action for users to include their own advanced filters on the payments table

- includes/EDD_SL_Plugin_Updater.php
Plugins built using the EDD_SL_Plugin_Updater class "Phone Home" twice when on the "Dashboard" > "Updates" page or the "Plugins" page. This may be un-necessary.
The "plugins_api" hook is what's causing it to "phone home" twice on plugins and updates pages. If we cache the result of that for 24 hours in a transient (but not the result that comes through "pre_set_site_transient_update_plugins"), then "Dashboard" > "Updates" page will check for updates every time but only once every 24 hours on the "Plugins" page - and in turn only once every 24 hours will it check twice on the "Dashboard" > "Updates" page as well.
> Store api_request in a transient for 24 hours.

- includes/template-functions.php
Makes Add to Cart option accessible to screen readers.
See: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4482
> Add ARIA live & hidden attributes to AJAX alert

- includes/download-functions.php
- includes/emails/class-edd-email-tags.php
- includes/template-functions.php
- templates/history-downloads.php
- templates/shortcode-receipt.php
This swaps usage of `$file['name']` for `edd_get_file_name( $file )`, which means we're getting file names in our templates the same way everywhere.
Addresses #4555
> Standardize the method of getting file names

- includes/process-purchase.php
Right now, a couple of our extensions add extra validation to the checkout form.
The problem is that if they rely on knowing the correct user_id, right now, the hook they have to use is before EDD logs in a user if they've used the registration or login forms. To accurately log these users in, we need to add a new hook to let the extensions do this.
I've submitted this to master, as right now, a couple of our extensions have bugs that mean the validation will fail even for valid users, and the sooner we can get this hook out, the better, so the extensions can immediately update and fix this problem.
Additionally, there appears to be a related bug in core in that EDD is not correctly storing the user_id of the user placing an order if the user uses the login/registration forms while …
> Let extensions validate fields after a user has been logged in

- assets/js/edd-checkout-global.js
I was having an issue (as described here: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/2963) where the states field was just showing `nostates` instead of the field.
Turns out the response from the ajax was: `"        nostates"` (without quotes, but with spaces infront). this meant the conditional was not met. Added $.trim() to fix the issue and the field shows as it should.
Not sure why there were spaces before the response, but this solution works well and should avoid it in future.
> Trim states response

- includes/emails/template.php
Replaces #4400, so it's merged into `release/2.6` instead of master. All commits kept in tact @pderksen
> Use existing function to build {receipt_link} purchase receipt email tag.

- includes/class-edd-download.php
The filter have the same purpose of the action added for customers, i.e. to allow processing the earnings before they are update on the product. This needed in cases like multi-currency shops, where earnings cannot just be added or subtracted, but must be first converted to the base currency.
> Added filters to process the earnings as they are updated

- includes/cart/functions.php
This makes it unnecessary to reproduce the logic inside `edd_add_to_cart()`.
Closes #4820
> Add $items parameter to the `edd_post_add_to_cart` action

- assets/css/edd-admin.css
I couldn't see how you generate your minified CSS, so this doesn't update `edd-admin.min.css`.
Before:
After:
> Fix horizontal alignment of items in the dashboard widget

- includes/discount-functions.php
Apply a `edd_get_cart_discount_html` filter to each discount's generated HTML instead of one for all the discounts.
Fixes #4902
> Fixes #4902

- includes/admin/downloads/metabox.php
- includes/class-edd-html-elements.php
#4665 
This does 2 things. When buy now buttons aren't supported, the `Button Behavior` checkbox on the downloads meta boxes is disabled, instead of being hidden. It also modifies the tooltip text to mention why it's not allowed.
In order to do this, we had to allow our `select` HTML helper to accept a `readonly` and `disabled` argument.
> Disable button behavior option when not supported #4665

- includes/payments/class-edd-payment.php
This could cause problems with all the functions in /payments/functions.php - I started updating them, but it's so many that I figured I'd let @cklosowski and @pippinsplugins think about it first.
Related: #4718
> Return false if EDD_Payment::setup_payment() fails

- includes/discount-functions.php
I encountered a problem when using `edd_unset_cart_discount()` with a discount code that isn't actually set/active. This causes `$key` to be `false` and trying to use `unset` with a `false` array key empties the entire array out (thus removing other discount codes that weren't expected to be removed).
> Issue with unsetting cart discount when code isn't set

- includes/admin/import/class-batch-import-downloads.php
#4940 
Terms were not created because the `$term` variable was getting overwritten each time we tried to retrieve an existing term. When no term was retrieved, `$term` was set to `false` and thus we were passing `false` as the term name in `wp_insert_term()`, causing it to return a `WP_Error` with the message `A name is required for this term.`.
> Change  to  to prevent the original  variable getting overwritten. #4940

- includes/cart/actions.php
Fixes #4797 
Removes the edd parameters from the URL and then append the remaining parameters to checkout URL and then redirect.
> Preserve get parameters when straight to checkout is selected

- includes/admin/settings/register-settings.php
The way that `add_settings_field()` was being called before was very restrictive in what you could and could not pass to EDD Settings API Callbacks.
Now it utilizes `wp_parse_args()` to set the same defaults as before and simply passes `$args` to `add_settings_field()` instead.
This is useful if a User is creating a custom Callback function for a custom Field Type and wants to add more, custom Arguments than what EDD usually supports for its Settings API.
So if a User is adding a custom Field Type to their Settings Tab and wants to have an Argument called `add_item_text` or anything else that they need, they can.
> Allow custom Arguments for Settings API Callbacks

- includes/checkout/template.php
Clicking on the zip/postal code label on the checkout form wouldn't put focus into the appropriate field. This adds an `id` attribute to the zip code `input` field so the label can pass focus.
> Fix checkout zip code label's for attribute

- includes/class-edd-html-elements.php
Right now is label passed to an HTML element is empty, it still outputs an empty label. This is bad practice, because it causes issues if you're defining a label for that field elsewhere.
> Don't output a label if one isn't set for text and select HTML elements

- templates/shortcode-profile-editor.php
I was creating an online store and I was wondering why this string wasn't getting translated like the others. This one seems to have slipped through the cracks in the last text-domain change operation.
> Fix last text domain replacement

- includes/post-types.php
- includes/scripts.php
I think this is better because then it's easier and more intuitive to change the menu icon.
And should #3052 be revisited? It seems like the effort to move to SVG has been basically dead for over a year unless there's more discussion I haven't found.
> Move Download CPT icon to registration arguments

- includes/admin/settings/register-settings.php
Sometimes it is nice to have something for the `placeholder` attribute like desired input examples that you may not want to otherwise put in the Field's Description. 
I needed/wanted it for a project I'm working on, so I made this quick tweak. Just repurposes the `$args['placeholder']` that is also used within Chosen `<select>` field creation since their intent is similar.
> Add Placeholder attribute for Text Inputs

- includes/admin/settings/register-settings.php
Needed to add extra Class Names to Settings API Fields for CSS/JavaScript needs. This should allow that for every field, even the more specific ones like the callback for Tax Rates.
The `field_class` argument accepts both Strings and a basic Array.
Examples
`$args['field_class'] = super awesome class-name;`
```
$args['field_class'] = array(
'super',
'awesome',
'class-name'
);
```
In cases where Chosen or something else would normally place a Class Name onto the Field this still works just fine. The additional Class Names just become appended to the String that gets created.
> CSS Class Argument for Settings API Fields

- includes/admin/payments/payments-history.php
The link to the iOS addon is incorrect. This simply fixes that typo
> Fix link to iOS addon

- includes/admin/upgrades/upgrades.php
Right now we round the total number of steps using this:
$total_steps = round( ( $total / 100 ), 0 );
The problem is that if you round like that, what happens in the upgrades is if you have 102 items, it says "Running step 1 of 1 total" and then since there's more meta IDs to process, it redirects to finish the other 2 left and says "Running step 2 of 2 total". It looks like an extra step came out of nowhere.
This fix correctly tests + rounds the total of number of steps so this rounding error doesn't happen.
Proof of concept code:
``` php
<?php
$total       = 102;
$total_steps = round( ( $total / 100 ), 0 );
var_dump( "Total steps: " . $total_steps ); // <-- You'll incorrectly get 1 here
var_dump( "Total: " . $total );
// below is the new code additions to fix the issue
if ( $total_steps …
```
> Fix incorrect upgrade total steps rounding issue

- includes/class-edd-cron.php
Hi,
If you live in a UTC+0 timezone this doesn't affect you, but if you live in a UTC+2 i.e. timezone, without getting GMT time, the first time the cron will start after two hours.
With the use of the true parameter the cron will start immediately.
> Update the current time to get GMT

- includes/admin/downloads/metabox.php
Solves #5140 
In the save routine for the downloads metabox, _edd_download_limit isn't checked for existence before attempting to access it on line 119
> Check _edd_download_limit exists before trying to access it in superglobal on metabox save routine

- includes/admin/settings/display-settings.php
Implement a better way of determining if the main settings section is empty for a tab.
Solves #5171
The change basically changes the part that determines if the `main` section is empty, and makes it use the same code we use a couple lines down for finding the first non-empty section to replace it with.
> Fixes issue #5171 about determining if main section for a tab is empty

- easy-digital-downloads.php
- includes/admin/tracking.php
Adds support for user locales:
- The primary EDD `load_textdomain()` loader
- EDD_Tracking::setup_data()
- Related inline hook doc
#5247
> Add support for user admin locales

- easy-digital-downloads.php
- includes/checkout/template.php
- package.json
- readme.txt
The email field is required by default, just like the first name, but the first name input field has the "required" attribute and the email input doesn't. This PR just adds the missing "required" attribute to the email input field.
> Add "required" attribute to the email input field

- includes/template-functions.php
Currently EDD doesn't output price information for downloads that only have a single price, only for those that have variables prices. 
This PR outputs the following markup for single-price downloads:
``` html
<span itemprop="offers" itemscope itemtype="http://schema.org/Offer">
<meta itemprop="price" content="12.00" />
<meta itemprop="priceCurrency" content="USD" />
</span>
```
> Output schema markup for single price products.

- includes/emails/class-edd-email-tags.php
> Use esc_url_raw to prevent over escaping of links in emails

- includes/user-functions.php
See #5342 
Submitted against release/2.7 since there isn't a release/2.7.3 branch.
> Avoid PHP Warnings in 7.1 when a customer has no address.

- includes/payments/functions.php
#5520 
This ensures that earnings reports properly reflect recovered payments from past days, weeks, months, years.
> Update payment date during recovery. #5520

- includes/payments/class-payments-query.php
Instead of hooking to edd_pre_get_payments, call the query modifiers directly.
> Call query modifiers directly in EDD_Get_Payments

- includes/admin/import/class-batch-import-downloads.php
- includes/admin/import/class-batch-import-payments.php
In the ```EDD_Batch_Payments_Import``` and ```EDD_Batch_Downloads_Import``` classes the ```get_user_by``` function $field param was using the ```user_login``` and ```user_email``` field instead of the ```login``` and ```email``` field.
> Fix get_user_by function $field param

- includes/shortcodes.php
If this was a guest checkout and the purchase session is empty, output a relevant error message.
https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5594
> Add relevant guest checkout error message for receipts.

- includes/api/class-edd-api.php
- includes/class-edd-customer.php
- tests/tests-misc.php
Just a tiny misspelling. Three lines with "succesfully" instead of "successfully".
> Typo: "succesfully" instead of "successfully"

- includes/payments/class-edd-payment.php
> Check that  is an array before accessing it in get_meta(). Fixes #5658

- includes/admin/reporting/graphing.php
Adds a filter to let people customize the default date range, solving a backward incompatible change in EDD.
EDD changed this to "last 30 days" from "this month" in the last major release, and there's currently no way for anyone to change it back or to use a different default range. This filter allows for both cases.
Note, edits for pr is on in case someone has a better name for the filter.
> Offer a filter to customize the default date range

- includes/class-edd-cli.php
I changed the function so it filters the email before the get_recent_sales() method. #5774
> Add email parameter to wp edd sales command.

- assets/js/admin-scripts.js
- assets/js/edd-ajax.js
Using the more efficient `$( document.body )` vs `$( 'body' )` for example.
As a extend to the previous issue; https://github.com/easydigitaldownloads/easy-digital-downloads/pull/3707
> Use document.body where possible for performance

- .gitignore
- includes/misc-functions.php
- tests/tests-misc.php
In situations where there are multiple reverse proxies, there will be multiple IPs stored in $_SERVER['HTTP_X_FORWARDED_FOR'].
> Multiple reverse proxy IPs in $_SERVER['HTTP_X_FORWARDED_FOR']

- includes/class-edd-session.php
As `maybe_unserialize()` returns `mixed`, so should `EDD_Session()->get()`.
`EDD_Session()->set()` can accept strings and arrays as well as integers.
> Correct docblocks for EDD_Session get() and set() methods

- includes/cart/class-edd-cart.php
- includes/discount-functions.php
Ensure the return type of the `EDD_Cart::get_discounts()` method is always an `array` as specified in the docblock. 
Which is also consistent with the older `edd_get_cart_discounts()` function.
Also two other minor changes in the EDD_Cart class
- the `quantity` property is already set the `get_quantity` method
- make the `get_contents()` return type accurate
> Ensure EDD_Cart::get_discounts() return type is consistent

- includes/ajax-functions.php
- includes/class-edd-html-elements.php
Resolves #5884 
This does a couple things:
1) Introduces two filters `edd_product_dropdown_status_nopriv` and `edd_product_dropdown_status`
2) Users who cannot `edit_products`, default to `publish`
3) Users who _can_ `edit_products`, default to `publish, draft, private, future`
4) If, after allowing the filters through we run `sanitize_text_field` to be sure we don't get a bad value
5) If what we get back is not an array, we default back to `publish` only, no matter privs.
> Add ability to filter post_status for product dropdown #5884

- includes/class-edd-cli.php
> issue/6049 – Use a valid status in the payments create command docs.

- includes/admin/reporting/class-file-downloads-logs-list-table.php
As per the title, make the file download log IP addresses clickable through to the ARIN website.
> Make Download Log IP addresses clickable to ARIN website

- includes/payments/class-edd-payment.php
Backfill _edd_payment_user_id if its not the same as the one already there and also corrects typo.
Part of #6124
> Only backfill _edd_payment_user_id if its not the same as the one already there

- templates/history-purchases.php
Avoids a second query when using the action, where access to the payments would normally be needed
> Adding payments to before/after purchase history action

- includes/template-actions.php
These two strings in `includes/template-actions` were not translated.
> Translate two untranslated strings

- includes/process-download.php
The function edd_is_local_file() uses home_url() to check if a file is local.
Most of the times home_url() and site_url() are the same, but when they are different the correct function is site_url(). site_url() returns the URL for WordPress core files (like for example the uploads folder):
https://codex.wordpress.org/Function_Reference/site_url
This little difference makes WPML fail this check because home_url() has the language code attached while site_url() doesn't have it.
The problem was originally reported here:
https://wpml.org/forums/topic/edd-frontend-submission-form-translation-wrong-behaviour/
> Change home_url() to site_url() for WPML compatibility

- includes/admin/reporting/reports.php
- includes/reports/class-init.php
- includes/reports/data/class-base-object.php
- includes/reports/data/class-endpoint.php
- includes/reports/data/class-report.php
- includes/reports/data/class-table-endpoint.php
- includes/reports/reports-functions.php
- tests/reports/data/tests-report.php
- tests/reports/data/tests-table-endpoint.php
- tests/reports/data/tests-tile-endpoint.php
- tests/reports/tests-reports-functions.php
> Issue/6286 – Table endpoint support

- includes/shortcodes.php
If it's not too much trouble, I added two new hooks;
`edd_download_shortcode_item_before` & `edd_download_shortcode_item_before`
inside the `edd_downloads_query` function. With these two new hooks I (and others) can add extra code before and after the loop.
> Add hooks before and after downloads shortcode item

- includes/cart/class-edd-cart.php
Caused an error for me when I doing `reset( $content )` when the cart is empty because it returned `false`. 
Checking the EDD core code it only does `empty( $contents )` and ` if ( $contents )` type of checks, which should all react the same for returning `array()` as returning `false`
> Return expected array when cart contents are empty, not false

- includes/checkout/template.php
Instead of replacing the content dir with the content url, this could be done on the plugins path/url respectively.
Addresses #6044
> fix image src when plugins are not inside wp-content, fixes #6044

- includes/tax-functions.php
> Only run number_format if rate is 0, non-zero, and not an empty string - issue/6407

- includes/admin/customers/customers.php
The customer view displayed the ISO codes instead of the country and state names, making it somewhat confusing to users unfamiliar with ISO codes.
I have submitted PR (#6130) that aligns with this PR and adds a new `edd_get_state_name` function to the `country-functions.php` file that will return the state name when supplied with country and state codes.
Additionally a bug existed where manually entered "states" that had no pre-defined list, the name wasn't displayed when editing the customer record. I have fixed this bug and the size of the input box which was also incorrectly set.
> Show country and state name instead of codes for better UX

- includes/shortcodes.php
As per issue #6423, added support for sales and earnings.
> Add sales and earnings orderby support to [downloads] shortcode

- assets/js/admin-scripts.js
- includes/admin/tools.php
This will try to select the column when it has the right header (which is used when exporting payments/downloads from EDD). 
Selecting the columns once isn't that bad, but if you have to run a import like me more then once due to testing / developing this will be a hellish task to select each column every single import (test).
Before:
After:
If the field doesn't exist it won't break or anything, just won't pre-select it.
> Try and pre-select column when importing downloads/payments

- includes/admin/customers/customers.php
Makes the `Customer since {$date}` string is RTL-compatible (in some languages the date should precede the "customer since" part of the string).
Also makes sure translations are properly escaped.
> Make string RTL-compatible

- includes/admin/settings/register-settings.php
Resolves #6455
Showing the issue:
Only seems to happen for text fields when saving another settings section, no issue saving the value on the section itself.
Quick code snippet to reproduce:
```
add_filter( 'edd_settings_extensions', function( $settings ) {
$edd_ar_settings = array(
array(
'id' => 'edd_test_setting_head',
'name' => '<strong>' . __( 'Test setting', 'edd-auto-register' ) . '</strong>',
'type' => 'header',
),
array(
'id' => 'edd_test_text_setting',
'name' => __( 'Text setting', 'edd-auto-register' ),
'desc' => __( 'This will be emptied when saving ANOTHER section', 'edd-auto-register' ),
'type' => 'text',
),
);
return array_merge( $settings, $edd_ar_settings );
} );
```
> Fix text fields being unset when saving another settings section

- includes/admin/customers/class-customer-table.php
- includes/class-edd-customer-query.php
When looking at the customers table in admin and looking by email I got this error:
```
[27-Mar-2018 09:10:31 UTC] PHP Notice:  Undefined offset: 0 in /srv/www/themefusion-company/public_html/wp-content/plugins/easy-digital-downloads/includes/class-edd-customer-query.php on line 354
[27-Mar-2018 09:10:31 UTC] PHP Stack trace:
[27-Mar-2018 09:10:31 UTC] PHP   1. {main}() /srv/www/themefusion-company/public_html/wp-admin/edit.php:0
[27-Mar-2018 09:10:31 UTC] PHP   2. require_once() /srv/www/themefusion-company/public_html/wp-admin/edit.php:10
[27-Mar-2018 09:10:31 UTC] PHP   3. do_action($tag = 'download_page_edd-customers', $arg = *uninitialized*) /srv/www/themefusion-company/public_html/wp-admin/admin.php:224
[27-Mar-2018 09:10:31 UTC] PHP   4. WP_Hook->do_action($args = array (0 => '')) …
```
> Add a couple extra checks to avoid PHP errors

- includes/admin/tools.php
- includes/class-edd-logging.php
Fixes #6461 
1. Adds a paragraph under the Debug Log buttons, telling the user the path to the debug log file to make it easier to locate.
2. Adds `EDD_Logging::get_log_file_path()` to be able to be able to retrieve the location of the generated log file.
> Show the log file path on the Debug Log tool page #6461

- includes/cart/template.php
- tests/tests-checkout.php
Fixes #6400
1. Instead of using `did_action()` to see if hooks are being used, use `$wp_filter` to retrieve the callbacks of the hooks. _If_ callbacks exist, count those to determine the number of columns to add to the default column count (3).
> issue/6400 - correctly count cart columns based on hook usage

- assets/css/edd-admin.css
- assets/js/admin-scripts.js
- includes/admin/customers/customers.php
Fixes #5955 
1. Use different class for the HTML container that displays [error] messages when attempting to add an email address to a customer record from the customer card screen.
See final comments on the issue.
> issue/5955 - adjust error message container class for customer email management

- includes/shortcodes.php
Fixes #6436
1. Add support for `class` parameter in `[downloads]` shortcode.
> issue/6436 - add support for custom classes on downloads shortcode

- includes/admin/import/class-batch-import-payments.php
- includes/class-edd-cli.php
- includes/class-edd-discount.php
- includes/class-edd-download.php
- includes/gateways/paypal-standard.php
- includes/misc-functions.php
- includes/payments/functions.php
Fixes #6355
1. Any calls to `is_a` is switched to `instanceof` checks, for the performance improvements.
> Switch all is_a checks to instanceof #6355

- includes/country-functions.php
Fixes #6491
1. Switches _Genova_ to *Genoa* in the Italian list of states/provinces
> Genoa Italy, not Genova #6491

- includes/user-functions.php
Fixes #6490
1. By default, only attempts to shows the User API key input fields when `is_admin` is `true`
2. Adds `edd_show_user_api_key_fields` filter to allow plugin/theme/shop owners to alter this behavior for their specific needs.
> Allow showing/hiding user API key fields, default to is_admin only #6490

- includes/admin/settings/register-settings.php
Fixes #6455
1. Adding a case in for `edd_settings_sanitize` for `text` inputs to handle not clearing backwards compatibility of text inputs.
> Add specific sanitization for text inputs for EDD Settings API #6455

- includes/admin/settings/register-settings.php
- includes/checkout/template.php
- includes/process-purchase.php
Fixes #6484 
1. Add settings for privacy policy agreement, privacy policy agreement text, privacy policy page, and show privacy policy on checkout
2. Includes logic to handle showing 1 checkbox but two agreements/policies, or 2 individually.
> Support a separate privacy policy on checkout.

- includes/shortcodes.php
Fixes #6376 
1. Adds a hook pair before and after the output of the `[downloads]` shortcode and `No {plural_label} found` output.
> Issue/6376 -  add hooks before and after EDD download list output

- easy-digital-downloads.php
- includes/privacy-functions.php
- tests/tests-privacy.php
Fixes #6502 
1. Adds 3 new functions `edd_mask_string`, `edd_mask_domain`, and `edd_mask_email`.
2. The mask email function uses the mask domain, which uses the mask string. DRY style.
3. Adds in unit tests for cases I could think of
Note:
The domain parsing supports domains like `example.org`, `example.org.uk`, `test.example.com` and `test.example.org.uk`.
> Add String, domain, and email masking functions

- includes/admin/reporting/class-gateways-reports-table.php
- includes/admin/reporting/reports.php
This class name contained a typo, for a few years.
We can use `class_alias()` to rename the class without the typo, and still make sure anyone that might be using the old class name still can.
See #6549.
> Alias `EDD_Gateawy_Reports_Table` class.

- includes/admin/reporting/class-file-downloads-logs-list-table.php
- includes/admin/upgrades/classes/class-file-download-log-migration.php
- includes/admin/upgrades/upgrade-functions.php
- includes/admin/upgrades/upgrades.php
- includes/api/class-edd-api-v2.php
- includes/api/class-edd-api.php
- includes/download-functions.php
- includes/user-functions.php
Fixes #6548
1. Adds a migration routine to kill the `_edd_log_user_info` for the file download logs and add `_edd_log_customer_id` for the file download logs
2. Adds `edd_count_file_downloads_of_customer` to return the file download count of a customer record.
3. Updates `edd_count_file_downloads_of_user` to switch to the `edd_count_file_downloads_of_customer` function if the string is an email (this is what it was doing previously anyway, now it's explicit)
4. Updates the list table to use the proper customer ID instead of always performing searches on users (users mean nothing to EDD for the most part, customer should be our canonical).
5. Updates the file download log list table to search customers, not users (as a canonical source)
6. Updates the Customers API …
> Remove PII and switch file download logs to use customer ID #6548

- includes/payments/functions.php
- includes/privacy-functions.php
Fixes #6543 
Fixes #6544
1. Adds two exporters, customer record and order billing details to the WP Core data exporter
> Adds support for customer record and billing information from all payments for a customer record #6543

- includes/privacy-functions.php
Fixes #6498
1. Adds `edd_anonymize_email`, which hashes an email address with `<hash>@site.invalid`
2. Adds `edd_anonymize_customer`, which does the following:
```
- The name is changed to 'Anonymized Customer'
- The email address is anonymized, but kept in a format that passes is_email checks
- The date created is set to the timestamp of 0 (January 1, 1970)
- Notes are fully cleared
- Any additional email addresses are removed
```
3. Adds the `edd_register_privacy_erasers` function to help us register our erasers/anonymizers
4. Adds `edd_privacy_customer_eraser` which executes on the eraser/anonymizer
> Anonymize customer records when user delete requests are executed #6498

- includes/database/queries/class-base.php
- includes/database/schemas/class-column.php
Ready for initial merge into `release/3.0`.
We will need to introduce more exact validation functions and methods as they are identified and needed. In some cases these might be magic fallbacks, others may be able to use generic WordPress validation functions, and others might require unique solutions (BIGINT, LONGTEXT, etc...)
This PR includes an example fallback method for `DATETIME` columns. I've put it in the `EDD\DB\Column` class, because all columns of those types could use it. I can imagine having a dedicated interface class for fallback validation methods, but this seems OK for now.
See #6572.
> (WIP) - Issue/6572 - Just in time database column value validation

- includes/admin/settings/register-settings.php
- includes/payments/class-edd-payment.php
- includes/privacy-functions.php
Fixes #6497
1. Adds support for payment records to be anonymized or deleted.
2. Adds `_edd_anonymize_payment` to handle anonymizing or deleting a payment record
3. Modified `edd_anonymize_customer` to `_edd_anonymize_customer` to signify it's not a 'normal' function.
There is a filter in place associated with the status of a payment. By default these are the actions taken:
```
case 'publish':
case 'refunded':
case 'revoked':
$action = 'anonymize';
break;
case 'failed':
case 'abandoned':
$action = 'delete';
break;
case 'pending':
case 'processing':
default:
$action = 'none';
break;
```
TL;DR - Published, refunded, or revoked get anonymized, failed and abandoned get deleted, and pending or processing have no action taken as they are still possibly needed. No action is also …
> Add payment anonymizer/eraser that integrates with WP Core

- templates/shortcode-profile-editor.php
Fixes #6553
1. Encode the email address when it's being removed via [edd_profile_editor]
> issue/6553 - encode email string when removing email address

- includes/privacy-functions.php
Fixes #6501
1. Adds API Access logs to the data exporter
2. Deletes API Access logs on erasure request.
3. Fixed an issue where no customer is found yet an empty table was being displayed for the customer record on export.
> Add API access logs to export and support deleting #6501

- includes/privacy-functions.php
Fixes #6582 
1. Adds new data eraser process, that runs after the customer and payment handling that...
- Checks if any payments are remaining for the customer
- If there are, takes no action
- If there aren't, deletes the customer and its associated meta.
> After all payments and customer is processed, see if the customer can be deleted. #6582

- includes/payments/class-payments-query.php
Fixes https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6471
Reverts the change made in https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6178 and adds additional code to search within sequential payment numbers when entering just the numeric ID.
> Fix search not fully working

- includes/admin/settings/register-settings.php
Fixes #6588
1. Makes a new top level tab 'Privacy'
2. Moves the `Export & Erase` and `Privacy Policy` sections under it.
3. Improves the descriptive text for the `Export & Erase` settings.
> Move Privacy settings to their own tab, and rework the header for the payment action list #6588

- templates/history-downloads.php
The 'edd_download_history_files' action call passes the (probably leftover?) $id variable holding the current page id instead of a (more desirable) download_id.
> Pass download_id to download_history_files action

- assets/js/edd-ajax.js
- templates/edd.css
Fixes #6525
1. Remove qualifying selector in Javascript and CSS for the checkout form.
> Remove qualifying selector on purchase form submit button.

- includes/admin/settings/register-settings.php
- includes/install.php
- includes/privacy-functions.php
1. Removes the `Privacy` sub-section from the `Misc` tab after we moved `Privacy` to its own tab.
2. Removes the `Terms and Privacy Agreements` header in the `Misc -> Terms of Agreement` tab.
3. Sets the `update_file_download_log_data` upgrade as complete on a fresh install.
4. Adds some missing filters and incorrectly documented filters.
> Fixes a few items of feedback from 3rd party developers I had review the GDPR release.

- includes/admin/settings/register-settings.php
- includes/admin/upgrades/upgrade-functions.php
- includes/checkout/template.php
- includes/privacy-functions.php
- includes/process-purchase.php
Fixes #6596
1. Forces all checks for terms and privacy policy checkboxes to be explicitly strict type checked.
2. Updates the variable naming to make it more clear what is going on during the process ( as it was hard to debug due to naming conventions)
3. Fixes an issue with logging the privacy policy time on the customer meta, due to an incorrect array index
4. Fixes an issue causing some timeouts when no privacy policy page is selected in the Settings > Privacy of WP Core yet EDD is being told to show the privacy policy on checkout.
> Be more strignent with policy checkbox settings and variable naming #6596

- includes/admin/reporting/class-export-customers.php
- includes/admin/reporting/class-export-download-history.php
- includes/admin/reporting/class-export-payments.php
- includes/admin/reporting/class-export.php
- includes/admin/reporting/export/class-batch-export-earnings-report.php
- includes/admin/tools.php
- includes/admin/tools/class-edd-tools-recount-all-stats.php
- includes/admin/tools/class-edd-tools-recount-customer-stats.php
- includes/admin/tools/class-edd-tools-recount-download-stats.php
- includes/admin/tools/class-edd-tools-recount-single-customer-stats.php
- includes/admin/tools/class-edd-tools-recount-store-earnings.php
- includes/admin/tools/class-edd-tools-reset-stats.php
- includes/admin/upgrades/classes/class-file-download-log-migration.php
- includes/admin/upgrades/upgrade-functions.php
- includes/misc-functions.php
- includes/process-download.php
* This replaces mulitple calls to `ignore_user_abort()` and `set_time_limit()`
* Ensures error control operators are used everywhere
* Reduces time limit from -infinity- to 6 hours (can be adjusted or filtered as necessary)
* Moves `edd_is_func_disabled()` towards bottom of file, near new function
* Adds strict type comparison in `in_array()` check
The results of this change will be improved compatibility with a myriad of hosting environments that disable certain functions, and also avoids rogue unterminated PHP processes from incomplete downloads where user aborts failed to be processed.
See #6602.
> (WIP) issue/6602 - improvements to memory/time related PHP function usage

- includes/formatting.php
- tests/tests-formatting.php
Fixes #5844
1. Introduce `currency` parameter to `edd_currency_decimal_filter()`
> issue/5844 - Allow for currency to be passed to `edd_currency_decimal_filter`

- includes/admin/payments/view-order-details.php
Fixes #5373 
1. Link to customer ID instead of user ID.
> User customer ID when viewing customer download logs. #5373

- includes/gateways/paypal-standard.php
Fixes #6605
1. Call `sleep()` on IPN actions if PDT is enabled too. PayPal PDT and IPN both sending data back to the site can cause a race condition to develop whereby the status of a payment is changed to `complete` twice triggering all the completed purchase actions to be triggered twice: double the license keys, double referrals in AffiliateWP etc.
> issue/6605 - Add sleep() if PayPal PDT is used.

- includes/admin/downloads/metabox.php
Fixes #6662 
1. Changes the role of `manage_shop_settings` to `view_shop_reports` for the Exclude Tax download setting.
> change manage_shop_settings to view_shop_reports for editing tax exclusion on a product level #6662

- includes/admin/settings/register-settings.php
Fixes #6676
1. When tax rates are saved with no tax rates entered, the array stored is an empty array instead of an array of keys with empty values.
> Leave an empty array if no tax rates are found #6676

- includes/admin/payments/actions.php
Fixes #6378 
1. When editing an order, and selecting 'new customer', instead of selecting an existing customer we now throw an error that stops the rest of the process, in order to prevent an incorrect association and data overwrite.
> Don't allow new customer email address to match an existing customer when editing an order #6378

- includes/user-functions.php
Fixes #6619
1. Verifies that an email address is returned from `get_the_author_meta` before continuing to set them to pending.
> Verify an email address is returned before setting a user to pending and attaching payments #6619

- includes/emails/class-edd-email-tags.php
Fixes #6604
1. Defines `EDD_Email_Template_Tags $tags` as an array on instantiation.
2. Forces `edd_get_emails_tags_list` to format the return of `edd_get_email_tags` as an `(array)`
> Force email tags to be an array #6604

- includes/payments/class-edd-payment.php
Fixes #6563
1. Changes the `price` value of `EDD_Payment::modify_cart_item` to account for prices inclusive of tax.
> Respect prices inclusive of tax when modifying a cart item #6563

- includes/actions.php
- includes/cart/actions.php
- includes/checkout/functions.php
#6668
1. ~Updates `edd_is_checkout` to use a global to cache for this thread, in order to reduce a number of calls to the function over and over.~
2. Adds a condition to `edd_get_checkout_uri` to detect if the current URL is a checkout, to return itself, instead of the default checkout URI only.
3. Adds new 'delayed hooks', so that things like `edd_add_to_cart` can run later than `init` in order to allow proper page detection, which allows determining what checkout page to redirect to.
> Fix alternate checkouts with better edd_is_checkout and edd_get_checkout_uri detection #6668

- includes/admin/settings/register-settings.php
Fixes #6724
1. Fix copy [& edit] pasta on the setting ID for showing Privacy Policy on checkout.
> issue/6724 - fix incorrect setting ID for showing privacy policy on checkout

- includes/admin/settings/register-settings.php
Fixes #6719
1. Replace the link to our newsletter sign up form found at the bottom of the Tracking settings page
> issue/6719 - point newsletter links to EDD site Subscribe page

- includes/misc-functions.php
- tests/tests-misc.php
Fixes #6817
1. Adds a check for query strings in file extension detection.
2. Adds unit test to verify the new case.
> Remove query strings from file extensions before returning them #6817

- assets/css/edd-admin.css
- includes/admin/downloads/metabox.php
Fixes #6826 
1. Move Download Settings tooltips to display beside the headings of the metabox sections
2. Add tooltip for Accounting Options section
> issue/6826 - reposition Download Settings metabox tooltips

- includes/class-edd-session.php
Per #6648, the original change to allow EDD sessions in the admin for all page requests, even when FES isn't even installed, and not limited to edit and/or admin views of the download screen should be reverted in EDD core to prevent against extremely dangerous amounts of sessions being started, and instead (as outlined on the ticket) should be implemented using the existing filter by using it in FES, so the behavior is only altered for FES users.
This also allows FES a lot more flexibility in the future.
FES PR: https://github.com/easydigitaldownloads/edd-fes/pull/1413
> Revert #6648 EDD Session to start in wp-admin

- includes/ajax-functions.php
Fixes #6882
1.Updates the logic for adding an item to an order via admin, to properly find the price ID, since `index` is not the value determined by the price ID, but the array key is.
> Fix ajax for adding item to order not finding variable prices #6882

- includes/error-tracking.php
Fixes #6895
1. Ensure an error key exists before trying to remove it.
> Ensure an error exists before trying to remove it.

- assets/css/edd-admin.css
> Issue/6907 - Prevent vertical scrollbar in Firefox when hovering over tooltip

- includes/admin/settings/register-settings.php
Anything still filtering `edd_settings_styles` will surface the original tab.
Fixes #6877
1. Removes "Styles" tab by default.
2. Moves old style settings to more appropriate existing setting sections.
> Remove "Styles" tab by default.

- includes/process-download.php
Fixes #6886
1. In the chunked file download, we were using `set_time_limit` without verifyign it is available with `edd_is_func_disabled()`
> Check if set_time_limit is enabled before using it in chunked file download #6886

- includes/class-edd-download.php
Fixes #6745
1. Fixes `EDD_Download::update_meta` to only return `false` for an empty `$meta_value` if the `$meta_value` _is not_ numeric.
> Allow setting numeric download meta to 0 #6745

- includes/process-purchase.php
Fixes #6708
1. Updates the 'MN' regex for postal code verification to look for a 5 digit number instead of 6.
> Update mongolia to a 5 digit postal code verification #6708

- includes/reports/data/downloads/class-top-selling-downloads-list-table.php
Fixes #6930 
1. Removes the call to `wp_filter_object_list` as that was being incorrectly used.
2. Finds the actual Price ID of the item and displays it instead of always assuming price ID `0`
> Fix showing variable prices in the best selling downloads report #6930

- includes/class-edd-license-handler.php
Fixes #6835
1. Adds the `item_id` parameter to the `activate_license`, `deactivate_license`, and `weekly_license_check` API requests at the store URLs
> Send item_id along with the activation deactivation and weekly checks #6835

- includes/checkout/functions.php
Fixes #6941 
Adds the lock icon back when SSL is enabled at checkout.
> Issue/6941 - Fix SVG lock icon at checkout

- includes/admin/thickbox.php
Fixes #6950 
1. Keeps the current system in place of just using the select option value as a class in the shortcode and purchase link output. But before inserting that class, check its value against the `text link` option and adjust it to `plain` if necessary.
> issue/6950 - use correct class name when inserting purchase link

- includes/process-download.php
1. Provides `$args` array to edd_requested_file filter, providing additional context 
This is necessary for plugins that need to make changes to the download delivery that uses information from the purchase or purchaser.
> Pass all available contextual arguments to edd_requested_file filter.

- includes/gateways/amazon-payments.php
Fixes #6958
1. Per the amazon representative, there is only a single URL that we need to use now...and this is it.
> Updating registration URL per Amazon Rep #6958

- includes/shortcodes.php
Customer names like `O'Connor` currently get saved as `O\'Connor`.
1. Strip slashes from customer names when updating via the profile form
> Strip slashes from names when updated by profile form

- includes/ajax-functions.php
- includes/download-functions.php
- includes/orders/classes/class-order-item.php
Fixes #6938
1. Updates the AJAX Call to check if a product has variable prices, not if the price ID is `0`.
2. Fixed display issue of names to avoid checking `empty` on price Id, and instead check the product for variable pricing.
> Fixing adding new items to orders with a price ID of 0 #6938

- includes/payments/actions.php
Fixes #6971
1. Isolates fee IDs when doing a cart recovery to avoid duplicating their output
> Isolating fees by ID when doing a cart recovery #6971

- includes/class-edd-logging.php
Fixes #6243
1. When `edd_debug_log` is called, converts the message to UTF-8 to avoid issues with character encoding.
So far the only sample set we have is from PayPal, but if someone has a way to replicate this easily, that'd be ideal.
> Proposed: Convert all debug entries to UTF-8 #6243

- includes/admin/payments/view-order-details.php
Fixes #7035
EDD 2.9.4 added nonces to AJAX actions. See: https://easydigitaldownloads.com/development/2018/07/09/important-update-to-ajax-requests-in-easy-digital-downloads-2-9-4/
1. Add missing nonce attribute to the Country select field (chosen) on the Edit Payment screen. The corresponding nonce support already exists in the JS for editing the payment.
> add missing nonce data attribute to country select - issue/7035

- includes/checkout/template.php
Fixes #7027, #6598
1. Remove Privacy Policy related output from `edd_terms_agreement()` function so that nothing related to the Privacy Policy depends on separate Agree to Terms functionality.
2. Refactor `edd_privacy_agreement()` so that **Agree to Privacy Policy** setting output (checkbox and label) and **Show the Privacy Policy on checkout** setting output (expandable/collapsible policy content) can display independently.
3. Only show Agreement Text container if there is actual content to display.
> issue/7027 - refactor Privacy Policy and Agree to Terms output

- includes/api/class-edd-api.php
Fixes #7058
1. Removes checks for the completed upgrade for the migration of the api keys to the new format for performance, as it's nearly 4 years old (EDD 2.4).
> Remove checks for upgrade_user_api_keys upgrade routine #7058

- includes/admin/upgrades/upgrades.php
- includes/scripts.php
Fixes #6856 
1. Adds the JS for the export tools to allow the AJAX handling of the upgrades
2. Sends in a `$hook` so that we can enqueue the JS for this page only when needed.
> Enqueue the edd-admin-tools-export.js on the upgrade page #6856

- includes/class-stats.php
1. Avoid PHP notice by using dynamic table names
> [3.0] fix: do not use hardcoded table names

- assets/css/edd-admin.css
Fixes #7080
1. Remove Gray Box on Vertical Sections 3.0 UI component.
--- 
Previously #7086 -- this time around `flexbox` is used to simplify vertical heights. The only difference for the 5% of people in the world using IE9 or lower is the left column stays white.
https://cloudup.com/cFQVuMKVSu2
https://cloudup.com/c4ZayRGuKtn
> [3.0] Remove Gray Box on Vertical Sections (Take 2)

- includes/admin/payments/actions.php
- includes/orders/functions/actions.php
Fixes #7096
Fixes #7052 
1. Avoid fatal errors when creating a customer via the new order or edit order screens.
---
- Fixes referencing unavailable input fields causing the validation to fail.
- Fixes referencing an undefined `$status` variable
- Fixes a few instances of potentially accessing an unavailable `$customer` object.
There are still more places where `$customer` is referenced with the assumption that the customer was properly created. I had a database that did not contain the `uuid` column which caused the customer creation to always fail. This is likely the original cause of #6791 as well.
> [3.0] Fix Customer Creation from New/Edit Order Screens

- includes/admin/settings/register-settings.php
- includes/tax-functions.php
Fixes #7109
~- Force enable taxes to be enabled if a rate was created (and is active) without previously globally enabling taxes.~
- Hide "Rates" subtab until global taxes are enabled
---
Someone may want to add a test case for the `edd_use_taxes()` being enabled via the option filter. I don't have a test environment setup on this machine currently.
> Create a better UX when managing tax settings

- includes/cart/functions.php
1. Fix incorrect `edd_get_cart_item_name( $item = array() )` param documentation from **int** to **array**.
> Fix incorrect param type in method documentation.

- includes/shortcodes.php
Fixes #7124
1. Ensure profile editor always allows customer data to be updated by creating a customer if one does not previously exist.
> Allow Customer Address Updating in [edd_profile_editor]

- includes/class-utilities.php
- tests/tests-date-functions.php
Fixes #7130
1. In the event of PHP 5.3 or 5.4, we determine a string based timezone from a lookup of the GMT offset in order to allow the instantiation of `DateTimeZone` without a fatal error.
> Account for DateTimeZone look-ups i PHP 5.3 and 5.4 when a GMT is selected #7130

- includes/admin/payments/class-payments-table.php
Fixes #7118
1. Changes the default column for the orders list table to `date_created` instead of `id`
> Default sort for orders list tables should be date_created, not ID, to give a better user experiance #7118

- includes/admin/payments/class-payments-table.php
Fixes #7079
1. Updates the collection of orders for the list table to include the `$_GET` variables for the counts as well
> Fix counts not updating with order list table filters #7079

- includes/admin/admin-pages.php
**Fixes a conditonal check typo at `edd_is_admin_page();`**
Switch case for 'settings' submenu page has a conditional check for 'general' tab which is spelled 'genera'.
> Fix Conditional Check Typo at edd_is_admin_page()

- includes/admin/payments/orders.php
Fixes #7149 
1. Adds the `show_variations_only` argument to the `HTML::product_dropdown` call which was added in #6760
> Set show_variations_only on product selector when creating a new order #7149

- CONTRIBUTING.md
Resolves #7166
1. Adds a section to the `CONTRIBUTING.MD` that links to the DCO
> Adding DCO to the CONTRIBUTING.MD file #7166

- includes/admin/upgrades/v3/class-data-migrator.php
Fixes #7170 
1. At all points where an order is created, also creates an order with a type of `refund` if the main `sale` order is marked as `refunded`.
> Initial pass at migrating refunded orders with a propr refund order #7170

- includes/gateways/paypal-standard.php
Fixes #7190 
1. Only fires PDT when on the same purchase session.
> PDT should only run when on the same purchase session #7190

- includes/class-edd-license-handler.php
Fixes #6835
1. If the item_id is defined, send it along with the payload for activate, deactivate, and weekly checks.
> Add item_id to activate, deactivate, and weekly checks #6835

- includes/payments/class-edd-payment.php
#7215 The user data uses the discounts data. Therefore the discounts need to be set up prior to the user.
> Fix race condition with discounts -> user in EDD_Payment

- includes/admin/upgrades/v3/class-data-migrator.php
Fixes #7225
1. If an order is migrated and is _not_ in a _non-completed_ status, and has a missing date_completed, use the post_date_gmt
> Backfill date_completed times #7225

- includes/database/tables/class-customers.php
Fixes #7236
1. Add the `uuid` column inside of `maybe_upgrade()`
> Issue/7236 - Create Customer `uuid` column when upgrading from 2.9

- includes/admin/class-list-table.php
- includes/admin/customers/class-customer-addresses-table.php
- includes/admin/customers/class-customer-email-addresses-table.php
- includes/admin/customers/class-customer-table.php
- includes/admin/discounts/class-discount-codes-table.php
- includes/admin/payments/class-order-adjustments-table.php
- includes/admin/payments/class-order-items-table.php
- includes/admin/payments/class-payments-table.php
- includes/admin/reporting/class-base-logs-list-table.php
- includes/admin/reporting/class-download-reports-table.php
- includes/database/engine/class-query.php
Fixes #7208.
1. Add `parse_pagination_args()` method to Base List Table class
2. Use `parse_pagination_args()` where necessary
3. A few small tweaks to the main `Query` class
This needs testing across:
> Issue/7208 - Paged/Limit/Offset handling between List Table & Query class

- includes/api/class-edd-api-v2.php
When passing an array of categories a warning is thrown due to the fact that there is no check if categories is a string first.
Fixes #7176
1. Add category string check to product api to avoid PHP warnings
> Fix strpos warning when using product API

- includes/install.php
Closes #7200
1. Remove deprecated `wpmu_new_blog` usage in favor of `wp_initialize_site`
> Remove Deprecated wpmu_new_blog Usage

- includes/checkout/template.php
Fixes #7247
1. Wraps the default purchase link button in `edd_checkout_button_purchase` to verify that we have active gateways, to prevent a whitescreen when there are no gateways selected.
> If no gateways are active, do not show the purchase button by default (filter still runs)

- includes/admin/discounts/add-discount.php
- includes/discount-functions.php
Fixes #7263
1. Change the add discount product requirements field to follow suite with `product_reqs` as the input name, instead of `products`.
> Fix saving product requirements when creating new discount #7263

- includes/admin/class-edd-notices.php
- includes/admin/payments/actions.php
- includes/admin/payments/class-order-items-table.php
- includes/admin/payments/class-payments-table.php
- includes/misc-functions.php
- includes/orders/functions/orders.php
- tests/orders/tests-trash.php
Fixes #7245 
Fixes #7224 
1. Adds functions for trashing, and restoring.
2. Adds functions for checking something is trashable or restorable.
3. Extends the list table to be able to work with the statuses.
4. Fixes the bulk actions not working
5. Adds Trash and Restore to the bulk actions (conditionally)
> Introduce 'Trash' and 'Restore' for orders and bulk actions.

- includes/orders/functions/orders.php
Fixes #7085
1. Allows order items to inherit the date_created in edd_add_order
> Allow order items to inherit the date_craeted in edd_add_order #7085

- includes/payments/functions.php
- tests/bootstrap.php
- tests/tests-payments.php
Fixes #7292
1. Changes all references to possibly using post_status and WP_Post objects to using an EDD_Payment object.
2. Swaps use of literal status labels for the keys, which are not translated.
> Refactor how edd_get_payment_status finds the status, with unit tests  #7292

- includes/admin/upgrades/v3/class-data-migrator.php
- includes/database/tables/class-order-items.php
- includes/misc-functions.php
- includes/orders/functions/refunds.php
- tests/orders/tests-refunds.php
- tests/phpunit/factories/class-edd-factory-for-orders.php
Fixes #7307
1. Updates `edd_order_items` table to use `signed int` for the `quantity` column.
2. Adds new `edd_negate_int` function and implements for negating integers instead of assuming floats.
3. Unit tests to verify negative values for refunded quantity
> Fix edd_order_item table to accept negative integers for quantity #7307

- includes/admin/upgrades/upgrade-functions.php
Fixes #7282
1. Changes the wording for each migration step to reference the data being migrated, instead of just being 'orders'
> Update the messaging for the upgrade steps to be specific to the data being migrated #7282

- includes/admin/upgrades/v3/class-data-migrator.php
- includes/database/tables/class-customer-addresses.php
- includes/database/tables/class-order-addresses.php
Fixes #7302 
1. Converts the `first_name` and `last_name` columns in the `edd_order_addresses` table to a single `name` column, including upgrade routine to add the column, concat the strings to the new column, and removing the old column.
2. Adds the `name` column to the `edd_customer_addresses` table, including upgrade routine.
3. Updates the data migrator to use the new columns.
> Move to using single 'name' column for customer/order addresses

- includes/reports/data/customers/class-most-valuable-customers-list-table.php
- includes/reports/data/customers/class-top-five-customers-list-table.php
Fixes #7331
1. Allow "Most Valuable Customers" and "Top 5 Customers" Report List Tables to properly set the report data by overriding the `get_data()` method, instead of the deprecated (and uncalled) `reports_data()` method.
> 3.0 - Override get_data() Methods in Customer Report List Tables

- includes/admin/payments/class-order-items-table.php
- includes/admin/upgrades/v3/class-data-migrator.php
- includes/download-functions.php
- includes/emails/tags.php
- includes/emails/template.php
- includes/orders/classes/class-order-item.php
- includes/orders/functions/orders.php
- templates/shortcode-receipt.php
Fixes #7308
1. Adds logic to `edd_build_order` to add the price ID name to an order_item when one exists.
2. Adds logic to the EDD order migrator to add the price ID name to an order_item when one exists.
> Add price name to order_items table #7308

- includes/admin/customers/customer-actions.php
- includes/class-edd-customer.php
- tests/customers/tests-customers.php
Fixes #7321
1. Alters the change and remove User ID actions when altering a customer to alter the orders as well.
> Consistently handle user ID changes on orders and customer

- includes/class-edd-discount.php
- includes/discount-functions.php
- tests/discounts/tests-discount-meta.php
- tests/discounts/tests-discounts.php
Fixes #7349 
1. Updates unit tests around product_conditions
2. Adds `product_conditions` to the meta table
3. Removes `product_conditions` from the meta table when product requirements are removed from a discount.
> Fix product condition meta

- .travis.yml
- includes/admin/customers/customer-actions.php
- includes/class-edd-customer.php
- includes/class-edd-discount.php
- includes/class-utilities.php
- includes/database/engine/class-query.php
- includes/discount-functions.php
- includes/emails/template.php
- includes/orders/functions/orders.php
- tests/customers/tests-customers.php
- tests/discounts/tests-discount-meta.php
- tests/discounts/tests-discounts.php
- tests/reports/tests-reports-functions.php
- tests/tests-date-functions.php
- tests/tests-misc.php
Fixes #7243 
I am not sure why this was being prevented. The furthest back I was able to trace it was here:
https://github.com/easydigitaldownloads/easy-digital-downloads/blame/release/3.0/includes/orders/functions/orders.php#L1003
Any ideas why that line might have been added @JJJ? Do you think it is safe to remove it?
Additionally, this issue uncovered an issue with the flow to the gateway. The gateways were recording this properly, while EDD was not (and thus the customer's receipt was for the wrong amount). 
That is because [send_to_gateway](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/issue/7243/includes/process-purchase.php#L195) is passed data from the session, as opposed to data from the custom tables.
To ensure that the same data is used for everything (and …
> Fix fees not being applied to orders

- includes/class-stats.php
Fixes #7360 
1. In the stats class we now force the `type` to be an array if it's not.
2. Fixed the calls to the stats class to make the `type` an array.
> Corrected an issue where we sent in strings instead of arrays to the stats class, and account for this in the stats class #7360

- includes/orders/functions/refunds.php
Fixes #7286
1. Removes the logging of the refund in the general log
We may bring this back but currently this is the only type of order action logged in the general logging, and we do make a log on the order itself. Removing it for now.
> Don't add a general log entry for refunds for now #7286

- includes/reports/class-init.php
Fixes #7395
1. Add a try/catch block
2. Fix DocBlock hinting on the $reports parameter
> issue/7395 – Wrap add_report() calls in a try/catch block in legacy_reports()

- includes/payments/class-edd-payment.php
Fixes #6798 
1. Adds the `total` to the call to `edd_add_order_transaction` in the `EDD_Payment` class.
> Fix orders entering 0 for transaction amounts #6798

- includes/admin/payments/class-payments-table.php
Fixes #6803
1. Swaps the `s` argument to `search` which is what the query class is expecting.
> Fix searching payment history #6803

- includes/orders/functions/refunds.php
Fixes #7400 
1. Use a true bool when checking if a refund should be processed, and use an explicit bool check when comparing filter result.
> 3.0 - Explicit bool Check on Refund Availability

- includes/class-edd-register-meta.php
Fixes #7425
1. Adds the `object_subtype` to all download and payment meta registrations.
> Add object_subtype to register_meta calls #7425

- includes/admin/import/class-batch-import-downloads.php
- includes/admin/import/class-batch-import.php
Fixes #7199
1. Introduce a `convert_file_string_to_array()` method that ignores `/`s in the file value
This resolves the issue completely without introducing significant complications nor extension-specific compatibility.
> Introduce convert_file_string_to_array() for product import that ignores / for delimiters. #7199

- webpack.config.js
Closes #7457
Use `webpack.ProvidePlugin` to ensure jQuery and $ point both variables to the external jQuery module.
> 3.0 - Fix "$ is not a function"

- includes/shortcodes.php
Fixes #7378
1. Save the address `country` when updating or adding an address via the profile editor shortcode.
> Save country when editing or setting address via shortcode #7378

- includes/compat/class-customer.php
Fixes #7458
1. Adjust backwards compatibility for `_edd_user_address` user meta so that we return an array containing the array of address data.
> Return backwards compat customer address inside another array #7458

- assets/css/edd-admin.css
- includes/admin/notes/note-functions.php
Fixes #7525 
1. Adjust "Notes" markup and styles.
> issue/7525 - Adjust Note Markup and Styles

- assets/css/edd-admin.css
- includes/admin/payments/orders.php
- includes/admin/payments/view-order-details.php
Closes #7524
1. Convert separate "Logs" box to section in the "Order Details" box.
> issue/7524 - Move "Logs" to "Order Details" Section

- includes/admin/reporting/reports.php
Fixes #7532
1. Ensure Reports can be exported.
---
Note: If not previously compiled you may need to run `npm install && npm run build`
> issue/7532 - Enqueue Export Script in Reports > Export

- assets/css/edd-admin.css
Fixes #7526 
1. Use `box-shadow` for Vertical Tab Active State (creates a straight line).
> issue/7626 - Use box-shadow for Vertical Tab Active State

- includes/orders/functions/types.php
Fixes #7527 
1. Use "Order" and "Orders" for `sale` Order Type UI labels.
> Use "Order" and "Orders" for `sale` Order Type UI labels

- includes/admin/customers/customers.php
- includes/admin/notes/note-functions.php
- includes/admin/payments/class-payments-table.php
- includes/admin/payments/orders.php
- includes/date-functions.php
Fixes #7589 
1. Show order completed date in site time zone.
2. Show order & customer notes in site time zone.
3. Show customer Agreements dates in site time zone. Also append site time zone abbreviation.
4. Show customer addresses "First Used" date column in site time zone. Also append time zone abbreviation.
5. Show customer recent orders "Completed" date column in site time zone. Also append time zone abbreviation.
6. Correct an array key error in `edd_get_hour_values()` function. There was an incorrect entry for `'03' => '02',` when it should have been `'02' => '02',`.
> Issue/7589 - Correct date timezones on Orders, Notes, & Customers pages

- assets/css/edd-admin.css
Fixes #7580
1. Ensure "Amount Type" input group works on 5.3+
> issue/7580 - Ensure "Amount Type" Input Group Works on WP 5.3+

- includes/admin/discounts/discount-actions.php
Fixes #7577
1. Ensure "Use Once Per Customer" setting is honored when editing a Discount.
> issue/7577 - Save "Use Once Per Customer" Setting When Editing Discount

- includes/admin/discounts/discount-actions.php
- includes/admin/discounts/edit-discount.php
Fixes #7581 
1. Ensure Discount start and end dates can be left blank.
> issue/7581 - Ensure Discount Start/End Dates Can Be Blank

- assets/js/admin/discounts/index.js
- includes/admin/discounts/add-discount.php
- includes/admin/discounts/edit-discount.php
Fixes #7542 
1. Ensure adding or editing a discount shows product requirement conditions when applicable.
---
Note: Run `npm install && npm run dev`
> issue/7542 - Ensure Adding/Editing Discounts Allow Product Requirement Conditions

- assets/css/edd-admin.css
- includes/admin/payments/orders.php
Fixes #7523 
1. Create more flexible labels for order details.
> issue/7523 - Remove Right-Aligned Labels in Orders

- includes/admin/customers/customers.php
Fixes #7564 
1. Show separate tables for Orders and Refunds when viewing a Customer record.
2. Adjust table column headers from "Amount" to "Total" and "Completed" to "Date"
> issue/7564 - Separate Orders and Refunds in Customer Details

- includes/discount-functions.php
Fixes #7576
1.Adjustment meta is now only deleted if it's explicitly passed through to `edd_update_discount()` as an empty value. Previously running this would delete `product_reqs` because the value was omitted: `edd_update_discount( 1, array( 'name' => 'New Name' ) );` . Now to remove `product_reqs` you'd have to explicitly pass through `product_reqs` like this: `edd_update_discount( 1, array( 'name' => 'New Name', 'product_reqs' => '' ) );`
> Only delete discount meta if it's explicitly being set to an empty value #7576

- includes/database/engine/class-table.php
- includes/database/tables/class-adjustment-meta.php
- includes/database/tables/class-adjustments.php
- includes/database/tables/class-customer-addresses.php
- includes/database/tables/class-customer-email-addresses.php
- includes/database/tables/class-customer-meta.php
- includes/database/tables/class-customers.php
- includes/database/tables/class-log-meta.php
- includes/database/tables/class-logs-api-request-meta.php
- includes/database/tables/class-logs-api-requests.php
- includes/database/tables/class-logs-file-download-meta.php
- includes/database/tables/class-logs-file-downloads.php
- includes/database/tables/class-logs.php
- includes/database/tables/class-note-meta.php
- includes/database/tables/class-notes.php
- includes/database/tables/class-order-addresses.php
- includes/database/tables/class-order-adjustment-meta.php
- includes/database/tables/class-order-adjustments.php
- includes/database/tables/class-order-item-meta.php
- includes/database/tables/class-order-items.php
- includes/database/tables/class-order-meta.php
- includes/database/tables/class-order-transactions.php
- includes/database/tables/class-orders.php
Fixes #7579
1. Updates all database table version numbers to new 9 digit format: from `{YYYY}{mm}{dd}{xxxx}` to `{YYYY}{mm}{dd}{x}`.
2. Hooks into `EDD\Database\Table::get_db_version()` to detect if the stored version is 12 digits instead of the new 9. If so, converts to the new length (essentially just strips off the 3 prefixed zeros) and updates the version number in the database. This ensures all upgrades will still continue to be processed in order.
3. Removed unnecessary third parameter in `EDD\Database\Table::delete_db_version()` `delete_option()` calls. (Those functions only take 2 parameters but 3 were being passed.)
> Convert DB table version numbers to 9 digits. #7579

- includes/admin/upgrades/v3/class-data-migrator.php
This fixes fatal PHP errors when running the v3 Step 1 Order migration.
Fixes #7620
1. Adds proper root namespace prefix to DateTime & DateInterval class usages.
> Add namespace root for DateTime & DateInterval

- includes/download-functions.php
Fixes #7627
1. Restores the default value, now that the logic for checking limited downloads is nested.
> Retain default value for return #7627

- includes/cart/class-edd-cart.php
Fixes #7450
1. Adds `$download_id` and `$options` to the filter for `edd_pre_add_to_cart_contents`
> Add download_id and options to the EDD_Cart::edd_pre_add_to_cart_contents method #7450

- includes/orders/functions/actions.php
Fixes #7565 
1. When creating an order use the download's variable price name.
> issue/7565 - Use Price Variation Name when Creating an Order

- assets/css/edd-admin.css
- includes/admin/payments/orders.php
Fixes #7569 
1. Preselects the Customer's primary email address.
2. Adds setting description directly under the setting.
3. Adds valid markup for a list of radios.
> issue/7569 - Adjust "Email" Order Details Section UI/UX

- includes/shortcodes.php
Fixes #7378 
The country field was not being saved/updated which is why it was not being populated in the short code.
1. Save the country field on profile edit.
> Save country field on edd_edit_user_profile

- includes/admin/payments/class-payments-table.php
Fixes #7634 
1. Removes dead code inside `EDD_Payment_History_Table`
2. Ensures `edd_payments_table_column` is run with a column name of `email`
> issue/7634 - Restore "Email" Column Filter in Payments Table

- includes/cart/class-edd-cart.php
Adds the additional suggested fix from #6901. In some cases, it was
still possible for the items subtotal to be 0, which caused a
mathematical error.
Fixes #7613
> Fix division by zero error

- assets/css/edd-admin.css
- includes/admin/reporting/graphing.php
- includes/admin/reporting/reports-callbacks.php
- includes/admin/reporting/reports.php
- includes/class-stats.php
- includes/reports/data/class-report-registry.php
- includes/reports/data/customers/class-most-valuable-customers-list-table.php
- includes/reports/data/customers/class-top-five-customers-list-table.php
- includes/reports/data/downloads/class-earnings-by-taxonomy-list-table.php
- includes/reports/reports-functions.php
- tests/reports/data/tests-reports-registry.php
Fixes #7644 
1. Reintroduce filter to "Exclude taxes" in report calculations.
> issue/7644 - Enable "Exclude Taxes" in Reports

- includes/admin/reporting/class-edd-graph.php
Fixes #7616 
1. Ensure legacy Flot tooltips appear above content.
Brings tooltips above https://github.com/easydigitaldownloads/easy-digital-downloads/blob/9f305f2ddc1250fb0cab20d73df81cddfe31fa07/assets/css/edd-admin.css#L2704-L2708
> issue/7616 - Ensure Legacy Flot Tooltips Appear Above Content

- includes/admin/reporting/reports.php
- includes/class-stats.php
- tests/orders/tests-stats.php
Fixes #7637 
1. Include type SQL in `get_order_count()`. This ensures `type = 'refund'` condition is picked up in refund count queries, and that refund records are not picked up in order queries.
2. Include type SQL `get_order_earnings()`. This ensures `type = 'refund'` condition is picked up refund amounts queries, and that refund records are not picked up in order queries.
3. `get_order_earnings()` now sets default query vars for `type = 'sale'` and `status = array( 'complete', 'revoked', 'refunded', 'partially_refunded' );`. These can be overridden. But these changes ensure that the `Sale / Earnings` report shows gross earnings, before factoring in refunds. See https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7637#issuecomment-597617049
4. …
> Issue/7637 Correct refund report queries

- includes/admin/payments/class-payments-table.php
Fixes #7636
1. Wraps `edd_get_payment()` function and associated `edd_payment_row_actions` filter in `has_filter()` check. This ensures it only runs if the filter is actually hooked into.
2. Deprecate `edd_payment_row_actions`.
3. Introduce replacement filter `edd_order_row_actions` that passes in the `EDD\Orders\Order` object.
> Issue/7636 - Wrap old row actions filter in has_filter() and introduce replacement

- includes/class-stats.php
- includes/payments/class-payment-stats.php
Fixes #7652 
1. Restore `edd_payment_stats_post_statuses` filter and ensure all stats use a consistent set of statuses.
> issue/7652 - Restore `edd_payment_stats_post_statuses` Filter

- includes/admin/reporting/reports-callbacks.php
Fixes #7663
1. Modifies query for Sales and Earnings chart to add `type = 'sale'` and `status IN(...)` conditions.
> Limit Sales & Earnings chart to sale objects with certain statuses #7663

- assets/css/edd-admin.css
- includes/admin/reporting/class-categories-reports-table.php
- includes/admin/reporting/graphing.php
- includes/deprecated-functions.php
- includes/reports/class-init.php
Fixes #7615 
1. Deprecates `edd_reports_graph_controls()` in favor of attaching filters to registered legacy reports.
2. Ensures filter data is available in URLs for legacy reports that still access it directly.
> issue/7615 - Fix Filters for Legacy Reports

- includes/admin/payments/class-payments-table.php
Fixes #7651 
1. Ensures extensions using `edd_payments_table_views` can still set their own labels and counts.
> issue/7651 - Restore `edd_payments_table_views` Filter

- includes/misc-functions.php
- includes/orders/functions/refunds.php
- includes/payments/functions.php
- tests/orders/tests-payments.php
Fixes #7640 
1. Set an Order status to "Partially Refunded" when one or more, but not all, Order Items are refunded.
> issue/7640 - Set Orders to "Partially Refunded" When Refunding an Order Item

- includes/admin/upload-functions.php
Fixes #6356 
1. Removed wp_is_writable() shim
2. Shim is not needed after WordPress 3.6
> removed dated wp_is_writable shim function #6356

- includes/admin/reporting/reports.php
Fixes #7673 
1. Correct references to the wrong `$filter` variable when getting the `$dates` ranges.
> Fixing reporting warnings of undefined variables #7673

- includes/admin/reporting/reports.php
Fixes #7670 
1. Remove "Product" filtering from Refund reports until queries support filtering.
> issue/7670 - Remove Product Filtering From Refund Reports

- assets/css/edd-admin-chosen.css
Fixes #7649
1. Removed css opacity for `select` drop downs so they do not appear disabled on mobile
2. Removed height and max-width from same rule so as not to override WP Core styles
> removed css that made dropdowns appear disabled #7649

- CONTRIBUTING.md
Updates the `GitHub Pull Request documentation` link in "Additional Resources"
> Fix Broken Link in CONTRIBUTING.md

- includes/admin/upgrades/v3/class-data-migrator.php
Fixes #7689
Uses fallback `edd_get_currency()` when the payment meta currency is empty (as suggested in #7689).
> Fallback to site currency when payment currency meta is empty.

- includes/download-functions.php
Fixes #7745
1. Moves the logic for the check on the purchase level, only when the store is not unlimited.
> Only check if the purchase has unlimited downloads when the store is not unlimited #7745

- includes/class-structured-data.php
- tests/tests-structured-data.php
Fixes #7387 
1. Only include `image` if one exists.
2. Only include `description` if one exists.
3. Fallback to the Download ID if no unique SKU is set.
4. Set `priceValidUntil` for each offer.
> issue/7387 - Adjust JSON-LD Structured Data for Downloads

- includes/reports/reports-functions.php
- tests/reports/tests-reports-functions.php
Fixes #7693
1. Ensures parsing `last_month` on a date with more days than the previous still fetches the true "last month"
> issue/7693 - 3.0 - Ensure last_month Is Parsed With No Overflow

- includes/admin/customers/customers.php
Fixes #7725 
1. Added hidden label to email field for screen reader accessibility
To Test:
1. Downloads -> Customers -> Customer Emails
2. No label visible, only placeholder text
3. Inspect field element and see hidden label
> Issue 7725, Add Hidden Label for Email Field

- includes/admin/reporting/reports-callbacks.php
- includes/admin/reporting/reports.php
- includes/class-stats.php
- includes/reports/data/customers/class-most-valuable-customers-list-table.php
- includes/reports/data/customers/class-top-five-customers-list-table.php
- includes/reports/data/downloads/class-earnings-by-taxonomy-list-table.php
Fixes #7692
1. Updates all reports to exclude taxes by querying `SUM(total - tax)` instead of `SUM(subtotal)`.
> Exclude taxes with SUM(total - tax) instead of SUM(subtotal) #7692

- includes/admin/discounts/add-discount.php
- includes/admin/discounts/edit-discount.php
Fixes #7757 
1. Changes hard coded `$` in discount type select to use the user-defined currency symbol
2. Changes `%` to no longer be a translatable string
> Update discount amount to use user-defined currency symbol

- assets/css/edd-admin.css
Fixes #7731 
1. Increased contrast for `.edd-chip` to `#444`, the core text color
2. Removed border from `.edd-chip` to gain more space for text
3. Increased text on `.edd-chip` to 11px to meet WAVE recommendations
> changed background and font on chip, issue #7731

- includes/admin/settings/register-settings.php
Fixes #7774
1. Adds `number` case to the `switch` in `edd_settings_sanitize`.
2. Accounts for the `number` type in the `edd_get_option` call.
3. Adds a new function called  `edd_get_registered_setting_details` allowing getting the details of a registered setting, when knowing it's section and tab.
> Add special handling for the 'number' setting type #7774

- includes/country-functions.php
Fixes #7797
1. Verified ISO code for Caltanissetta (CL)
2. Double checked that no other province has the ISO code CI
3. Removed incorrect listing for Caltanissetta
> removed incorrect listing for Caltanissetta

- includes/admin/upgrades/v3/class-data-migrator.php
Fixes #7789
1. Use the `$payment_meta` variable when computing key differences, as this has already been unserialized. `$meta['_edd_payment_meta']` is actually an array of unserialized data so this whole thing wasn't working.
> Use unserialized meta array when computing differences #7789

- includes/emails/tags.php
Fixes #7808
1. Checks if `$email_tag['label']` exists. If not, falls back to an empty string.
> Check if email tag label exists before using #7808

- includes/admin/payments/orders.php
Ensures full backwards compatibility with this hook from 2.9.
Fixes #7788
> Add payment meta to edd_payment_personal_details_list hook

- includes/orders/functions/actions.php
Fixes #7794
1. Parse date and hour from `data`
2. Check if hour and minutes are within given range
3. Convert WP timezone to UTC and format
> convert order date from local store time to utc

- includes/admin/downloads/metabox.php
- includes/ajax-functions.php
- includes/class-edd-html-elements.php
Fixes #7811 
1. Search and delete `edd_product_type` field from metadata for "default" products
2. Update meta query to match AJAX search
To Test:
- Create a new default download and check database
- Before database would have `_edd_product_type` of `"0"`
- Now there is no entry for default
> Remove `edd_product_type` for default download

- includes/admin/upgrades/v3/class-data-migrator.php
Fixes #7807
1. If API request token is empty, but the key is `public`, then set the token to be `public` as well.
2. If API request token is empty, but the key is not `public`, then set the token to an empty string. This prevents database errors when the token was actually `null`.
> Use 'public' for token if key is public, otherwise set to empty string instead of null #7807

- includes/class-edd-cli.php
> Set the object ID for order_notes when migrating via CLI

- includes/class-edd-cli.php
Fixes #7804
1. Moves all legacy data removal logic to its own command that runs last.
2. Changes `remove_legacy_notes` upgrade key to `remove_legacy_order_notes` to match what the CLI uses.
> Move all legacy data removals to separate command that runs last #7804

- includes/admin/payments/actions.php
Fixes #7464 
1. Removes Order total/tax/amount related changes since those cannot change.
2. Groups some variables/processes together for better readability.
3. Avoid generating PHP errors when creating a new customer.
> issue/7464 - Optimize "Save Order" Routine

- includes/admin/views/tmpl-order-refund.php
Fixes #7856 
1. Spell "digital" correctly
> fixed typo

- assets/css/edd-admin.css
Fixes #7838 
1. Added `display: flex` to `#edd-item-wrapper` so that sidebar and content are side by side, as they are in 2.9
> added display flex to #edd-item-wrapper

- includes/customer-functions.php
Fixes #7822
This can be tested with this code:
```php
add_action( 'wp_head', function() {
edd_add_customer_email_address( 
array(
'customer_id' => 142, // replace with a valid customer ID
'email'       => 'Aurelio.Kogut@affwp.example', // replace with an email belonging to that customer
) 
);
} );
```
In `release/3.0` the above code will add a duplicate email address to the database; switch to this branch and that should no longer happen.
> Do not add email address if it already exists for the customer

- includes/class-edd-cli.php
Fixes #7858
1. Only run `DELETE` queries if we've actually found IDs in the associated `SELECT` query.
> Only run delete queries if we have IDs to delete #7858

- includes/admin/upgrades/v3/class-data-migrator.php
Fixes #7855
1. Checks if `$payment_meta['user_info']` is set before using.
2. Adds fallback method for retrieving order `total` and `tax` values.
> Check if user_info is set before using & add fallback for retrieving order totals #7855

- includes/class-edd-cli.php
Fixes #7835
1. Use existing `$total` variable for the old log count. This directly counts the results from the SELECT query.
> Use existing variable for old log count #7835

- includes/orders/functions/actions.php
Fixes #7864 
1. Removed `date_completed` from `edd_add_manual_order()`, since that was keeping the `edd_complete_purchase` hook from sending a receipt
2. `edd_complete_purchase` already sets the date completed when called.
Tested by:
- Create a manual order, check email receipt and see if email is sent
Also, I confirmed that Order Details -> Notes is the same whether order is manual or from store.  Both types of orders show "Status changed from Pending to Complete" and "After payment actions processed."
I think this may fix EDD-Software-Licensing #[1629](https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/1629).  When I create an order with a license, I receive an email receipt and see a license key generated when I view the order.
> Removed `date_completed` from `edd_add_manual_order()`

- includes/admin/payments/orders.php
Fixes #7738 
1. Changed wording on label for send receipt checkbox
2. Move send receipt checkbox to top of Order
3. Removed `edd-admin-box-inside` class to remove unnecessary styling
> Move Send Purchase Receipt to Top of Order

- includes/admin/customers/class-customer-addresses-table.php
- includes/admin/customers/class-customer-email-addresses-table.php
- includes/admin/customers/customers.php
Fixes #7889
1. Adds missing time zone abbreviations to the customer Addresses tables
2. Adds missing time zone abbreviations to refunds on the customer details screen
> Add missing time zone abbreviations

- assets/css/edd-admin.css
Fixes #7866 
1. Changed `#edd-item-tab-wrapper` to use `*` instead of `div` to add more consistent padding
I'm still working on testing each instance of this `ids` use, but you all can probably find any issues before me anyway, since I haven't yet used `commissions` or `usage-tracking` yet.
>  edd-item-tab-wrapper rule changed to wildcard instead of div

- includes/admin/reporting/export/class-batch-export-earnings-report.php
Fixes #7876
1. Removes use of `edd_format_amount()`. That function is intended when a number is destined for _display_. It's not appropriate if any mathematical functions will be performed, which is the case here.
> Remove number formatting & cast to float #7876

- includes/admin/reporting/export/class-batch-export-payments.php
Fixes #7878
1. Gets customer name and address information from `$order->get_address()`
> Change how order addresses are included in order exports #7878

- includes/admin/upgrades/v3/class-data-migrator.php
1. When adding the customer address to the database, use the related order completion date as the address creation date
2. Change the way the email address is added to the database so the order completion date will be the email address creation date
If there is not an associated order, the creation date for the address record will be the migration date.
Fixes #7859
> When migrating, use order date as address creation date if possible

- includes/admin/reporting/export/class-batch-export-payments.php
Branched from #7879, which should be merged first.
Fixes #7880
Sets `type` to `sale` in order exports.
> Exclude refunds from order exports

- includes/scripts.php
Fixes #7847 
1. Called `edd_localize_script` inside of `edd_load_scripts`
2. Unhooked (removed hook?) for `edd_localize_script` from `wp_enqueue_scripts`
> Load Localization Scripts

- includes/admin/payments/add-order.php
- includes/admin/payments/orders.php
- includes/admin/payments/payments-history.php
- includes/admin/payments/view-order-details.php
- includes/admin/payments/view-refund.php
Fixes #7882 
1. Remove `edd-admin-orders` script from orders
I don't quite understand the technicalities of what this is doing, but I can confirm that the JavaScript error has gone away in the console.
> Remove edd-admin-orders script from orders

- includes/admin/upgrades/upgrade-functions.php
Fixes #7887
1. Updated escaping functions from `_e()` to `esc_html_e()` or `esc_attr_e()`
2. Updated `printf()` to `sprintf()` and escaped the whole output
3. Added translator comments when needed
> Translation-Ready Text for Migrations / Updates

- assets/css/edd-admin.css
- includes/admin/customers/customers.php
- includes/admin/payments/class-refund-items-table.php
Fixes #7922
1. Update the refund modal for smaller screens (iPads and lower). The WP Core primary column toggle doesn't work with the modal, so that has been removed, and the table CSS overridden to display necessary data on small screens. (It will look better in conjunction with PR #7899, but is not required.)
2. Fix the customer details physical address table to display only the primary column, although this feels awkward because just the street address doesn't feel helpful. Reworking to be more like the refund modal might make more sense.
3. Remove the primary column from the customer emails table (this was added in 3.0 but should not have been, as it hides the ability to remove emails on smaller screens).
> Update admin tables' responsive CSS

- includes/admin/payments/actions.php
- includes/admin/payments/class-payments-table.php
Fixes #7937
1. Changes the bulk actions list when viewing trashed orders.
2. Removes pagination if no orders match the current status.
> Update bulk actions for trashed orders

- includes/admin/reporting/export/class-batch-export.php
Fixes #7883
Replace `edd_die()` in the batch export class with `die`.
> Prevent extra content being added to exported CSV files

- assets/css/edd-admin-chosen.css
Resolves super narrow select issues when the first option has a short
label. Adds an override for the customer dropdown on the orders screens.
Fixes #7953
> Update chosen select widths

- includes/database/schemas/class-order-transactions.php
- includes/database/tables/class-order-transactions.php
Fixes #7963  
1. Increases the column length from `varchar(64)` to `varchar(256)` to account for updates to the Stripe object ID lengths.
> Increase column length for transaction_ids #7963

- includes/admin/reporting/reports.php
- includes/class-stats.php
Fixes #7919
1. Changes default region/country for the `Stats` class to be an empty string, not the shop region/country
2. Updates the country parsing logic to match the state
I don't know why this was affecting pie charts (download sales/earnings) and did not seem to be affecting other queries, but I tracked the reported issue down to the database query erroneously setting the state and country (none were selected).
To test, make sure your store has products with variations, and has a base state/region and country set. Create orders for the variations, hopefully with addresses not matching the shop state/region. In release/3.0, pie graphs should be broken; this PR should fix them.
Since the fix is in where the query is being parsed, this may have deeper ramifications I'm …
> Fix download pie chart report queries

- includes/reports/reports-functions.php
- tests/reports/tests-reports-functions.php
Fixes #7985 
1. Introduces the `edd_gross/net_order_statuses()` functions into the reporting functions.
2. Introduces two filters to allow filtering these statuses (with doc blocks)
3. Adds unit tests for the two functions.
> Add gross/net order status functions to aid in consistent reporting #7985

- assets/css/edd-admin.css
Fixes #7785 
1. Removed `overflow:hidden` from `edd-vertical-sections:not(.meta-box)
This class is also used in class-sections for vertically tabbed UI, but that still looks okay (to me) with this change.
> Export File Download Logs Dropdown, #7785

- includes/admin/upgrades/v3/class-data-migrator.php
Fixes #7602 
1. In the `Data_Migrator::tax_rates` method, check for any other country wide tax rates for the same country and deactivate them.
> Deactivate any country wide tax rates when importing a country wide tax rate that is for the same country #7602

- includes/admin/reporting/reports.php
- includes/class-stats.php
- package-lock.json
Fixes #7921 
1. I removed the `Average Age` tile and endpoint based on [this comment](https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7921#issuecomment-630328620)
2. Changed name of the `$accepted_functions` argument to match the name of the AVG function name
**Steps to reproduce the behavior**
Visit Downloads > Reports > Customers
- Average customer age should be gone
- Average number of orders should be correct
I don't have a ton of customer data to pull from, but I _think_ the average number of orders is correct.  Please check in your own stores.  If it is not correct, I can just pull out the tile until I / we can figure out where that number is going sideways.
> Report Tiles Incorrect #7921

- includes/admin/reporting/reports.php
- includes/reports/data/class-base-object.php
Fixes #6840
1. Changes the `object_id` of reports class to `public` so that it can be used in the hooks in the reports output. Everything was previously `private` so nothing could be used or filtered.
2. Adds a notice at the bottom of the tax reports if a default tax rate is detected.
> Adding notice to tax report if default tax rate is detected #6840

- includes/admin/upgrades/upgrade-functions.php
Fixes #7840 
1. Avoid marking migrations complete automatically when no migration needs to happen.
> 3.0 - Migration - Don't Automatically Mark Upgrades Complete via UI

- includes/admin/upgrades/v3/class-data-migrator.php
- includes/orders/functions/orders.php
- includes/payments/class-edd-payment.php
Fixes #7305
1. Removes the adjustment meta for `price_id` and `download_id` as they exist in the main columns for the adjustment itself.
> Removing unnecessary adjustment meta for the download_id and price_ids it is stored in the adjustments table columns already. #7305

- includes/discount-functions.php
Fixes #8002
To test:
Use `edd_get_discount_id_by_code()` (`var_dump` or `error_log` is enough) to retrieve a nonexistent discount code. Example:
```php
var_dump( edd_get_discount_id_by_code( 'adsrfd' ) );
```
In `release/3.0` this will throw a PHP notice, because a discount object is not returned. This adds a check for that situation.
> Return false for discount ID if discount object is not retrieved

- includes/customer-functions.php
Fixes #7998
1. Remove `type` from the `$empty_address` array
2. Add `type` to the `$address_to_check` array. Note that this is only for address comparison, and isn't part of the data added to the database (the `$data` variable in the code). Because the address table default type is `billing`, any address without a specific type registered will be added as a billing address.
To test: generate orders using WP-CLI. These orders do not have physical addresses, so no address rows should be created.
> Remove type from empty address array

- assets/css/edd-admin-tax-rates.css
- includes/admin/views/tmpl-tax-rates-table-add.php
- includes/admin/views/tmpl-tax-rates-table-bulk-actions.php
- includes/admin/views/tmpl-tax-rates-table-meta.php
- includes/admin/views/tmpl-tax-rates-table-row.php
Fixes #7957
1. Update table markup for consistency with Core tables.
2. Add `data-colname` attributes to rows for managing small screen output.
The input labels for the "add new" row are currently hidden with `screen-reader-text`, which I'm currently overriding on mobile screens so they can be visible for all users. This is a good use case for the reusable "show on mobile" CSS class requested in #7946.
> Update tax rates table markup and CSS for improved responsiveness

- includes/orders/functions/orders.php
- includes/reports/reports-functions.php
- tests/reports/tests-reports-functions.php
Fixes #8030
1. Moves get statuses functions out of a namespace
2. Fixes `completed` status to `complete`
3. Renames `edd_*_order_statuses` to `edd_get_*_order_statuses`
> Relocate and rename order statuses functions

- includes/ajax-functions.php
Fixes #8029 
1. Ensure taxes are enabled on individual Downloads before settings.
> 3.0 - Orders - Ensure Taxes Are Needed on Individual Order Items

- includes/payments/class-payments-query.php
Fixes #7845
1.`meta_key` can now be included without a corresponding `meta_value`.
2. Add support for "individual" date intervals: `array( 'year', 'month', 'week', 'day', 'hour', 'minute', 'second' ) `
3. Add support for `number`.
4. If `-1` is passed as `number` then `nopaging` is set to `true`.
5. If `nopaging` is set to `true` then this is meant to show all results. This was doing `unset( $arguments['number'] )` but the default in `edd_get_orders()` was then just being used instead, which was effectively setting the number to 30. So this has been adjusted to set the number to a really large integer instead.
> Remap missing EDD_Payments_Query arguments #7845

- includes/admin/payments/actions.php
- includes/admin/payments/class-payments-table.php
Fixes #7937 
1. Revert the changes to the list of bulk actions for trashed orders.
Looking over this, I wonder if the trashed orders bulk actions should be limited to simply "Restore" instead of the standard list of actions, since restoring the order will check the order meta and automatically change the restored order to its pending/cancelled/complete/etc. state, instead of allowing the bulk actions to potentially significantly change that.
(Also, some of the actions, such as "Resend Receipts", seem inappropriate for trashed orders.)
> Revert adding "delete permanently" to orders bulk actions

- includes/admin/upgrades/v3/class-data-migrator.php
- includes/gateways/functions.php
Fixes #8033
1. Since the Manual Purchases extension allows users to override the purchase total, use that if it is set.
2. Add a fallback label for orders with the `manual_purchases` gateway. This is currently set to "Manual Payment", which is what the extension uses, but could be changed.
**To Test:**
1. In a 2.9 storefront, use the Manual Purchases extension to create some orders. Make sure to override the purchase total on some.
2. Check out the `issue/8033` branch and migrate the payments. The order totals should reflect the manually set total, instead of the calculated total. (In `release/3.0`, the orders will use a calculated total, and will override the `_edd_payment_total` amount.
> Update migration for orders created with Manual Purchases extension

- includes/class-stats.php
Fixes #8006
The MySQL query should be ordered by `total` rather than `day`.
To test:
Generate a lot of orders for a specific day (ideally not a Saturday). I used:
```
wp edd payments create --number=50 --generate_users=1
```
which generated 50 orders for today (Thursday) in an otherwise fairly empty store. Visit Downloads > Reports and see what day is the busiest.
Alternatively, generate orders for a random set of dates, spanning maybe a year, and try changing the report date filter. Theoretically, the busiest day in a week could be different than the busiest day in a year.
> Fix busiest day tile

- includes/admin/discounts/class-discount-codes-table.php
Fixes #7596
Change the checkbox column on the discounts list table to allow used discounts to be selected for bulk actions.
To test:
1. Create some discounts.
2. Use a discount.
3. Select multiple discounts, including the used one, and Deactivate them. Even the used discount should be deactivated (note: you may need to refresh the page again as the new discount state does not show on the initial refresh for me).
4. Select multiple discounts, including the used one, and Delete them. The used discount will not be deleted, but the others will.
> Allow used discounts to be selected for bulk actions (#7596)

- assets/css/edd-admin.css
- includes/admin/adjustments/adjustment-functions.php
- includes/admin/admin-actions.php
- includes/admin/customers/customers.php
- includes/admin/payments/payments-history.php
- includes/admin/settings/display-settings.php
- includes/admin/tools.php
Fixes #8055
1. Change admin screens' tabbed navigation to use `nav` instead of `h2`
2. Adds `aria-label` to tabbed navigation
3. Removes unneeded CSS
> Update admin screens tabbed navigation

- includes/admin/reporting/class-export-customers.php
- includes/admin/reporting/class-export-payments.php
- includes/admin/upgrades/upgrade-functions.php
- includes/class-edd-customer.php
- includes/customer-functions.php
- includes/payments/actions.php
- includes/payments/class-payments-query.php
- includes/privacy-functions.php
- includes/user-functions.php
Fixes #7748
1. Replace `-1` with `9999999` when using new database queries
2. Add `_doing_it_wrong` if `-1` is used in `edd_get_customers` or `EDD_Payments`
What this doesn't currently cover is if someone were to bypass a function such as `edd_get_customers` in favor of calling the class directly using something like (if `$args['number'] => -1`):
```php
$customers = new EDD\Database\Queries\Customer();
return $customers->query( $args );
```
> Add "doing it wrong" when -1 is used in a query which no longer supports it (#7748)

- includes/template-functions.php
Fixes #
Since PHP 7.4 implode(): Passing glue string after the array is deprecated. So, I fixed with swapping the arguments.
> implode(): Passing glue string after array is deprecated.

- includes/api/class-edd-api-v2.php
Building out a data pipeline for extracting and combining data from our store, support inbox, email list, other plugins/EDD extensions, and others to build out reports. However, we need some additional data points in the sales endpoint.
1. To be able to ensure correct joins with data from other plugins, we need user ID.
2. To ensure we are only building reports on our live data, we need the mode.
3. To combine data with other EDD reports, it would be useful to have customer ID.
4. We will also be adding in other payments with different statuses through some of the filters, such as from the Recurring Payments extension, so we need to be able to see Complete vs Renewal statuses.
Here they are in the response after adding these fields on a local test site:
_Please do not …
> Add 4 new values to sales REST endpoint

- includes/template-functions.php
1. Adds additional`esc_attr` calls as well as resolving the issues from @zackkatz in the original PR #7661
> Fix W3 validation issues caused by dupe `id` atts

- includes/process-download.php
Fixes #8083 
1. Reordered args in call for `get/set_magic_quotes_runtime` to check PHP version first
Steps to Duplicate
- Use PHP 7.4.
- Install All Access Pass and configure that.
- Purchase a pass.
- Visit the page with the [downloads] shortcode and click the "Download" link to download a file.
I wasn't able to replicate this issue with just EDD.  I had to use the instructions above from #7818 to trigger the error.
> Issue/8083 Reorder args to check PHP first

- .travis.yml
- includes/cart/class-edd-cart.php
- includes/payments/functions.php
Fixes #8088
1. Forces pre/postfix items to be strings.
2. Make sure the the quantity of multi-price products is an array.
> Fix array key checks on cart quantities, and force string on strpos #8088

- includes/login-register.php
- includes/process-purchase.php
- tests/tests-login-register.php
Fixes #6647
1. Adds a 401 status header when a login is failed.
2. Remove validation done by EDD so that core actions can run
3. Modify `edd_log_user_in` to use `wp_signon` instead of just setting cookies and doing actions, so that core actions can run.
> Return 401 response on failed login and use wp_signon #6647

- assets/js/admin-scripts.js
- assets/js/edd-ajax.js
Fixes #8092
1. Adds `.length` attributes to the checks on the presense of the tax and fees inputs when removing a download from a payment in the admin.
> check that inputs have lengths before checking them on remove download #8092

- assets/css/edd-admin.css
Fixes #8065 
1. Updated border-radius, border color, padding to more closely match core 
2. Removed display: block from `#edd-filters span` so that fields stay together when resized
3. Added media query to add margin under edd-filters on small screens
These changes work well in Chrome, but the heights of the the inputs and selects vary in Firefox.  Firefox loads correctly for a second and then the selects change height.  Maybe a Chosen side effect?
> Issue/8065 Data range styles 

- includes/login-register.php
- includes/process-purchase.php
Fixes #8098
1. Boat-load of PHPCS fixes
2. In the `edd_register_and_login_new_user` function, we're now setting the WordPress user if logged in successfully.
> Fixing checkout registration form to set the current user #8098

- .travis.yml
Fixes #8032
1. Updates WordPress versions used for unit tests.
Include/exclude are not added/removed at this time.
> Update WP versions for unit tests

- includes/ajax-functions.php
- includes/tax-functions.php
Fixes #8107
1. Adds a `$fallback` parameter to the `edd_calculate_tax()` function. Set this to `false` when calling this function from inside `edd_admin_order_get_item_amounts()`.
2. Removes the `edd_get_tax_rate()` call (returned variable wasn't being used).
To test:
1. Make sure you have a `Business Country` set in Downloads > Settings > General.
2. Enable taxes and add a tax rate for your base country.
3. Manually create a new order via Downloads > Orders > Add New.
4. Add an item to your order, but do not set a customer/address, and ensure no tax is applied.
Also ensure that if you _do_ set a country that has a tax rate, tax is still applied.
> Add fallback parameter to edd_calculate_tax() function #8107

- includes/user-functions.php
This is supported functionality, but not reflected in the docBlocks.
1. Fix the docblocks for edd_has_user_purchased()
> Docblock: $downloads can be int edd_has_user_purchased()

- includes/admin/reporting/reports.php
Fixes #7972
1. Use `edd_get_price_name` to get price option names, if viewing a price ID.
> Update download labels for reports

- includes/admin/dashboard-widgets.php
- includes/admin/payments/class-payments-table.php
Fixes #7902
If a storefront has has orders and hasn't done the migration process:
1. Changes the dashboard sales summary widget to explain that the information will be available once the migration is complete.
2. Updates the "no items" message for the orders table.
To test:
Update an existing 2.9 site to 3.0 but do not run the migration. Check the dashboard widget and the main orders table. The new messages should display.
Create a new 3.0 site with no orders. The new messages should not display.
> Update dashboard widget, orders table, for sites which have not yet migrated (#7902)

- templates/shortcode-receipt.php
Fixes #8062
Update the check for discounts on a user's purchase.
To test: in `release/3.0`, create a front end purchase with no discounts applied. The "Discounts" row shows on the purchase confirmation screen, even though there are no discounts. Switch to this branch, reload, and the empty row will not display.
> Prevent empty discount rows showing in purchase confirmation (#8062)

- assets/css/edd-admin.css
- includes/reports/reports-functions.php
Fixes #7976 
1. Fix the reports chart markup to avoid duplicate `id`s.
Keeping this PR in draft as I'm checking with @LisaCee about updating the CSS to handle pie charts better and be mobile responsive.
> Fix report charts markup

- includes/payments/class-payments-query.php
- includes/payments/functions.php
- tests/orders/tests-payments.php
Fixes #7056
1. Support the `count` argument and return an integer when passed through.
2. Add unit test covering this scenario.
> Support returning an integer when counting payments via EDD_Payments_Query #7056

- assets/css/edd-admin.css
Fixes #8157 
1. Add media query to offset buttons only on larger screens
2. Tweak media query to match when table responds
I'm not crazy about this solution, but it works for now.  
In the future I'd love to see this screen styled differently for mobile, with tablet+ (782px) looking more like the larger screens.  IMO, the layout is too spread out, but that's a different issue having to do with when the table responds.
> Issue/8157 X Buttons Visible on All Screens

- includes/payments/class-payments-query.php
Fixes #8174
1.Check if `$meta['key']` exists before switch statement.
> Check if 'key' exists before using #8174

- assets/css/edd-admin.css
Fixes #7966 
1. Remove z-index for filters on reports screens
Go to `Downloads > Reports > Downloads` and use the dropdown to select a product
You can also see the changes on `Taxes` and `File Downloads` under `Reports`.
> issue/7966 Active Vertical Tab Border

- includes/payments/class-edd-payment.php
Fixes #8177
1. Use `city` property instead of `address`
> Use city property when filling address city #8177

- includes/admin/customers/customers.php
Fixes #7897
Updates the logic for the Terms and Privacy agreement dates to:
1. Show the agreement date if it exists.
2. Show the last payment date if there is a payment and store has a terms/privacy policy, regardless of when the policy was implemented.
3. Otherwise, show "No ... agreement found".
> Update customer privacy/terms agreement dates

- includes/cart/actions.php
Fixes #8181  
1. Check if `download_id` key exists before using.
2. Only add item to cart if `$download_id` isn't empty.
3. Don't save `edd_add_to_cart()` output to a variable, as the variable is never used.
I opted to continue the flow of the function instead of bailing immediately, because that way you'll still get redirected to checkout, even though your cart is empty. I thought this might make it easier to debug a broken URL.
To test:
1. Manually visit a malformed add to cart URL like this: `https://yoursite.com/checkout/?edd_action=add_to_cart` . Ensure you are redirected to checkout with no items in your cart. Ensure no PHP notices.
2. Manually visit a correctly formed add to cart URL like this: `https://yoursite.com/checkout/?edd_action=add_to_cart&download_id=123` …
> Check if download_id exists before using #8181

- tests/orders/tests-trash.php
- tests/phpunit/class-edd-unittestcase.php
- tests/tests-api.php
- tests/tests-cart.php
- tests/tests-formatting.php
- tests/tests-scripts.php
- tests/tests-tax.php
The goal is to get the unit tests _mostly_ working with PHPUnit 5.x and 7.0.
Related: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7435
This PR doesn't entirely fix that issue; you still have to manually remove the speed trap listener. But the goal is to make it so if you _do_ remove that speed trap, the unit tests pass.
---
Update: With these changes the tests are now passing for me locally. I've added some notes throughout the code to explain why I made each change.
@robincornett Please run these tests on your end and let me know if there are any failures.
> Get unit tests usable with PHPUnit 7.0

- includes/admin/tools.php
- includes/compat/class-tax.php
Fixes #8133
1. Do not attempt to convert empty tax rates.
2. Fixes the redirect link after settings are imported.
> Fix tax rate conversion when importing settings

- includes/EDD_SL_Plugin_Updater.php
- includes/class-edd-license-handler.php
Fixes #7707
1. Updates the EDD_SL_Plugin_Updater class to version 1.8.
2. Add support for auto-updates (added in WordPress 5.5) by changing the `auto_updater` method hook so it can run during cron events.
> Update EDD_SL_Plugin_Updater to 1.8

- includes/admin/class-edd-notices.php
- includes/admin/discounts/discount-actions.php
Fixes #8183 
1. Validate discount code is numeric prior to saving.
To test:
1. Attempt to create a new discount code with an invalid amount (such as `10abcd`). Ensure you get an error message.
2. Attempt to edit an existing discount code with an invalid amount. Ensure you get an error message.
3. Ensure you can still successfully add/update discounts with valid amounts.
> Validate discount amount is numeric before saving #8183

- includes/admin/class-edd-notices.php
- includes/admin/discounts/discount-actions.php
- includes/class-edd-discount.php
Fixes #8183
1. Convert values to floats before doing calculations.
**Note:** For ease of testing, I'm doing this PR in two parts. This first part only fixes the calculations. This is to ensure you can still save a non-numeric discount for testing purposes. After this has been tested, I'll follow up with sanitizing amounts before saving.
1. Create a new discount code. Type = percentage; amount = 50b. (Or any random letter thrown in.) Save.
2. After saving, it will appear in the UI as just 50, but in the database it's actually saved as 50b.
3. Add an item to your cart, proceed to checkout, and apply this discount code.
4. Ensure you don't get any PHP notices.
5. Ensure discount amount is correctly displayed on checkout.
> Ensure values are floats before doing calculations #8183

- includes/admin/upgrades/v3/class-data-migrator.php
Fixes #8028
1. Only store the address country if it exists in `edd_get_country_list()`
To test:
1. Start on EDD 2.9.
2. Manually update the address on an order to be something invalid. Can be done by manually running this PHP:
```php
$order_id = 123; // Order/payment ID number
$meta = get_post_meta( $order_id, '_edd_payment_meta', true);
$meta['user_info']['address']['country'] = '*'; // Or set to something totally random
update_post_meta( $order_id, '_edd_payment_meta', $meta );
```
3. Upgrade to 3.0.
4. After upgrading, check the `wp_edd_order_addresses` value for that order ID. The `country` should be blank.
> Validate order country against global list during migration #8028

- assets/css/edd-admin.css
- includes/admin/payments/class-payments-table.php
- includes/reports/reports-functions.php
Fixes #7965
1. Remove unneeded CSS for the filter bar.
2. Update filter bar button markup to include `button` class (`button-secondary` CSS is similar in many cases, but not mobile).
> Update filter bar markup, CSS

- tests/bootstrap.php
Fixes #8210 
1. Prior to running tests, uninstall any custom tables, then reinstall.
> Reinstall custom tables prior to running unit tests #8210

- includes/login-register.php
> Use wp_safe_redirect with EDD's login

- includes/checkout/template.php
Fixes #8217 
Add alt tag containing payment type to the payment icon.
> add alt to credit card icons

- includes/cart/actions.php
Fixes #8219
1. Check if `$data['edd-cart-downloads']` exists and is an array before treating it like one.
I'm not sure how the original issue happened, but I think the main thing here is to ensure the process still works.
To test:
1. Enable quantities (Settings > Misc > Cart Item Quantities).
2. Add an item to your cart.
3. Once at checkout, **disable JavaScript**. JS needs to be disabled for the `Update Cart` button to appear.
4. Increase the quantity of the item in your cart and click `Update Cart`.
5. When the page refreshes, ensure you have the updated quantity.
> Check if edd-cart-downloads exists & is an array before using #8219

- includes/gateways/paypal-standard.php
Fixes #6837
1. Prevents negative fees from being applied twice.
---
This is going to need a bunch of testing because it touches payment amounts.
Testing steps for the original issue are outlined here: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6837#issuecomment-713580310
We should also test with:
1. Positive fees.
2. Actual discount codes (not negative fees, but proper coupons).
3. Anything else we can think of?
> Prevent negative fees from getting applied twice #6837

- includes/class-edd-html-elements.php
Fixes #8224
1. Updates the user dropdown function to accept an array of selected users when making sure that a selected user will appear in the initial batch.
To test:
1. Check out the [1.5-master-merge branch](https://github.com/easydigitaldownloads/edd-discounts-pro/tree/release/1.5-master-merge) for Discounts Pro (the issue is not present in `master`).
2. With `release/2.10`, create a discount for a specific user and see the error indicated in the related issue.
3. Switch to this branch and the error should be resolved.
Notes: I referred to the `product_dropdown` method to set up the logic for this, as it also can be set to single/multiple.
> Fix user fallback if user is not in initial batch for user_dropdown

- includes/login-register.php
- includes/payments/actions.php
- templates/shortcode-login.php
Fixes #8100
1. Because the EDD login process isn't always part of the checkout process, the current referer is set as the redirect instead of hard coding in the checkout page.
Base set to 2.10.
> Update redirect when directing to lost password URL

- templates/shortcode-profile-editor.php
Fixes #8232 
Proposed changes: update the `label` elements to associate them with the password `input` elements on the profile editor.
> Fix labels on password input fields (profile editor)

- includes/api/class-edd-api-v2.php
Fixes #8240
1.Use `$args['customer']` instead of an undefined `$customer` variable in the error message.
> Use original customer argument in error message #8240

- includes/admin/downloads/metabox.php
Fixes #8214
To test:
1. Activate this branch and an extension which adds options to the variable prices. Software Licensing may be easiest.
2. Make sure debugging is enabled.
3. Edit a download. PHP Notices should be logged.
4. Switch to the [SL branch 1182](https://github.com/easydigitaldownloads/EDD-Software-Licensing/pull/1182). Notices should be gone!
> Add deprecation notices for variable pricing hooks

- includes/discount-functions.php
Fixes #8236
Proposed Changes: initially I was just going to fix the output to show the proper discount rate, but after reading through the code with changes from #7993, it seemed important to figure out how to show the calculated discount amount, as that appeared to be the goal of the updated code (2.9.x shows just the discount rate, not the calculated/applied amount):
1. Show the calculated discount amount after the discount code. This has been updated to honor the storefront currency placement settings.
2. Additionally, for percentage discounts, the percentage is also displayed.
3. Prefixed the row with "Discount(s):" to be consistent with Subtotal, Tax, and Total rows.
4. Added link text to the `edd_discount_remove` link (hidden with `screen-reader-text`) for accessibility.
To test:
- …
> Update how discounts are displayed in the cart

- includes/admin/import/class-batch-import-payments.php
- includes/orders/functions/orders.php
- includes/payments/class-edd-payment.php
Fixes #8145
1. Make the early return logic consistent when `edd_get_discount_by` is used.
2. In `EDD_Payment`, if a discount object does not exist, but a discount does, add it as a fee instead (discounts are expected to exist in the `edd_adjusments` table).
<del>@ashleyfae although the checks for the discounts and taxes are happening in the `EDD_Payment` class, I feel uncomfortable automatically adding the fee/tax rate (haven't started on that one yet) there because of potential ripple effects. However, I'm not sure if I can duplicate the checks in the import class, or if that would be more appropriate at all. So setting this up as a draft to ask for feedback (the non-object error is resolved, at least, but imported orders don't feel correct).</del> Currently discounts …
> Prevent errors when importing payments with non-existing discounts

- includes/database/engine/class-query.php
Fixes #8247
1. Revert visibility changes on methods made as part of #8132.
2. I have reviewed everything in the class which is still marked `private` (under the `Private Parsers` heading and then another section further down); everything which is not used outside of the class is still `private`.
3. One exception to 2 is `set_query_var_defaults` which is also used by the Orders class as a protected method.
> Revert visibility changes on BerlinDB query methods

- includes/cart/class-edd-cart.php
- tests/tests-api.php
Fixes #8246 
1. Add support for options inside `item_number` for variable pricing.
For testing, consult steps in the original issue: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/8246
We should both 1) reproduce those steps; and 2) test with a non-variable-priced product to ensure the discount amount is still valid for that.
> Add support for variable pricing when getting item discount amount post-checkout #8246

- includes/admin/payments/class-payments-table.php
Fixes #8248
1. Remove the variable which adds the `open` class on load if an advanced filter is applied.
To test:
1. On Downloads > Orders, click the "More" button to open the advanced filters. Apply one and click the "Filter" button.
2. On reload, the advanced filters should be hidden.
> Do not show additional filters on load

- includes/admin/payments/class-payments-table.php
- includes/database/queries/class-order.php
Fixes #8260
1. Change select values to `eq`, `gt`, and `lt` instead of angle brackets.
2. Use `compare_query` argument instead of `compare` for comparison array. I suspect this was a change in BerlinDB at some point. :shrug: 
3. Exit early out of `query_by_country()` method if there is no country query.
To test:
Try filtering by all "Total is" options to ensure each of them work.
Try combining a "Total is" option with a country filter and ensure it still works.
> Fix order comparison query #8260

- includes/admin/payments/class-payments-table.php
- includes/misc-functions.php
Fixes #8262
1. Filter out empty query arguments. The issue was that the count query had unnecessary clauses in it, checking for empty values (example: `where mode = ''`)
2. Change parameter type in docblock.
> Filter out empty query arguments #8262

- includes/admin/class-edd-notices.php
- includes/orders/functions/actions.php
Fixes #8191
1. Move all order related notices out of the "Shop reports errors" section and into the order-related notices. I think they were just in the wrong spot.
2. Create a new notice for `order_added` and include this notice in the page redirect after making an order.
3. Correct return type in PHPDocs for `edd_add_manual_order()`.
To test:
Manually create a new order and ensure you get a success message after doing so.
> Show success message after manually creating order #8191

- includes/admin/payments/actions.php
- includes/admin/payments/class-payments-table.php
Fixes #7262 
1. Remove refund from Orders > bulk actions 
2. Remove refund from actions switch statement
> #7262 Remove Bulk Refund Action

- includes/database/schemas/class-adjustments.php
- includes/database/schemas/class-customer-addresses.php
- includes/database/schemas/class-customer-email-addresses.php
- includes/database/schemas/class-customers.php
- includes/database/schemas/class-logs-api-requests.php
- includes/database/schemas/class-logs-file-downloads.php
- includes/database/schemas/class-order-addresses.php
- includes/database/schemas/class-order-adjustments.php
- includes/database/schemas/class-order-transactions.php
Fixes #8266 
1. Remove all `'searchable' => false` parameters for consistency. The default is false, so omitting it completely is essentially already `false`. I did this to improve scanability so you can more easily search for `searchable` to see all the searchable fields.
2. In general, `searchable` has been removed for all non-text fields. This includes numeric columns (like `object_id` or `parent` etc. and amount fields like order totals) and date / datetime columns.
To clarify point 2, by removing searchable we can still query on those columns. We can still find all adjustments with `object_id` `4`; it just has to be done deliberately in the query arguments:
```php
array(
'object_id' => 4
)
```
We can also still search orders for all orders with a total greater than …
> Limit searchable to text based columns #8266

- includes/admin/admin-pages.php
- includes/admin/settings/display-settings.php
Fixes #8209
1. Adds a check for `admin.php` and the EDD settings page to the `edd_is_admin_page()` function.
To test:
Navigate to `admin.php?page=edd-settings&tab=general` in your site. With this branch, the navigation tabs should be styled correctly and the script (Chosen) needed to change the country/region selector will load--that's the most visible thing to check.
> Ensure that a mislinked EDD settings page is an EDD admin screen

- includes/admin/upgrades/v3/class-data-migrator.php
Fixes #8304 
When looping through `$cart_details` during a migration, use `float` when a value is set, not on the `isset` check for the value.
> Move float performed on cart values during migration

- includes/admin/payments/actions.php
- includes/orders/functions/addresses.php
- includes/payments/class-edd-payment.php
- includes/privacy-functions.php
Fixes #8309
1. Sets up the payment/order address after the `user_info` has been set up (since it relies on `user_info`)
2. Update usage of `edd_add_order_address` and `edd_update_order_address` to use the correct `name` parameter instead of `first_name` and `last_name`, which are incorrect.
3. Update related doc blocks.
> Fix payment address setup

- includes/class-edd-logging.php
Fixes #8299
1. Use the `edd_add_log_meta` (and related file download/api request functions) to add metadata to the log.
2. Use `edd_update_log_meta` (and related file download/api request functions) to update metadata in `update_log`.
> Use helper functions to add log metadata

- includes/admin/reporting/class-base-logs-list-table.php
- includes/admin/tools/logs.php
Fixes #8275
1. Filter out empty arguments. 
2. Update PHP docs to reference specific class name.
> Filter out empty arguments #8275

- includes/admin/tools/logs.php
Fixes #8329
Just changes the `$context` being passed to the function so that it matches the action hook used.
> Fix the old logs filter bar

- includes/payments/class-edd-payment.php
Fixes #8334
1. Remove fallback to `date_created`
Follow testing steps in the issue. Ensure that if there is no order `date_completed`, an empty string is returned. If there is a `date_completed`, that date should be returned.
You can also test that EDD Commissions now get recorded. See https://github.com/easydigitaldownloads/EDD-Commissions/issues/394
> Remove date_created fallback for payment completion date #8334

- includes/admin/reporting/class-api-requests-logs-list-table.php
- includes/admin/reporting/class-base-logs-list-table.php
- includes/admin/reporting/class-file-downloads-logs-list-table.php
Fixes #8272 
1. Remove entire `get_meta_query()` method, as it's no longer needed.
2. Fix email search to get customer by the email address.
3. When a customer is found via search, also set `user_id` parameter. Some log tables use `customer_id` and others use `user_id` so this ensures compatibility with both.
To test:
Follow original testing steps here: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/8272
You will need at least one API request. Then try a variety of searches, including:
- Use date parameters.
- Enter an IP address in search.
- Enter an email in search. (This should match the account that performed the API request.)
- Enter a user ID number in search. (This should match the account that performed the API request.)
- Also try some …
> Remove unnecessary meta query & fix email search #8272

- includes/admin/upgrades/v3/class-data-migrator.php
- includes/compat/class-log.php
Fixes #8317
1. Updates the data migrator code to update the log metadata for all core log types (previously just main logs; file download and API request logs were excluded).
2. Does not migrate metadata which has been migrated to a column in the main/related log table.
Note: a meta key which did exist in 2.x, apparently, is `_edd_log_user_id`. However, looking at all of the rows that include it (on the site I'm migrating), I'm not convinced we need to keep it. The empty value appears to be saved as `-`, so I see a lot of that; additionally, the rows with values are all single digit numbers, and that does not make sense for a very large site. Actually, the newest rows (migration still going) are all the `-` value, so maybe that's a meta value which is no longer valid at …
> Migrate log metadata

- includes/class-edd-logging.php
Fixes #8333 
1. Add check if `log_type` is `file_download` (3.0)
2. Change `post_parent` to `product_id` if 3.0
> #8333 Backwards Compatibility Logs post_parent

- includes/admin/upgrades/v3/class-data-migrator.php
Fixes #8342
1. Removes the `$data->ID` parameter from the hook because it's identical to `$order_id`.
2. Adds the original `$meta` to the hook as the second parameter. Wondering if this should really be `$payment_meta` instead as that's been unserialized and is probably what's really needed (or hard to get) for an extension.
> Update the edd_30_migrate_order parameters

- package-lock.json
- package.json
1. Removes `npm` as a dependency and moves it to `engines`. I just copied the version number that's currently in release/3.0 :shrug:
> Move npm requirement to 'engines'

- includes/admin/class-sections.php
Fixes #8337 
1. Remove the `is_string()` check prior to checking if the callback is callable.
I opted to leave the reports-specific stuff in for now, because although only reports is using it, it seems reasonable that other implementations could use it too.
> Remove is_string() check #8337

- includes/admin/upgrades/v3/class-data-migrator.php
- includes/payments/class-edd-payment.php
Fixes #8350
1. During order migration, only removes core `user_info` from the payment meta--if anything is left, it's saved.
2. Adds a backwards compatibility check to the `setup_user_info` method in `EDD_Payment` to get the extra `user_info`.
> Keep extra user_info during order migration

- includes/admin/discounts/add-discount.php
- includes/admin/discounts/edit-discount.php
Fixes #8322
1. Do not allow variations in the product dropdowns for discounts. Variations were added in #7786, but have unintended consequences.
> Remove variations from discount product options

- includes/admin/payments/class-payments-table.php
Fixes #8362
1. Updates `user` parameter to query for `user_id`.
> Fix user_id parameter for filtering orders

- includes/formatting.php
Fixes #8365
1. Check if price is numeric before doing a `<` comparison.
> Check if price is numeric before doing comparison #8365

- includes/class-edd-db-customers.php
Fixes #8370
The only main change is this extra snippet at the very top:
```php
$user = get_userdata( $user_id );
// Bail if the email address didn't actually change just now.
if ( empty( $user ) || $user->user_email === $old_user_data->user_email ) {
return;
}
```
We exit ASAP if the user's email address didn't just change. The following code should only execute if the user's email changed to something else during the current update.
Other changes are minimal while in the area:
1. Update PhpDocs to include parameters.
2. Reformat code to exit early instead of a bunch of nested if statements.
3. Change `return false;` to `return;`
4. Add comments to action hook.
5. Remove required parameter before optional (PHP 8 error)
This fixed the memory issue for me. We should verify …
> Exit early if user's email address didn't change #8370

- includes/class-edd-discount.php
Fixes #8372
1. Re-adds two missing meta methods: `get_meta()` and `update_meta()`. 
2. Replaces uses of `$this->delete_meta()` with `edd_delete_adjustment_meta()` (It appears the `delete_meta()` method does not exist in 2.x so I opted not to add it.)
3. Replaces uses of `$this->add_meta()` with `edd_add_adjustment_meta()`
> Re-add discount meta helper functions & update calls to delete/add meta #8372

- includes/class-edd-html-elements.php
- includes/reports/data/class-endpoint.php
- includes/reports/data/class-table-endpoint.php
- includes/reports/data/downloads/class-earnings-by-taxonomy-list-table.php
- includes/reports/reports-functions.php
Fixes #8358
1. Don't use an associative array.
Visit all reports and ensure everything displays correctly.
@robincornett please test in PHP 8
@LisaCee Please test in non-PHP 8
> Don't use associative array in call_user_func_array() #8358

- includes/payments/class-edd-payment.php
Fixes #8373
To test:
Use this branch with an extension which uses the `edd_update_payment_meta` and `edd_get_payment_meta` functions, especially with their own meta keys with the `_edd_payment_` prefix. Cross-Sell/Upsell is one; Simple Shipping is another ([use this branch to get a 3.0 compatible version](https://github.com/easydigitaldownloads/edd-simple-shipping/tree/issue/89-meta)). Meta keys should continue to be saved with the prefix and should be able to be updated and retrieved with either the payment or order meta functions.
ACK! Just realized this wasn't mine to do--I'm so sorry I messed that up. Checked with Lisa and am leaving as is.
> Remove backwards compat _edd_payment_ removal

- includes/admin/reporting/export/class-batch-export.php
Fixes #8369
To test: switch to PHP8 and use an export tool which uses the EDD_Batch_Export class. Without the fix, you should get the warning noted in the issue; with it, you should not.
> Check if the export file exists before using unlink

- includes/admin/upgrades/v3/class-data-migrator.php
- includes/class-edd-logging.php
Fixes #8383 
1. Add support for converting `$log_meta['user']` to `user_id`. If not provided, it falls back to `get_current_user_id()`
2. Set `user_id` to during 3.0 migration.
2. Check if all array keys exist before using.
3. Whenever a piece of `$log_meta` is used in the main `$data` array, ensure it gets unset from `$log_meta`. This ensures that we don't add duplicate meta data unnecessarily. (The data was being added to the main table _and_ the meta table.)
4. For file downloads: get the `order_id` arg from `$log_meta['payment_id']` instead of `$log_meta['order_id']`
5. Add PHPDocs for action hooks.
6. Strip `_edd_log_` meta key prefix during log migration.
> Fix backwards compatibility for log inserts #8383

- includes/database/tables/class-adjustment-meta.php
- includes/database/tables/class-adjustments.php
- includes/database/tables/class-customer-addresses.php
- includes/database/tables/class-customer-email-addresses.php
- includes/database/tables/class-customers.php
- includes/database/tables/class-logs-api-requests.php
- includes/database/tables/class-logs-file-downloads.php
- includes/database/tables/class-logs.php
- includes/database/tables/class-notes.php
- includes/database/tables/class-order-addresses.php
- includes/database/tables/class-order-adjustments.php
- includes/database/tables/class-order-items.php
- includes/database/tables/class-order-transactions.php
- includes/database/tables/class-orders.php
Fixes #8341
1. Removes all database upgrades from 2018.
We should test:
1. An upgrade from 2.9.
2. A fresh install of EDD 3.0.
And in both cases ensure there are no database errors.
> Remove database upgrades from 2018 #8341

- includes/admin/adjustments/adjustment-functions.php
Fixes #8286
1. Change the main header to `Discounts` to match the admin menu item and Add/Edit pages ("Add New Discount")
> Change heading to 'Discounts' #8286

- includes/database/engine/class-table.php
- includes/database/schemas/class-logs-file-downloads.php
- includes/database/schemas/class-orders.php
- includes/database/tables/class-adjustments.php
- includes/database/tables/class-orders.php
Fixes #8176
1. Patches the `index_exists()` method in BerlinDB. The query wasn't working before.
2. **Orders Table:**
- Removes `searchable` from some columns that do not need to be searched (id, parent, status, etc.). They can still be queried individually, but they do not need `LIKE` queries. This improves the performance of searching orders.
- Drops old `KEY status (status(20))`
- Creates new index `KEY status_type (status, type)` . Adding `type` improves the performance of the admin orders table.
3. **Adjustments Table:**
- Drops the old `code_status_type_scope_amount` index. I couldn't find it being used anywhere. This came closest: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/settings/register-settings.php#L1479-L148 …
> Add new indexes to custom tables #8176

- includes/admin/customers/customers.php
Fixes #8394
1. Add a clearing `div` at the end of the customer info section.
> Clear the customer info section

- includes/admin/admin-deprecated-functions.php
- includes/admin/payments/actions.php
Fixes #8374 
1. Redirect to trashed orders after permanently deleting order
2. Escaping for function
3. Update doc block typo and param
I'm not quite sure the difference between this function and the one right above it, `edd_trigger_purchase_delete`.  I would love to clarify in the descriptions, once it is explained.
> #8374 Redirect After Permanently Deleting

- includes/orders/classes/class-order.php
- includes/orders/functions/actions.php
- includes/payments/actions.php
- includes/payments/class-edd-payment.php
Fixes #8412 
1. `Order::get_fees()` no longer sets the array key. It's not actually needed in new 3.0 code, so I've removed this and we'll only implement this in 2.9 backwards compat layers (`EDD_Payment`).
2. Removes all usage of `download_id` and `price_id` order adjustment meta. These are only set when the adjustment type is `order_item`, and in that case they can be retrieved from the order item itself.
3. `EDD_Payment::setup_fees()` no longer loops over order items. This is where some duplication was coming from, because `Order::get_fees()` already includes the order item fees in the array.
4. `EDD_Payment::setup_fees()` - if we end up modifying the `type_key`, then actually update it in the DB to reflect that. Basically, in my reproduction steps, my `type_key` was …
> Fix order fee backwards compatibility to avoid duplication #8412

- includes/admin/upgrades/upgrades.php
Fixes #8425 
1. Use `esc_url_raw()` instead of `esc_url()`. The main difference is that `esc_url_raw()` does not encode ampersands or single quotes.
> Use esc_url_raw() to prevent ampersands from being converted #8425

- includes/payments/class-payments-query.php
Fixes #8430
1. Update `remap_args` to inherit the `meta_query` if set.
2. Update `remap_args` and returned array to honor the `fields` parameter if set.
To test:
Either follow the steps in the related issue, or test with [this Simple Shipping PR](https://github.com/easydigitaldownloads/edd-simple-shipping/pull/101).
> Update edd_get_payments backwards compatibilty

- includes/gateways/amazon-payments.php
Fixes #8440
Adds the `edd_is_gateway_active` check back after registering the gateway so that the rest of the code doesn't run if Amazon Payments isn't active.
> Return after registration if Amazon gateway is not active

- includes/install.php
Fixes #8423
1. If the block editor exists, updates the content for pages added on activation to use blocks.
To test:
Do a fresh install of EDD with this branch on a site running WP 5.0 or higher. The pages automatically created by EDD should use paragraph and shortcode blocks rather than the classic editor block.
> Update block editor content for pages added on initial activation

- easy-digital-downloads.php
- includes/cart/template.php
- includes/class-edd-cache-helper.php
- includes/class-edd-register-meta.php
- includes/misc-functions.php
- readme.txt
- templates/shortcode-content-image.php
- tests/helpers/shims.php
- tests/tests-register-meta.php
Fixes #8443
1. Update minimum required WordPress version in readme.txt.
2. Update minimum version in internal requirements check.
3. Remove check for `get_user_locale` (WP 4.7)
4. Remove check for `wp_doing_cron` (WP 4.8)
5. Remove check for `wp_doing_ajax` (WP 4.8)
6. Remove check for `wp_doing_autosave` (doesn't exist)
7. Remove WP version checks for `$wp_filter` callbacks (WP 4.7)
8. Remove `sanitize_post_meta` compatibility filters and related tests (WP 4.6)
9. Remove `wp_suspend_cache_addition` check (WP 3.3)
10. Remove `is_post_type_viewable` shim (WP 4.4)
11. Remove `has_post_thumbnail` check (WP 2.9)
There is a check for `wp_add_privacy_policy_content` which I've left in as it was added in WP 4.9.6, not 4.9.0. It looks like `is_countable` and `is_iterable` are …
> Update minimum WordPress version to 4.9

- easy-digital-downloads.php
- package.json
- readme.txt
This PR is a version bump, but is intended to be run along side the build/testing of pulling from Stripe 2.8.4
Please run the `npm run build` in order to test the following:
1. When Running EDD Core only, no Stripe payment gateway license field shows.
2. Possible conflict with the number of plugins needing updates could be showing when unnecessary.
> Version bump for 2.10.1

- tests/tests-query-filters.php
Fixes #8473
1. Use absolute file paths instead of relative.
@robincornett I understand this was breaking tests for you locally. Can you give me more information about that?
1. How were you running the tests? Were you using the new Docker method or just running `phpunit` ?
2. Which version of WordPress?
3. What was the exact error?
> Use absolute file paths instead of relative #8473

- includes/admin/payments/actions.php
Fixes #8486
1. Remove trailing comma from function arguments.
> Remove trailing comma from function arguments #8486

- includes/deprecated-functions.php
- includes/payments/actions.php
- tests/tests-filters.php
Fixes #8480 
1. Deprecate `edd_record_status_change()` and replace with `edd_record_order_status_change()` 
2. Hook new function into `edd_transition_order_status`
3. Update test with new function name
> #8480 3.0 Manual order status change notes

- includes/admin/class-edd-notices.php
- includes/emails/actions.php
- includes/emails/functions.php
- includes/emails/tags.php
Fixes #8415
1. If there isn't an order retrieved for the email tag, return an empty string.
2. Apply the `edd_email_preview_template_tags` to the test purchase receipt.
3. Add a success message when a test purchase receipt has been sent.
> Fix purchase receipt email preview/test

- tests/tests-query-filters.php
Fixes #8473
Same changes as https://github.com/easydigitaldownloads/easy-digital-downloads/pull/8475 but against `master` branch.
> Fix attachment unit tests in WordPress 5.7 #8473

- includes/gateways/functions.php
Resolves #8499 
1. Moves the return value out of a direct return and into a variable for registered gateways.
2. Searches for the `stripe` gateway key and then moves it to the top of the list instead of in the order of registration.
> Move Stripe to the frist payment gateway in the Available Gateway Settings when it is found #8499

- includes/reports/reports-functions.php
- tests/reports/tests-reports-functions.php
Fixes #8470 
1. Add `edd_report_filters` filter so add-ons can add their own filters.
2. Add 'Product Categories' filter.
Use these add-ons to test:
1. `edd_report_filters` - https://github.com/easydigitaldownloads/edd-campaign-tracker/pull/9
2. Product Categories - https://github.com/easydigitaldownloads/edd-cross-sell-upsell/pull/39
> Add 'Product Categories' report filter & add filter on all filters #8470

- includes/discount-functions.php
Fixes #8511
When calculating the item discount, if the `$item['options']` are not set but the `$item['item_number']['options']` is, map that to the `options`.
> Account for variable pricing from cart details for discounts

- includes/admin/settings/register-settings.php
Fixes #8506 
1. Adds link to Termageddon on Privacy Policy Settings
2. Adds link to Termageddon on Terms of Agreement Settings
> Add ilnks to Termageddon on privacy policy and terms of agreement settings #8506

- includes/admin/settings/register-settings.php
Fixes #8513
1. Renames the `Order Blocking` setting to `Banned Emails`. Also adds back in the description that's currently in 2.10.
2. Hooks the `edd_sanitize_banned_emails()` function into `edd_settings_sanitize` so that it actually runs. I also updated the since version to 3.0, because from what I can tell it is completely new in 3.0.
> Fix banned email sanitization #8513

- includes/misc-functions.php
Fixes #8491
1. Fetches a status from `edd_get_payment_status_label()` as a first try. This ensures that _payment_ statuses always have a chance to use the `edd_payment_statuses` filter to use a custom status name.
To test:
Follow steps listed in issue, but this time, the status _display name_ should be shown instead of the key.
> Use edd_get_payment_status_label() for payment statuses where possible #8491

- includes/misc-functions.php
- includes/payments/functions.php
Fixes #8526
1. Make sure that `$found_key` has a value before using it in `edd_get_payment_status`.
2. Update the default/fallback label strings in `edd_get_payment_status_label` and `edd_get_status_label` to remove underscores before capitalizing the words.
> Fix status label fallbacks

- bin/update-stripe.sh
- includes/gateways/.stripe-hash
Fixes #8528
1. When updating Stripe, write the hash of the HEAD of the Stripe repo at the time of bundling.
> Add stripe revision during build #8528

- includes/orders/classes/class-order.php
- includes/orders/functions/refunds.php
Fixes #8546
Branched from #8075 because of variable name changes, code refactoring
1. Changes tax rate logic to use an absolute value instead of just checking if it's greater than 0 (refunds have negative tax value).
2. If the original order has a `tax_rate` meta value, copy it to the related refund.
> Ensure that tax_rate order meta is copied to refunds

- includes/payments/functions.php
Fixes #8551
1. Define `$status` irrespective of the `$order`, then update with the order status if it exists.
> Ensure that status is always set in edd_is_payment_complete

- includes/admin/upgrades/v3/class-data-migrator.php
- includes/class-utilities.php
- includes/utils/class-date.php
Fixes #8496
1. Add `@throws` to docblocks to clarify methods can throw exceptions.
2. Add exception handling in date parsing and set fallback date to an empty string (BerlinDB should then take over and set it to be the current time).
To test:
1. Start on EDD `master` branch and have a customer.
2. Add a note to the customer.
3. Then manually edit the customer's record in the DB (`notes` column) to set the date to something that won't parse. For example:
`I am an invalid date! - This is my note`
Make sure you have at least one ` - ` (space, hyphen, space) in there because the migration code explodes on that.
4. Run the migration.
5. Ensure no errors. Ensure the note gets migrated with a `date_created` of today/now.
You can also change your site language prior to adding …
> Add exception handling to date parsing #8496

- includes/payments/class-payments-query.php
1. Replace "start_date" with "end_date" property, when building the "before" part of the query inside of "remap_args" function.
This closes #8542.
> Replace "start_date" with "end_date" property when building the "before" part of the query inside of "remap_args" function

- includes/install.php
Fixes #8517
1. This primarily adjusts the logic of the check for whether a page was considered missing--`$missing_pages` has the `$page` as the array key, not the value, so I think this needed to be a different check.
2. I also set the `WP_Query` to return just IDs, so that the post object would only be retrieved if needed, and an array would not have to be reset.
To Test:
1. Activate EDD 3.0. Make sure that all of the required pages exist and have been set as options.
2. Deactivate EDD, then reactivate it.
3. Check and make sure no duplicate pages were created.
4. Optionally, delete one of the required pages, save the EDD settings (with a missing page), then deactivate and reactivate. The missing page should be created.
> Fix duplicate pages being created on activation

- assets/css/edd-admin.css
1. I think the CSS selector in EDD needs to be changed like this:
from: .edd_upload_field
to: input[type="text"].edd_upload_field
Then it will work just fine as it takes precedence over WordPress CSS.
> Change selector of upload field on admin download page to take precedence over WordPress CSS

- includes/class-easy-digital-downloads.php
- includes/deprecated-functions.php
- includes/deprecated-hooks.php
- includes/orders/functions/refunds.php
- tests/tests-easy-digital-downloads.php
Fixes #8540
Marking this as a draft as it results in multiple failed unit tests and I'm not 100% sure how to handle those:
> There were 8 failures:
> 
> 1) EDD\Discounts\Tests_Discounts::test_is_used_case_insensitive
> Unexpected deprecated notice for edd_pre_refund_payment
> Failed asserting that an array is empty.
> 
> /tmp/wordpress-tests-lib/includes/abstract-testcase.php:516
> /tmp/wordpress-tests-lib/includes/abstract-testcase.php:528
> 
> 2) EDD\Orders\EDD_Payment_Tests::test_refund_payment
> Unexpected deprecated notice for edd_pre_refund_payment
> Failed asserting that an array is empty.
> 
> /tmp/wordpress-tests-lib/includes/abstract-testcase.php:516
> /tmp/wordpress-tests-lib/includes/abstract-testcase.php:528
> 
> 3) EDD\Orders\EDD_Payment_Tests::test_refund_payment_legacy
> …
> Add legacy pre/post refund hooks to edd_refund_order

- includes/compat/class-discount.php
Fixes #8579 
1. Check for `$query` values before using (`$query['compare']` and `$query['where']`).
To test:
I found two ways to trigger error notices--one got me the original error and one got me a new one. In `release/3.0`, run this query:
```php
new WP_Query(
array(
'post_type'  => 'edd_discount',
'meta_query' => array(
array(
'key'   => 'expiration',
'value' => '2021-01-01',
),
),
)
);
```
You should get the original reported error. Note that this is not a validly used meta key for a discount, so it should not return any results anyway.
I encountered a second error when I changed the meta key to a key that EDD actually uses:
```php
new WP_Query(
array(
'post_type'  => 'edd_discount',
'meta_query' => array(
array(
'key'   => '_edd_discount_status',
'value' => …
```
> Update discount compatibility

- includes/compat/class-discount.php
Fixes #8587
1. Ensure the discount query has a clause to set `type = 'discount'`
> Ensure discount queries only return discount adjustments #8587

- includes/orders/functions/actions.php
- includes/orders/functions/orders.php
Fixes #8599
1. Round every subtotal, tax, total, amount before saving to the database. Applies to orders, order items, order adjustments.
> Round all order subtotals, taxes, totals before saving

- includes/admin/views/tmpl-order-tax.php
- includes/orders/functions/actions.php
Fixes #8591
1. Add the tax rate as a hidden input for manually created orders.
2. If a manually created order has tax, but no tax rate object, save the tax rate as metadata.
To Test:
1. Use a VAT plugin to manually generate an  order with tax which does not have a tax rate object in the database.
> Add custom tax rates to manually created orders

- includes/admin/upgrades/v3/class-data-migrator.php
- includes/class-edd-cli.php
- includes/class-edd-logging.php
- includes/download-functions.php
- includes/user-functions.php
Fixes #8570
1. Update `edd_count_file_downloads_of_user` and `edd_count_file_downloads_of_customer` to use the new `edd_count_file_download_logs` function.
2. Add the `user_id` as meta to the file download log if it exists (it looks like this was removed at one point, but we keep this data on migration, so adding it back for now. If we want to remove it, we should likely also remove it from the migration).
To test:
Make sure you have orders on your site. You can run this CLI command:
```
wp edd payments create --number=1000 --date=random --range=365 --generate_users=1
```
That will generate new customers, but not necessarily new users. You will need to link at least some of the customers to users. Then switch to this branch and run:
```
wp edd download_logs create …
```
> Update edd_count_file_downloads_of_user/customer functions

- includes/admin/upgrades/v3/class-data-migrator.php
Fixes #8616
1. Use `edd_get_customer` to retrieve the customer object when migrating additional email address.
To Test:
1. Set up a storefront in 2.10 with customers who have more than one email address assigned.
2. You can see the issue caused by the current code by running a 3.0 migration and seeing that the additional email addresses are not necessarily mapped to the correct customers (if the customer ID and user ID are the same, they could match).
3. Switch to this branch and run the migration--additional email addresses should show with the correct customers.
Note: this PR only fixes the migration. There is nothing currently to remove the `additional_email` metadata from the customer record.
> Fix additional customer email address migration

- includes/admin/upgrades/v3/class-customer-email-addresses.php
- includes/admin/upgrades/v3/upgrade-actions.php
Fixes #8118
1. Comment out step recovery.
This actually needed less work than I thought because it turns out we already have checks in place to skip items that already exist:
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/upgrades/v3/class-discounts.php#L56
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/upgrades/v3/class-orders.php#L57
Note that this recovery process may result in a few duplicate logs and notes getting added, but those won't be the end of the world.
To test:
- Start a migration via the UI.
- For easiest testing, wait for one of the long running processes to start (orders, logs).
- Then note which percentage you're on for that step.
- Navigate away from the …
> Allow migration step recovery #8118

- includes/admin/upgrades/v3/class-data-migrator.php
Fixes #8603
1. Adds `user_id` and `amount` to the core meta keys which don't need to be migrated.
To Test:
1. Run yet another migration from 2.x order data to 3.0. It may require having an older dataset.
> Do not migrate amount, user ID for payment meta

- includes/class-edd-session.php
Fixes #8037
1. Change the `secure` parameter for `setcookie` to check `is_ssl()`.
2. Remove error silencing.
> Use is_ssl() to set cookies to secure

- includes/orders/classes/class-order.php
- includes/orders/functions/orders.php
- includes/payments/class-edd-payment.php
- templates/history-purchases.php
Fixes #8550; branched from #8549
1. Create `edd_recoverable_order_statuses` to return an array of recoverable order statuses.
2. Create order recovery methods `$order->is_recoverable()` and `$order->get_recovery_url()`.
3. Use the new order methods in the purchase history template.
> Create order recovery methods

- includes/database/schemas/class-order-adjustments.php
- includes/database/schemas/class-order-items.php
- includes/database/schemas/class-orders.php
- includes/orders/functions/actions.php
- includes/orders/functions/orders.php
Fixes #8609 
1. Moves amount sanitization logic to BerlinDB, which means it will _always_ run prior to database insertion. This ensures payments created outside the normal checkout flow also get the same sanitization.
I chose `edd_sanitize_amount` amount for this, which handles rounding, but it also does a bunch of other stuff to strip thousand separators and whatnot. We should test this with non-standard decimal separators to make sure nothing breaks. Example:
- Set decimal separator to be a comma instead of a period.
- Make a purchase for $10.50.
- Make sure it shows up for the customer on the receipt, etc. as `10,50`, but it should be stored in the database as `10.50` (with more zeros at the end).
Other tests to run:
- The original issue: …
> Move amount sanitization to BerlinDB schema settings #8609

- includes/utils/class-date.php
Fixes #8586
1. Updates the `Date` constructor to match's `Carbon`. This should not impact functionality, as `Carbon` treats both `now` and `null` as the same.
> Update Date constructor to match Carbon's #8586

- includes/admin/settings/register-settings.php
Fixes #8612
1. Make sure `step`, `min`, and `max` are available for using when sanitizing a number setting.
> Update number settings sanitization

- includes/orders/classes/class-refund-validator.php
Fixes #8634
1. Use `bccomp` to compare the attempted refund amounts with the maximum refund amounts, because computers think in binary. See the related issue for more details.
> Update refund validation to work more precisely

- includes/database/schemas/class-orders.php
Fixes #8646
1. Add `validation` to order currencies in BerlinDB to cast currencies to uppercase.
> Set currency validation to strtoupper

- includes/admin/upgrades/v3/class-data-migrator.php
- includes/orders/functions/orders.php
Fix #8422
1. Remove extra serialization on order item meta during migration and new order creation.
To Test:
1. Run a migration on a data set with Recurring active (subscriptions). Check the order item meta table to make sure any `_option_recurring` metadata is saved as a serialized array, not a string.
2. Create a new order with a subscription. Check the order item meta.
> Remove extra serialization on order item meta

- includes/admin/class-edd-notices.php
Fixes #8633
1. Changes dismissal notice back to user meta instead of a site option to be consistent with EDD 2.x.
> Move admin notice dismissal back to user meta

- includes/payments/class-edd-payment.php
Fixes #8524 
1. Remove deprecation notice when changing order status to prevent excessive notifications
2. Fix typo in comment
> I wonder if we should just remove the notice completely and convey deprecation through the blog (which we may have already done anyway).
I checked the dev blog and found this from the [beta-1 post](https://easydigitaldownloads.com/development/2021/02/16/edd-3-0-beta1/):
```
Querying for payment/order records
...
// Valid in both 2.9 and 3.0
$payments = edd_get_payments( array(
'status' => 'publish'
) );
// Valid in 3.0 only
$payments = edd_get_orders( array(
'status' => 'complete'
) );
```
I'm not sure if this is enough of a notice, but it was mentioned on the blog.
> #8524 Remove deprecation notice 

- includes/admin/upgrades/v3/class-data-migrator.php
Fixes #8668 
1. If a transaction ID isn't found via `_edd_payment_transaction_id` meta, check in legacy payment notes (comments) instead.
> Add fallback for retrieving transaction ID via comments #8668

- includes/admin/downloads/dashboard-columns.php
- includes/admin/downloads/metabox.php
- includes/admin/reporting/export/class-batch-export.php
- includes/admin/tools/class-edd-tools-recount-all-stats.php
- includes/admin/tools/class-edd-tools-recount-download-stats.php
Fixes #8659 
1. Renames the `Earnings` download column to `Gross Revenue`.
2. `EDD_Batch_Export` - add public `$done` property. This was previously being set dynamically and it bugged me.
3. `EDD_Tools_Recount_Download_Stats` This has been heavily refactored.
- It now just does a direct database query with `SUM` and `COUNT` instead of looping over all items. This means there are no steps; it's all done in one single step.
- Because there are no steps, all step stashing/retrieving has been removed. I left the delete stuff in, just in case someone still has leftover step data from previous runs. This just cleans them up in case they're still there.
- For the query itself, order items with a status in `edd_get_gross_order_statuses()` are counted. We join on the orders table to ensure we only …
> Refactor download recount stats tools to exclude refunds #8659

- includes/admin/upgrades/v3/class-data-migrator.php
Fixes #8604
1. Ensure `_edd_payment_transaction_id` is not unnecesarily migrated to `wp_edd_ordermeta`
> issue/8604 - 3.0 Exclude `_edd_payment_transaction_id` From Order Meta Migration

- includes/admin/downloads/dashboard-columns.php
- includes/admin/downloads/metabox.php
- includes/admin/payments/class-payments-table.php
- includes/admin/tools.php
- includes/admin/tools/logs.php
- includes/database/engine/class-query.php
- includes/database/queries/class-order.php
Fixes #8658
1. Updates old "Sales" links to point to orders page with a product filter.
2. `class-payments-table.php`
- Removed unused variables.
- Add support for product ID filter.
- Add new "Product" filter in advanced filters.
3. Redirects page requests from the old sales log to the orders page (supporting 3 existing query args in the redirect).
4. BerlinDB (`database/engine/class-query.php`) - Set the second `parse_groupby()` parameter to `true`, which just prefixes the column name with the table alias. This fixes an ambiguous column error when doing a join and groupby at the same time.
5. `database/queries/class-order.php`
- Adds new `query_by_product()` parameter, and adds support for two new query args: `product_id` and `product_price_id`. If either of these are …
> Add Product filter to orders table & remove Sales Log #8658

- includes/class-edd-discount.php
Fixes #8655 
1. Strip `get_` on incoming method calls. So `get_name()` becomes `name`. Then it falls into case 2 (below).
2. If a method doesn't exist but a property does, call the method. I updated the existing call for this logic. Previously it was passing `$args` to the property, which... doesn't work. It was treating the property like a method instead of a property. My fix actually treats it like a property.
To test:
See original issue. Test both `get_ID()` and `get_name()` methods.
> Add support for old get_x() methods #8655

- includes/class-edd-download.php
Fixes #8640
1. Adds a `has_variable_prices` check to `is_single_price_mode`.
> Set single price mode to true only if download has variable prices

- includes/admin/upgrades/v3/class-data-migrator.php
Fixes #8671
1. Use tax and total metadata values (if available) in order migration.
> issue/8671 - 3.0 - Migration - Use Tax and Total Metadata Values in Order Migration

- includes/class-edd-cli.php
Fixes #8702
1. Show the count of existing tax rates (used already in the migration) as old records.
2. Count the number of `tax_rate` adjustments in the new table.
> Show number of migrated tax rates in CLI

- includes/admin/views/tmpl-order-adjustment.php
Fixes #8695
1. Add a second check in the order adjustment template to show negative fees as negative based on the original, non-formatted subtotal value.
> Show fees as negative if the raw subtotal is less than zero

- includes/query-filters.php
Fixes #8711
1. Check for `edd-api` in the `query_vars` and include in the early return before unsetting the discount query arg.
> Do not unset the discount query arg during an API request

- includes/cart/template.php
When there are callbacks added to  `edd_checkout_table_header_last` hook, this bug produces PHP warnings and notices. Introduced in 3a5007c.
> Fix incorrect array key name.

- assets/js/edd-ajax.js
- easy-digital-downloads.php
- includes/ajax-functions.php
- includes/template-functions.php
- includes/utils/class-tokenizer.php
- tests/tests-tokenizer.php
Fixes #8714 
1. Introduces a new `Tokenizer` class for hashing a piece of data.
2. A timestamp and a token are now added to the "add to cart" buttons and sent via AJAX.
3. `edd_ajax_add_to_cart()` A few changes have been made here:
- Exit early if `download_id` is not provided. (This is instead of nesting everything under an `if ( isset() )` check.)
- If the timestamp + token are provided and the token is valid, consider the request verified.
- Otherwise, fall back to still using the nonce. This ensures that we don't break anything if the add to cart links have been filtered and the filtered versions don't contain our timestamp + token.
- If the token isn't valid and the nonce isn't valid, bail.
Security-wise, the one downside this method has over the caching method is …
> Introduce Tokenizer to replace some nonce verifications #8714

- includes/discount-functions.php
Fixes #8718
1. Sets the original `$data` to a variable for use in the `edd_post_insert_discount` hook and adds it to `edd_add_discount`. (Pulled from `edd_store_discount`.
> Add edd_post_insert_discount hook to edd_add_discount

- includes/discount-functions.php
Fixes #8721
1. Sets the default `$discount_id` value back to `null`. This matches what it is in EDD master branch.
> Revert discount_id default back to null for backwards compat #8721

- includes/admin/settings/register-settings.php
- includes/emails/tags.php
Fixes #8696
1. Moves the rich text editor description field back below the editor (how it is in 2.x).
2. Adds the email tags list to the purchase receipt and sale notification descriptions (removed at some point in 3.0).
> Move wysiwyg description below editor, add email tags list back

- includes/payments/class-payment-stats.php
Fixes #8727
1. Re-adds the filter on `edd_count_payments_where`, which should make the date range apply correctly.
2. Updates an array of statuses to use `edd_get_gross_order_statuses()`.
3. Query sales only (no refunds).
> Apply count_where() to ensure date range is respected & query sales only #8727

- includes/payments/class-payment-stats.php
When fourth parameter, `$status`, is passed to `EDD_Payment_Stats::get_sales()`, it uses property of an object returned by `edd_count_payments()` without checking if that property exists. This can trigger PHP notice if passed status(es) are not returned by `edd_count_payments()`.
This PR fixes this, and it simplifies code.
> Verify that property of an object exists before using it

- includes/admin/upgrades/v3/class-data-migrator.php
Fixes #8729
1. Instead of filtering empty values out from a customer address array, just use the `array_filter` to see if the address is empty.
> Use filter_array only to check if an address should be migrated

- includes/misc-functions.php
Fixes #8744 
1. Changes the extension to `.zip` to line up with our default nginx rules as per the docs.
> Use a zip for the nginx rules test #8744

- includes/adjustments/class-adjustment.php
In [`EDD\Adjustments\Adjustment` documentation](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/289400c2f83d792c6ea645ef9eb2962fae1455a1/includes/adjustments/class-adjustment.php#L29) it says that it's `string`, however in property documentation it says that it's `boolean`.
> Fix property type in PHPDoc

- includes/admin/reporting/reports.php
- includes/class-stats.php
- includes/reports/data/payment-gateways/class-gateway-stats-list-table.php
Fixes #8735
1. Payment Gateways "Refunds" report - set type to `'refund'` and status to `'complete'`. This ensure we retrieve all refunded amounts.
2. Stats `get_order_count()`, replace status list with `edd_get_gross_order_statuses()`. (Same status array, just using the new function.)
3. `get_gateway_data()` - Set the default type to `'sale'` and default status to `edd_get_gross_order_statuses()`. So unless overridden (such as the Refunds one), all Payment Gateways reports will use these settings.
4. Payment Gateways Table - change `Refunded Sales` to `Refunds Issued`.
> Audit Payment Gateways reports for type/status combinations. #8735

- includes/class-edd-discount.php
1. Passed $set_error to all applicable methods in the discount class.
2. Add $this to the calc function.
> Pass $set_error to all applicable discount class methods

- includes/discount-functions.php
Fixes #8768 
1. Add missing greater than symbol to close span element
> #8768 Close span element

- includes/discount-functions.php
Fixes #8756
1. Adds a check when creating a new discount (using `edd_add_discount`) to mark the discount as expired if the end date has passed.
2. When checking the store for active discounts, retrieve 10 `active` discount objects instead of just 1.
> Update discount expiration/active checks

- includes/discount-functions.php
Fixes #8773
1. Check if the discount doesn't exist and return `false`.
> Return false on invalid discounts #8773

- includes/payments/class-payments-query.php
Fixes #8783 
1. Adds a check for `$this->args['offset']` to `remap_args` and use it if possible, preferring that to `paged`/`posts_per_page`.
> Add offset to remap_args for payments queries

- includes/gateways/paypal-standard.php
Fixes #8598
1. Update the PayPal Standard transaction URL to use `https://www.paypal.com/activity/payment/TRANSACTIONID` as the format.
> Update PayPal Standard transaction URL

- includes/admin/tools.php
Fixes #6923
1. Add the Plugin URI or Author URI in the plugins report as it makes it easier to tell who is the developer for a plugin in support
> issue/6923 - Include Plugin URI in the System Info report

- includes/database/schemas/class-orders.php
- includes/database/tables/class-orders.php
Fixes #8792
1. Set the default order gateway to `manual`.
2. Upgrade the orders table to fill any empty gateways.
> Set default order gateway to manual

- includes/admin/upgrades/v3/class-data-migrator.php
Fixes #8780
1. Add an additional payment metadata check for looking for the order total during migration.
> Update order migration for orders missing payment total

- includes/admin/upgrades/v3/class-remove-legacy-data.php
- includes/class-edd-cli.php
- includes/database/tables/class-customers.php
Fixes #8798
1. Removes the column drop from the database upgrade routine. (This was run immediately upon upgrading to 3.0.)
2. Add the column drop to both the CLI legacy removal and the UI legacy removal.
1. Upgrade to release/3.0 & migrate.
2. Ensure the `wp_edd_customers` table still has the `payment_ids` column.
3. Maybe make a new order with a brand new account, which will create a new customer, just to make sure that all still works okay.
4. Remove legacy data via the UI. Ensure the `payment_ids` column is gone.
Repeat steps 1 and 2 (skip 3), but this time remove legacy data via CLI. Ensure the `payment_ids` column is gone.
> Drop payment_ids column when legacy data is removed #8798

- includes/admin/upgrades/v3/class-data-migrator.php
Fixes #8801
1. Use the original `post_parent` as the new order `parent` if it is not empty.
> Set order parent from original data->post_parent in migration

- includes/gateways/paypal/admin/connect.php
Fixes #8811
1. Moved some duplicated `json_decode( get_option( 'edd_paypal_commerce_connect_details_' . $mode ) );` code into a new function: `get_partner_details()`.
2. If we don't have REST API credentials, but we do have partner connect information, then we assume that the modal didn't work and display an error message:
@mihaijoldis I'd love for you to test this since you had popups blocked and were able to trigger this behaviour reliably. Basically just attempt to connect with PayPal when popups are blocked, make sure the PayPal modal DOESN'T open, continue through the process and click back to your site. Hopefully you should see the above error message.
@LisaCee and @robincornett you're welcome to check the above too, but also do a normal connection with the modal …
> Show error message if we think the modal didn't open #8811

- includes/admin/upgrades/v3/class-data-migrator.php
Fixes #8816
1. Only calculate the time difference if `$modified_time` is different from `$modified_time_gmt`
2. Catch exceptions from `DateInterval` operations. Worst case scenario here we end up with `$date_created_gmt` unmodified, which is no biggie.
See issue for steps to reproduce this problem. If you use my data, then post-migration you should see the date like this:
(Note my store time zone is UTC+0)
> Only calculate diff if dates are not equal & catch exceptions #8816

- easy-digital-downloads.php
- includes/admin/upgrades/downgrades.php
- includes/admin/upgrades/upgrade-functions.php
- includes/install.php
Fixes #8805
1. Detects a downgrade from EDD 3.0. This is done by checking if the _database_ version number is >= 3.0, but the _constant_ within the plugin is < 3.0.
2. If a downgrade has been detected, show the user a notice asking if that's correct and if they want to proceed.
3. Completing a downgrade rolls back the database changes.
4. Dismissing the notice just removes the downgrade flag with no other action.
- Make sure a site that has only ever been on EDD 2.x doesn't see any new notices.
- Do a fresh EDD 3.0 install. Make sure you don't see any new notices.
- Migrate from EDD 2.x to 3.0. Then downgrade. Make sure notice appears.
- Before clicking Upgrade, confirm that your `wp_edd_customermeta` table has a column called `edd_customer_id`.
- Click Upgrade.
- …
> Add EDD 3.0 rollback handling #8805

- includes/gateways/paypal/admin/connect.php
Fixes #8825 
1. Adds "Gateway Status" prefix to the inactive gateway list item.
2. Also adds a dashicon-no to visually indicate inactive gateway.
> Update PayPal inactive gateway line item

- includes/class-structured-data.php
Fixes #8818
1. Remove the `edd_structured_data_get_data` and `edd_structured_data_set_data` unless/until we decide they're necessary.
> Remove structured data filters for now

- templates/history-downloads.php
For product(s) with variable prices included in Bundle(s) we need to get price ID in a different way. Without this change, customers see all downloadable files for variable pricing products included in the Bundle.
> BUGFIX: Get price ID of product with variable prices included in Bundle

- includes/database/schemas/class-adjustments.php
Fixes #7139
1. @JJJ was right; we needed to make the `use_count` sortable.
> Make use_count sortable for adjustments

- includes/admin/payments/orders.php
Fixes #8803
1. Add `class="edd-form-group__input small-text"` to the input fields for hour/minute on the order details screen.
> Fix hour/minute inputs on order details screen

- includes/payments/functions.php
Fixes #8848
1. Check if `$transaction_ids[0]` isset.
2. Remove `$transaction_id` reassignment.
> Remove variable reassignment #8848

- includes/emails/class-edd-email-tags.php
- includes/emails/tags-inserter.php
Fixes #8829
1. If the email `$tag['label']` is empty, then the label will be created from the `$tag['tag']` instead.
> Create tag label from tag if label is empty

- includes/payments/actions.php
- includes/payments/class-edd-payment.php
Fixes #8843
1. If `edd_get_order` does not return an order in `edd_complete_purchase`, this prevents the rest of the function from running.
2. If there is not an order object/property in `check_status` in the payment class, this does an early return.
3. And the `update_meta` method now returns early if there is not a payment ID/property.
Basically I started with trying to create a subscription improperly in 3.0 and kept fixing errors until they stopped occurring. Note that in 3.0, creating a subscription without a customer attached fails to create an order at all. However, the same steps in 2.11.1 do create a new payment, although there is no customer attached. I'm not sure which behavior is preferable, to be honest, so putting the PR up as it is for now.
> Make sure an order object exists before using it in payment actions

- includes/admin/settings/register-settings.php
Fixes #8857
1. Update the SendWP account link.
2. Reorganize the `sprintf` so that the string for translation does not include the link.
> Update SendWP account link

- includes/class-edd-cli.php
Fixes #8859
1. Changes the `$price_id` variable to be properly assigned from `$assoc_args['price_id']`.
Submitting a PR now because I'm actively using this.
> Fix price_id parameter for CLI payments

- includes/emails/functions.php
- includes/emails/template.php
- includes/orders/functions/refunds.php
- includes/payments/actions.php
- includes/payments/class-edd-payment.php
- tests/orders/tests-edd-payment.php
Fixes #8804
1. Move the `edd_update_payment_status` hook to an anonymous function hooked into `edd_transition_order_status`.
2. Decrease download earnings/sales as part of `edd_refund_order`. I believe this is consistent with how the download earnings are handled when adding a new order (both via cart and admin). These stats were not being updated when the hook was moved.
3. Oddly, with these changes, unit tests are experiencing errors in `edd_get_sale_notification_body_content` and `edd_get_email_names`. Although not technically related to this issue, I updated the logic in both of these to start with the fallback values, and only use the user data if it's available. Not sure why it would magically start failing with the  changes I made, but the extra checks seem …
> Move `edd_update_payment_status` to a transition hook

- assets/js/paypal-checkout.js
Fixes #8867
1. Change `return` statements to `continue`. The issue was that it was successfully running the first, then any later failures prevented the next buttons from loading.
> Continue instead of return #8867

- includes/discount-functions.php
Fixes #8747
1. Check if we have a valid discount object before using.
I just fixed the obvious / simple functions in this file. We can address any others as they become known.
> Always check if discount object exists before using #8747

- includes/class-edd-html-elements.php
- tests/tests-html-elements.php
Fixes #8433
1. Adds support for `required` HTML5 attribute to select/text inputs, set to `false` by default.
2. Allow methods which support custom parameters to set `required`: `product_dropdown`, `customer_dropdown`, `user_dropdown`, `discount_dropdown`, `country_select`, `region_select`.
> Add support for required attribute to select/text inputs

- includes/gateways/paypal/webhooks/events/abstract-webhook-event.php
- includes/gateways/paypal/webhooks/events/class-payment-capture-completed.php
- includes/gateways/paypal/webhooks/events/class-payment-capture-denied.php
- includes/gateways/paypal/webhooks/events/class-payment-capture-refunded.php
- tests/gateways/tests-paypal.php
Fixes #8874
1. Deprecate `get_payment_from_capture` methods. I'm not triggering an actual deprecation notice for now, just marking them as deprecated in the docblocks.
2. Implement replacement `get_order_from_capture` methods. Same logic, but returning an `Order` object.
3. Update webhooks to use `Order` objects / methods.
4. Update unit tests to use `Order` objects.
> Rework PayPal Commerce webhooks to use Order object #8874

- includes/gateways/paypal/functions.php
Fixes #8870
1. Run all amounts through `edd_sanitize_amount()`, which handles rounding and formatting.
> Sanitize all amounts to ensure rounding & formatting #8870

- includes/discount-functions.php
Fixes #8885
1. This changes the checks for the product condition, product requirements, and excluded products metadata to be an `empty` check instead of `isset`, to prevent empty metadata rows being saved to the new database tables during migration.
Additionally this will impact any use of `edd_store_discount` and `edd_add_discount`.
In the database I'm migrating, the existing discount posts had this data saved as empty post meta rows.
> Update discount metadata checks to empty instead of isset

- includes/api/class-edd-api.php
Fixes #8250 
1. Switch `edd_die` to `die` after outputting API Data.
This will avoid the `edd_die` from calling `wp_die` which is where the output from Query Monitor comes in.
> Switch from edd_die() to die() on API responses #8250

- includes/admin/admin-pages.php
Fixes #8898 
1. Adds a 'Reports' menu item under the main Dashboard widget, which links to the EDD Reports view.
> Add our submenu item to the Dashboard menu list #8898

- includes/misc-functions.php
Fixes #7755
1. Wrap all backtrace outputs in an empty check.
> Only output a backtrace in deprecation methods if it isn't empty #7755

- includes/api/class-edd-api.php
- includes/class-edd-discount.php
- tests/tests-discounts.php
Fixes #8908
1. Once verified that we updated the correct post ID, we update the meta as well.
> Update post meta 'status' as well as post_status

- includes/gateways/paypal/functions.php
Fixes #8911
1. Uses `substr()` to truncate a product item name to 127 characters for PayPal Commerce orders.
> Truncate individual item name for PayPal when over 127 characters

- includes/admin/class-edd-notices.php
Fixes #8876
1. Changes the capability check to `manage_shop_settings`, as that's what's in 2.x currently.
2. Check if notice is dismissed before displaying. (If it has been, then don't display.)
3. Customize the dismissal URL for nginx vs apache notices (as the dismissal keys are different for each).
> Check if notices have been dismissed before displaying #8876

- includes/admin/discounts/contextual-help.php
- includes/admin/downloads/contextual-help.php
- includes/admin/payments/contextual-help.php
- includes/admin/reporting/contextual-help.php
- includes/admin/settings/contextual-help.php
Fixes #
Version: 2.11.3
Parse error broke my localhost:
```sh
[01-Nov-2021 11:38:26 UTC] PHP Parse error:  syntax error, unexpected ')' in /home/anna/html/wp58/wp-content/plugins/easy-digital-downloads/includes/admin/discounts/contextual-help.php on line 30
```
This error happens 5 times in these `contextual-help.php` files:
- `discounts`
- `downloads`
- `payments`
- `reporting`
- `settings`
1. Fix parentheses
> Fix PHP parser error in contextual-help.php files

- includes/admin/promos/notices/class-license-upgrade-notice.php
Fixes #8947
1. Sets the `$include_non_exclusive` flag to false when evaluating `edd_is_admin_page` for the license upgrade notices.
> Fix license upgrade display logic for EDD admin pages

- easy-digital-downloads.php
- includes/admin/class-pass-manager.php
- includes/class-edd-license-handler.php
- includes/licensing/licensing-functions.php
Fixes #8969 
1. Hooks into `admin_init` and saves the content of the `$edd_licensed_products` global. This allows us to reliably access that data outside the context of `WP-Admin`.
- Option is cached for 1 day to avoid excessive writing to the DB. So we only update it once per day.
2. Introduces a new helper function called `get_licensed_products()`. This is a wrapper for returning the result of that option.
I encountered this problem while testing https://github.com/awesomemotive/easy-digital-downloads/pull/8941 . Testing this fix requires working with that PR a bit.
Create a new file in `wp-content/uploads` called `edd-notifications.json`. Paste in these contents:
```json
[
{
"title": "📣 New Multi-Currency Extension!",
"content": "Now it's easy to add multiple …
```
> Save $edd_licensed_products to options so it can be referenced outside WP-Admin #8969

- includes/misc-functions.php
Fixes #8975
1. Adds an optional boolean parameter `$use_first_order` to the `edd_get_activation_date` function. Set to false by default.
2. If called outside of the initial installation, set the parameter to `true` to run a quick payments query to get the first order from the database.
3. If an order is retrieved, use its date as the activation date (this is not necessarily a complete order so I'm just using the date, not completed date).
4. So when we run the installer, we would not pass a parameter, but using it elsewhere, which might happen for an existing install, we would.
On my own storefront, this changes the activation date from today (`1636029820`) to `1434612134`, which is June 2015.
> Update edd_get_activation_date to optionally set date to first order

- includes/admin/upgrades/v3/class-data-migrator.php
Fixes #8933
1. Add `isset( $post_meta['_edd_log_ip'] )` before using it in the migration.
> Check if _edd_log_ip is set before using

- includes/class-edd-cli.php
Fixes #8946
1. Just sets `$query` to an empty string before beginning the `foreach`.
> Define $query variable before using

- easy-digital-downloads.php
In PHP it is possible to write to properties without declaring them. For example, the following is perfectly valid PHP code:
```
class MyClass { }
$x = new MyClass();
$x->foo = true;
```
Generally, it is a good practice to explictly declare properties to avoid accidental typos and provide IDE auto-completion:
```
class MyClass {
public $foo;
}
$x = new MyClass();
$x->foo = true;
```
Fixes # (none)
1. Add unlisted payment_stats property
> Add unlisted property

- includes/admin/class-edd-notices.php
- includes/emails/actions.php
- includes/emails/class-edd-emails.php
- includes/emails/functions.php
Fixes #8986
1. Updates the emails `send` method to document the `return`.
2. Updates `edd_email_purchase_receipt` to use that boolean and also return it.
3. If that returns `false` when resending the purchase receipt, generate a failure/error notice.
> Add failure notice if purchase receipt could not be re-sent

- easy-digital-downloads.php
- includes/admin/class-pass-manager.php
- includes/class-edd-license-handler.php
- tests/tests-pass-manager.php
Fixes #8980
1. Adds a highest license key property to the `Pass_Manager` class.
2. Instead of just getting the highest pass ID, set the highest pass ID and license key together when evaluating passes.
3. Update related tests docs.
4. When setting up the auto update class in `EDD_License`, if no license key is saved for the extension, but a pass license key is available, use that for the auto updater.
Note that the Pass Manager class changes are pulled directly from #8945. Additionally, I have branched this off of 2.11.4 although the issue is not currently milestoned.
> Use highest pass license key for updating if a specific key is not set

- includes/admin/reporting/export/class-batch-export-earnings-report.php
The counting of cols is done twice per iteration even though the number of colls is not being manipulated in the loop. Pre-computing the number ahead of the loop will same 2n performance of the operation (O(n) savings of performance).
Fixes #: (none)
Using PR to test a SAST. 
1. Pre-compute count of $cols as $count ahead of loop
2. Replace count( $cols) with $count inside loop
> Performance Improvement in batch export earnings report

- includes/admin/reporting/export/class-batch-export-earnings-report.php
Fixes #8995
Simplify the start and end date logic. The end date is now always set to the last day of the start date's month (using the `t` date format). So instead of this:
```mysql
AND posts.post_date >= '2021-08-01 00:00:00'
AND posts.post_date < '2021-09-01 23:59:59'
```
we should be seeing this:
```mysql
AND posts.post_date >= '2021-08-01 00:00:00'
AND posts.post_date <= '2021-08-31 23:59:59'
```
This ensure we only ever work within 1 month.
To account for this, you'll note I also changed the query comparison to `<=` instead of `<`.
To test, I honestly just found it easiest to log this query: https://github.com/awesomemotive/easy-digital-downloads/blob/b48c077c245b1329e0244aa30d5ff3728bedce4c/includes/admin/reporting/export/class-batch-export-earnings-report.php#L265- …
> Simplify start & end logic to always use last day of month #8995

- includes/deprecated-functions.php
- includes/download-functions.php
- tests/tests-process-dowload.php
Fixes #8917
Based on a discussion with @cklosowski I'm putting together this draft PR to see how it does. The issue, I think, is that we have the download URL being built off of one array, and validated off of another array, and the order now matters. However, since two different filters/functions/filters are involved, the problem is that the two arrays can be disordered/out of sync with each other.
1. Creates a new function, `edd_get_url_token_parameters`, which returns a one dimensional array of the URL parameters which are allowed for URL validation.
2. That array is replaced 1:1 in `edd_validate_url_token`.
3. The same array is now used as the base array in `edd_get_download_file_url` and populated with empty values, so that the initial array order is set to match …
> Ensure file URL creation and validation use the same arary of parameters

- includes/admin/settings/register-settings.php
Fixes #8997 
1. Removes link to renew license keys
2. We can maybe add this back if we alter the license `check_license` response to include if it is tied to a subscription or not so we can conditionally show it.
> Remove 'renew' link in license approaching expiration #8997

- includes/misc-functions.php
Fixes #8913
1. If `wp_get_environment_type` exists, use that to check if the current site is a development site. This function returns one of `'local'`, `'development'`, `'staging'`, or`'production'`. If the environment is `local` or `development`, this is considered to be true and returns early, instead of sorting through the URL options.
2. Updates the doc block return value, as this function actually returns either false or a string, matching whatever was determined to be the determining condition.
> Update edd_is_dev_environment to use wp_get_environment_type

- includes/admin/admin-actions.php
Fixes #9003
1. Just comments out the `add_filter( 'views_edit-download' ...` line that was commented out for 2.11.3. There doesn't seem to be a more practical way to add this, and this will keep it consistent with the taxonomy screens.
> Add product tabs back to downloads screen

- includes/admin/upload-functions.php
- includes/misc-functions.php
- includes/process-download.php
- tests/tests-misc.php
Fixes #8999
1. Adds `webp` to `edd_protected_directory_allowed_filetypes`.
2. Updates `edd_string_is_image_url` to include `webp` and condense logic.
3. Adds `webp` to `edd_get_file_ctype`.
4. Adds `webp` assertion to `test_string_is_image_url`.
> Add webp to supported file, image types

- includes/admin/settings/display-settings.php
- includes/admin/settings/register-settings.php
Fixes #9001
1. Do not get all of the registered settings within `edd_get_settings_tabs`.
2. Update `edd_options_page`:
- Remove duplicate `edd_get_settings_tab_sections`.
- Remove duplicate `edd_get_settings_tabs`.
- Evaluate the settings tabs against the registered settings, which have already been pulled, and remove any tabs which have no settings.
> Refactor edd_get_settings_tabs

- includes/admin/settings/register-settings.php
- includes/class-edd-license-handler.php
Fixes #9010
1. When checking the `*_license_active` option, check if the `license` property is set before checking whether it is `'valid'`. This is in a few different places:
- When evaluating whether to show the "Deactivate" button for an active license.
- When evaluating whether to show a warning notice with the license key input.
- When evaluating whether to show a general admin notice.
- If a plugin is out of date, a message is added to the plugin row update notice as well.
> Update active license options checks

- includes/database/NotificationsDB.php
Fixes #9027 
1. Converts anonymous static function to a named static method, for PHP 5.3 support.
> Move cron scheduling to a named method, for PHP 5.3 support #9027

- includes/payments/functions.php
Fixes #9026
1. Just combines the `array_key_exists` check with checking if `$found_key` has a value first.
> Check for $found_key value before checking for array key

- includes/admin/import/class-batch-import-downloads.php
- includes/admin/import/class-batch-import-payments.php
- includes/admin/import/class-batch-import.php
Fixes #9033
This is nearly identical to #8457, with a couple specific differences:
1. Per Chris, we are not removing the ParseCSV library file in case any extensions may be trying to load it. It is removed in 3.0.
2. The since version on the `get_csv_file` method is marked as 2.11.5 instead of 3.0.
3. When importing payments, I encountered a job-stopping error when `$customer` and `$email` were not defined, and then `$customer_by_email`. I think that method is difficult to read but I did the minimum I could do to prevent the errors.
> Update batch importer to use str_getcsv instead of an external library

- includes/emails/actions.php
Fixes #9025 
1. Updates `edd_trigger_purchase_receipt` to check for the order type and returns early if it's a `refund`.
> Do not send purchase email when creating a refund

- includes/gateways/paypal/admin/notices.php
Fixes #9039
1. Adds a nonce to the dismiss URL. I guess this was added in 3.0. :shrug:
> Add nonce to dismiss URL #9039

- includes/admin/extensions/abstract-extension.php
Fixes #9042
Currently based off of master.
1. Adds `can_show_product_section` check to the `hide_submit_button` method.
> Check if current product section can show before hiding submit button

- includes/admin/settings/display-settings.php
Fixes #9045
1. Adds a new required `$tabs` parameter to the `edd_options_page_primary_nav()` function. This function is new in 3.0 so not worried about rearranging parameters. By passing in the tabs instead of re-retrieving them, we get the modified tabs array that's set in `edd_options_page()`. **This change prevents the "Styles" tab from appearing.**
2. Removes the `ob_start()` and `ob_get_clean()` from `edd_options_page_primary_nav()` as I did not feel it was necessary.
3. In `edd_options_page()` I added an extra conditional when setting `$active_tab` to see if it exists in `$all_settings`. **This change protects against the PHP notice in the event that you navigate to `wp-admin/edit.php?post_type=download&page=edd-settings&tab=styles&section=buttons` manually.**
> Pass modified tabs to navigation function #9045

- includes/admin/extensions/abstract-extension.php
- includes/admin/extensions/product-education/class-email-marketing.php
- includes/admin/extensions/product-education/class-invoices.php
- includes/admin/extensions/product-education/class-recurring.php
- includes/admin/extensions/product-education/class-reviews.php
1. Creates a `settings_section` property in the abstract extension class. It's set to `general` by default but should always be overridden.
2. Updates email marketing, Invoices, Reviews, and Recurring to use the new property.
3. Also updates the default upgrade URL to include `/pricing` so that it goes directly to the pricing page instead of the front page.
> Use settings section for UTM medium

- includes/reports/reports-functions.php
Fixes #9072
1. The `display_currency_filter` currently counts how many currencies are represented in the EDD store orders and displays the filter if the number is not _equal_ to 1. However, the `$wpdb` result can be an empty array when there are no orders, so the count comparison should factor that in. This PR changes the `===` to a less than or equal to comparison.
> Update logic for showing currency filter on reports

- includes/payments/class-payment-stats.php
- tests/tests-stats.php
Fixes #9070
1. Updates the `get_earnings` method in the payment stats class to use `$wpdb->get_results()` and then add up the results ... I don't know if it's possible to get the `SUM` of two columns in a single query--if so, that might would be more efficient.
2. I also updated the stats unit tests to run two orders and get the data from them. This could be improved by generating a distinctly different order instead of just duplicating the one that's there. But with the current release code, `test_get_earnings_for_this_month_for_download_should_return_240` and `test_get_earnings_for_this_month_for_download_excluding_taxes_should_return_190` would fail, I think.
> Update stats get_earnings method to correctly query for a single download

- includes/cart/functions.php
- tests/tests-cart.php
1. Adds a new unit test, `test_cart_is_empty`, with two assertions.
2. Adds a test for `edd_is_cart_empty()` (true) to `test_empty_cart_is_array`.
3. Adds a test for `edd_is_cart_empty()` (false) to `test_get_cart_contents`.
4. Adds a test for `edd_is_cart_empty()` (false) to `test_restore_cart`.
> Add unit tests for edd_is_cart_empty()

- includes/orders/functions/actions.php
Fixes #9085
1. Removes the functions to increase sales/usage/stats from `edd_add_manual_order` because they're all run in `edd_complete_purchase` as well, so things are being duplicated.
> Remove duplicate stats functions from manual orders

- includes/orders/functions/refunds.php
- tests/orders/tests-refunds.php
Fixes #9079 
1. Before marking an order as fully refunded, count the number of items in the order which do not have a status of `refunded`. If that count is greater than 0, regardless of the order's total, the order should not be marked fully refunded.
> Count non-refunded items remaining on order before marking as fully refunded

- .buildkite/pipeline.sh
Adds WP 5.7,5.8 to tested WordPress versions.
> Update WordPress versions for buildkite tests

- includes/gateways/paypal-standard.php
Fixes #9102
1. Updates the logic to get a fallback value for the `$purchase_key` variable for the PayPal IPN, as it appears that the `item_number` value may not be defined.
> Update purchase key variable in PayPal Standard IPN

- includes/orders/functions/actions.php
Fixes #9105
1. The only real change is the creation of the new hook, which accepts the order ID and the parsed order data as the two parameters.
2. All other changes are renaming `$data` to `$order_data` for clarity.
> Create edd_post_add_manual_order hook

- includes/orders/functions/refunds.php
- includes/payments/actions.php
Fixes #9031
1. Adds a check for the order `type` during `edd_complete_purchase` and exits early if the order is not a sale.
2. Additionally updates the refund order completed date at the end of `edd_refund_order` (with the first change, the refund was not getting a completed date).
Note that with this change, refund orders no longer have a `date_refundable` value added to the database, which seems appropriate.
> Do not run edd_complete_purchase on refunds

- includes/admin/reporting/reports.php
- includes/post-types.php
- includes/reports/data/downloads/class-earnings-by-taxonomy-list-table.php
Fixes #9124
1. Creates the `edd_get_download_taxonomies` helper function, which will, by default, return only the `download_category` and `download_tag` taxonomy names.
2. Applies a filter to the array so a developer can manually add a custom taxonomy to the array.
3. Updates the customer export and the taxonomy earnings table to use this new helper function.
> Create edd_get_download_taxonomies helper function

- includes/gateways/paypal/integrations.php
- includes/gateways/paypal/paypal.php
Fixes #9133
1. Adds a filter for `edd_auto_register_login_user` for PayPal Commerce. The usage is consistent with what we do in Stripe.
> Add a filter on edd_auto_register_login_user for PayPal Commerce

- includes/admin/settings/register-settings.php
Fixes #9120 
1. Shifts the 'moderation' settings to the 'checkout' settings.
2. Moves 'Refunds' submenu to 'Payments' tab
> Moves moderation to checkout and adds refunds to gateways #9120

- includes/admin/settings/register-settings.php
Fixes #9128
Forked from #9120 because the setting is moving in that PR.
1. Updates `edd_sanitize_banned_emails` to use the tab/section specific hook: `edd_settings_gateways-checkout_sanitize` for sanitizing the banned emails list so that it only runs when that section is saved.
> Update banned emails sanitization

- includes/class-stats.php
- tests/orders/tests-stats.php
Fixes #9122
1. Sets the `price_id` default to `null` instead of an empty string.
2. Creates `generate_price_id_query_sql` method to check the price ID and generate the SQL query string.
3. In places where a price ID is cast to an absolute value, check if it's numeric first--if numeric, cast as before; if not, set to `null` instead.
> Update order stats class to use null, remove empty checks

- includes/admin/settings/contextual-help.php
- includes/admin/settings/register-settings.php
Fixes #9136
1. Renames the privacy tab to policies as suggested.
2. Also updates the corresponding help tab.
> Rename Privacy tab to Policies

- includes/database/engine/class-query.php
- includes/orders/functions/orders.php
- tests/orders/tests-orders.php
Fixes #9138
1. Runs the meta type parameter through `add_prefix` before attempting to delete the metadata.
2. Adds a unit test to ensure that order meta is deleted when an order is deleted.
3. Adds `edd_order_destroyed` action hook.
Note: this is already fixed in BerlinDB (https://github.com/berlindb/core/issues/84) and I'm thinking EDD is on version 1.0.x of Berlin. This PR is pretty minimal--and actually looking at what was done to resolve the issue in Berlin, probably incomplete.
> Make sure custom object meta is deleted along with the object

- includes/admin/payments/actions.php
- includes/class-utilities.php
- includes/date-functions.php
- includes/orders/functions/actions.php
- tests/tests-date-functions.php
Fixes #9150
1. In `EDD()->utils->date`, adds a check for whether the incoming string is a valid date/time string. If not, resets it to `'now'`.
2. Adds a unit test which tests an invalid date string to ensure it returns a valid date object.
> Reset date string if invalid

- templates/history-downloads.php
Fixes #9172
1. Updates the logic for showing download files to include `partially_refunded` as well as `complete`.
> Show download links for partially refunded order items in download history

- includes/payments/functions.php
Fixes #9181
1. Compares `$found_key` explicitly to `false` as `0` is a valid array key.
> Make found key check stricter

- includes/admin/payments/contextual-help.php
Fixes #9186
1. Removes the Invoices help tab and reference.
2. Updates the full/partial refund help text.
> Update orders' contextual help

- includes/class-edd-download.php
- includes/download-functions.php
- includes/emails/tags.php
- includes/process-download.php
- templates/shortcode-receipt.php
- tests/downloads/tests-process-download.php
Fixes #9182 
Branched from #9179 due to using new `edd_get_deliverable_order_item_statuses` function.
This ended up being a bit thornier to sort through than initially intended due to previously ignoring `0` price IDs as actual price IDs. Also I think Berlin is doing something that maybe we don't want it to do and I need to look into that.
1. The primary change was to add a secondary set of checks to the `edd_order_grants_access_to_download_files` method to check for items being downloaded as part of a bundle, since the download URL will not contain the correct order item/price ID. This secondary check loops through all order items and checks if the current download/price ID combo matches a defined bundle item.
2. The `edd_process_signed_download_url` function has been …
> Update download file URL, access evaluation

- includes/admin/payments/orders.php
Fixes #9203
1. Adds `edd-order-resend-receipt-email` back to the radio input as a class (it was inadvertently removed in #7777).
> Add missing class to radio input for orders with multiple emails

- includes/gateways/paypal/integrations.php
Fixes #9205
1. Includes the parameter for the filter and returns it as the fallback if the PayPal Commerce requirements are not met.
> Update PayPal Commerce Auto Register integration to inherit login state

- includes/admin/payments/orders.php
- includes/admin/views/tmpl-order-item.php
- includes/class-edd-download.php
- includes/download-functions.php
- includes/emails/tags.php
- includes/orders/classes/class-order-item.php
- includes/orders/functions/statuses.php
- includes/process-download.php
- templates/history-downloads.php
- templates/shortcode-receipt.php
- tests/downloads/tests-process-download.php
- tests/orders/tests-order-items.php
Fixes #9179
1. Creates the `is_deliverable` helper method in the `Order_Item` class. This just determines if assets can be delivered to the customer based on the order item status being `complete` or `partially_refunded`. I'm open to renaming this if needed.
2. Uses the new helper method on the order details screen in the admin and the download history shortcode.
> Create order item is_deliverable method

- includes/cart/class-edd-cart.php
- includes/discount-functions.php
- includes/orders/functions/orders.php
- languages/easy-digital-downloads.pot
Fixes #9207
1. Adds an optional parameter to `edd_get_item_discount_amount` allowing a custom price to be added.
2. Adjusts the cart contents, edd_build_order, and discount html to send in the actual price of the item, not looked up.
> Allow passing in a item price to the edd_get_item_discount_amount function, to make it context aware #9207

- includes/database/tables/class-order-transactions.php
Fixes #9209 
1. Adds an index of `object_type, object_id` to the `edd_order_transactions` table.
> Adding an index for object_type and object_id to the transactions table #9209

- includes/shortcodes.php
Fixes #9211
1. When using the profile editor, creating a new address will assign it as primary.
2. Adds the `name` property to editing/adding an address.
> Update profile editor address updating

- includes/admin/upgrades/upgrade-functions.php
- includes/class-edd-cli.php
Fixes #9216
1. If a CLI migration has been started, adds an option to the database.
2. Loading an admin screen while this option exists will show an admin message "Easy Digital Downloads is performing a database migration via WP-CLI. This message will be removed when the migration is complete." instead of the default EDD migration notice/link. This notice has no link to the upgrade screen.
3. The CLI option is deleted before the legacy data prompt shows.
> Change admin notice if a CLI migration is running

- includes/admin/upgrades/v3/class-data-migrator.php
- includes/class-edd-discount.php
Fixes #9218
1. Adds back legacy keys removed in #8544, as they were what was breaking the migration.
2. Updates the `scope` check somewhat in the legacy mapping to only map values that exist in the passed parameters.
> Update discount migration, legacy mapping

- includes/download-functions.php
- tests/downloads/tests-download-functions.php
Fixes #9226
1. If `edd_get_download` does not return a download object, return early.
Noting two things that seem incorrect about the function:
1. The doc block says that it always returns a string, but it does already return `false` if no download ID is provided. I feel like this could be problematic if the function is used without extra logic. We do things if we can't find a customer, for example, like say "customer missing". Without extra checks on this, the download name could just be empty where its used. Maybe that's fine but we should update the doc block.
2. I think the default price ID parameter should be `null` instead of `0` as that's technically correct for no price ID.
> Return early if download object isn't retrieved

- includes/admin/dashboard-widgets.php
- includes/admin/upgrades/upgrade-functions.php
- includes/class-edd-cli.php
Fixes #9232
1. When the CLI migration is running, display the CLI migration message in the dashboard widget as well, instead of the link to the upgrade screen.
2. Moves the CLI option deletion out of the CLI class and into the `edd_v30_is_migration_complete` function. This runs in the CLI class right before the option was deleted, but this feels a little safer in that the option will be handled outside of the CLI, in case it fails to delete somehow there.
> Update dashboard widgets message when CLI migration is running

- includes/admin/payments/class-payments-table.php
- includes/database/engine/class-query.php
- includes/database/queries/class-order.php
- includes/payments/class-edd-payment.php
Fixes #9239
1. Removes the fallback calculations for IP and payment key from the EDD_Payment class.
2. Extends the BerlinDB `add_item` method for orders and makes sure that every order has an IP, purchase key, and currency set when added to the database.
This needs to be tested with anything which manipulates/saves payments. Specifically, off the top of my head:
> Move payment property assignments to order queries class

- includes/admin/settings/display-settings.php
Fixes #9225
The break occurred in the PR for #9001, when `edd_get_settings_tabs` was refactored to be less expensive. That function checked if the licensing/extensions tabs were empty of settings and removed them if they were.
In its place, the `edd_options_page` function was updated to handle that check, but it checked all tabs, not just licensing and extensions, which is what broke settings added using the settings API, since the settings are registered differently than EDD core settings, I think.
This PR adjusts the check to only check the licensing and extensions tabs, which is more in line with the original code, and the sample tab/section now displays for me.
> Only unset licensing/extensions settings tabs if empty

- includes/admin/customers/customer-actions.php
- includes/class-edd-customer.php
- tests/customers/tests-customers.php
Fixes #9254
When user is adding an additional customer email in the admin, the JS will refresh the page as per `response.redirect` parameter from the backend. It will work the first time because the URL of the page will change, but the page reload will stop working for any subsequent new emails, because the URL of the second refresh has not changed. If `window.location.href` is the same as the current page (with the # paramater), the page will not reload.
- Added a unique parameter to each redirect response with the customer email ID, so that JS will always reliably reload the page
- Changed the `add_email` function inside `EDD_Customer` to return ID instead of boolean
> Fixes adding more than one additional customer email in admin

- includes/admin/reporting/export/class-batch-export-file-downloads.php
- includes/admin/reporting/export/class-batch-export-taxed-orders.php
Fixes #9165
Proposed change:
- The field `date_created` is ambiguous when you export taxed orders while selecting date filter + country filter. I have made a change inside `class-batch-export-taxed-orders.php` so that Berlin will append the table alias to the `date_created` field.
> Fixed ambiguous date_created column inside taxed orders reports

- includes/admin/notes/note-actions.php
- includes/admin/notes/note-functions.php
Fixes #9293
- We should allow adding notes for a role that can`edit_shop_payments`. If a role is allowed to edit payments, they should be allowed to add notes.
> Fixed wrong capability check when adding manual order note

- includes/process-purchase.php
- tests/tests-misc.php
Fixes #9302 
1. Adjusts the RegEx to accept prefixed and non-prefixed postal codes for Sweden.
2. Adds unit test around all 3 cases.
> Fix Swedish postal code validation and add unit tests around just SE postal codes #9302

- includes/template-functions.php
Fixes #9319
1. Updates the strings for outputting "includes/excluding % tax" on a download.
> Update strings to show tax rates on downloads

- easy-digital-downloads.php
- includes/admin/upgrades/upgrade-functions.php
This adds an additional check to the 3.0 upgrade notice, checking for the orders table. If it was not created, an error notice is displayed instead of the upgrade notice. The error shows one of two messages:
1. If the database version doesn't meet the minimum 5.6 they're instructed to contact their host for help with upgrading that.
2. If the database version did meet the minimum then they're instructed to contact our support instead.
> Change the upgrade message if the orders table could not be created

- includes/admin/upgrades/upgrade-functions.php
- includes/install.php
- tests/tests-install.php
Instead of checking the `$wpdb` global for the orders table, this uses the `edd_get_component` function to get the Order component, then the database table, and then the version. If the version is retrieved we can proceed with the upgrade.
> Update table check for upgrade notice

- includes/class-stats.php
Fixes #9325
- Very small calculation change inside `get_order_refund_amount` method. Relative data was a positive number, while total data was negative, therefore causing the wrong percentage change calculation
> Fixed "Total refund amount" relative data percentage calculation

- includes/orders/functions/orders.php
Fixes #9299
- Made changes into `edd_destroy_order` method where I loop through order adjustments, detect if adjustment is the discount, and then call the use count decrease method
> Decrease discount usage count when order is deleted

- includes/database/tables/class-customer-meta.php
- includes/database/tables/class-customers.php
Fixes #9341
1. Creates a private `needs_initial_upgrade` method for both the customers table and the customer meta table to check the tables directly.
2. Runs an additional `delete_option` for the most likely "missing" option but I'm not sure this is necessary--would be nice to have things tidy but it's also two rows.
> Update the initial checks for the customer database upgrades

- includes/admin/reporting/reports.php
Fixes #9337
1. Updates the price ID checks for reporting queries.
2. Updates the sales/earnings overview tiles to set up the parameters when the class is instantiated rather than when calling the individual method.
> Update price ID checks for reports

- includes/reports/reports-functions.php
Fixes #9351
I made sure that `hour_by_hour` variable is defined upfront to avoid cases where it could be undefined.
> Fixed undefined variable in certain cases for reports

- includes/admin/payments/actions.php
Fixes #9311 
1. Checks for a `0` on the order address id
2. If it is `0` we're creating a new order address, so we're removing the empty `order address id` and adding the `order id`
3. If the `order address id` is not `0`, we update it instead.
> Update/Create the order billing address upon saving order. #9311

- includes/compat/class-template.php
Fixes #9354 
1. Adds a transient of `edd-sc-receipt-check` when checking the `shortcode-receipt.php` template file to only run the check once a day.
> Use a transient to only check the shortcode-receipt template once a day #9354

- includes/admin/upgrades/v3/class-data-migrator.php
1. Wait to run `array_filter` on migrated order address data until needed, so that the country/region are always set for checking the tax rate.
> Defer removing empty address data

- includes/class-edd-cache-helper.php
Fixes #9375
1. Removes hooks for discount changes to hook into W3TC
> Removing old W3TC hooks for discounts when they were a post type #9375

- includes/class-stats.php
Fixes #9286
1. We have decided that we will query `Earnings` tile in reports by gross statuses for now.
> Changed Earnings tile in reports to query data by gross statuses

- includes/admin/payments/orders.php
1. When adding a new order on a store where the base country does not have an array of regions stored, so the text input is used instead of the select, adds the necessary `id` attribute for tax rate calculations.
This can be tested by setting your store's base country to a country which does not have regions stored. Norway works. With that set as your base country, set up a tax rate (I don't think the configuration for the rate matters actually) and then attempt to manually create an order which should have a tax rate assigned. In the `main` branch, it will not have a tax rate assigned.
> Set ID on order address region text input

- includes/orders/classes/class-order.php
- includes/orders/functions/items.php
Fixes #9379
I have set the default number of items retrieved to `100` as it feels enough.
> Increased default number of order items retrieved

- includes/reports/reports-functions.php
Fixes #
1. If 'HOUR' is used as the grouping, ensures that we group by 'hour' and 'day' to fix a 2 day hour by hour report.
Two replicate, select a graph that reports hour by hour, like a 2 day span.
With Changes:
Without Changes:
> Hour by Hour graph grouped only by hour, not day

- includes/class-edd-customer.php
- includes/user-functions.php
Fixes #9344 
1. Reverts back to the `edd_customer_post_attach_payment` hook.
2. Adjusted the `EDD_Customer->attach_payment` method to run the hooks even an order is already attached.
This will need testing with and without Auto Register.
> Revert new customer attachment, and improve customer->attach_payment to always run the hooks #9344

- includes/admin/tools/class-edd-tools-recount-store-earnings.php
- includes/admin/tools/class-edd-tools-reset-stats.php
- includes/api/class-edd-api.php
- includes/class-stats.php
- includes/currency/class-money-formatter.php
- includes/formatting.php
- includes/payments/actions.php
- includes/payments/functions.php
- tests/orders/tests-edd-payment.php
- tests/tests-formatting.php
- uninstall.php
Fixes #9361 
1. Many changes but primarily removing calls to `get_sales/earnings_range` function calls in favor of using the stats class.
2. Stop using the old date formatting, and rely on the Store timezone adjusted UTC `date_created` column so the queries are correct when using dates and ranges.
> Update Stats API Endpoint to use proper stats class and date adjustments #9361

- includes/admin/settings/register-settings.php
- includes/misc-functions.php
Fixes #7098
Fixes #6712 
1. Adds support for the `EDD_TEST_MODE` constant.
2. If `true` is the value, puts the store in test mode, disables the setting and always returns `true` for calls to `edd_is_test_mode()` and `edd_get_option( 'test_mode' )`
3. Adds a new `edd_is_test_mode_forced()` which uses the constant and the filter `edd_is_test_mode` (when using `__return_true`) to determine if we're forcing test mode so we can set the setting to disabled and readonly.
> Allow using a constant EDD_TEST_MODE to force test_mode to true #7098

- includes/admin/tools.php
- includes/template-functions.php
Fixes #7827 
1. Adds new `edd_get_theme_edd_templates` function, that finds any directories and files in the parent and child theme that are in the `edd_templates` directory and returns them as an array.
2. Adds the results of `edd_get_theme_edd_templates` to the system info.
> Show any edd_template files copied to the theme for possible customization #7827

- includes/admin/payments/class-payments-table.php
Fixes #7364
1. When searching the orders table for a discount code which doesn't exist, this sets the `id__in` parameter to a null array, similar to the customer search. This is a bit of a workaround--the customer search works this way because the customer ID is a property on the order, but the discount is not.
> Ensure discounts not found return no orders in admin search

- includes/process-purchase.php
Fixes #9411 
1. Removes the `preg_replace` while sanitizing the username supplied at checkout.
To Test:
1. Enable registration at checkout.
2. Provide the username of "Test User"
3. The ` ` character should be retained and is `Test User`.
As a note the `sanitize_user` function we are calling from WP Core does remove `multiple spaces` so something like `Test  User` will become `Test User`. This is expected and is fine as it follows WP Core standards.
> Do not remove spaces from user logins as they are allowed by WP Core #9411

- includes/logs/api-request-log/functions.php
- includes/logs/file-download-log/functions.php
- includes/logs/log/functions.php
- tests/tests-logging.php
Fixes #8450 
1. Adds 3 new filters to disable logging
`edd_should_log_{$data['object_type']}`
`edd_should_log_file_download`
`edd_should_log_api_request`
Example filters:
```
// Disabling an entry in the generic logs table. Replace {gateway_error} with the `object_type` being logged.
add_filter( 'edd_should_log_gateway_error', '__return_false' );
// Specific log type disabling.
add_filter( 'edd_should_log_file_download', '__return_false' );
add_filter( 'edd_should_log_api_request', '__return_false' );
```
> Adding filters that can allow disabling logging #8450

- includes/checkout/template.php
Fixes #9408
1. Adds `autocomplete="off"` to the gateway selector inputs, to avoid a refresh in Firefox putting the checkout in an unrecoverable state.
Steps to reproduce and test:
1. Use Firefox
2. Have a store with multiple gateways active.
3. Add a product to the cart.
4. Select the non-default gateway
5. Refresh the page (with ctrl+r, F5, or the refresh button - depending on your OS)
6. Replicate and Verify Fix
6a. On `main` branch, notice that the default gateway fields are shown, but the radio is still set to the 'selected' gateway from before the refresh.
6b. On `issue/9408` notice that both the radio selector and the payment gateway fields have reset to the default state of the checkout.
> Set autocomplete to 'off' on gateway selector so Firefox recovers from page refresh #9408

- includes/admin/customers/customer-actions.php
Fixes #9420 
1. Swaps the delete customer action to use `destroy` functions instead.
> Destroy order and customer when deleting a customer #9420

- includes/admin/settings/register-settings.php
Fixes #9432
1. Sets the number of tax rates to retrieve for the settings callback to `9999`.
> Get a large number of tax rates for the settings screen

- includes/admin/downloads/metabox.php
Fixes #8215 
1. Removes deprecated hooks/filters/code from when we moved the advanced price options into a toggle.
> Remove deprecated backwards compatibility code for advanced price options #8215

- includes/class-edd-logging.php
- tests/tests-logging.php
Fixes #9313
1. Creates a private method `get_object_id_column_name_for_type` to get the correct "object ID" column for a given log type:
- 'object_id` as a default
- `product_id` for file downloads
- `user_id` for API requests ... not sure on this one as it looks like API requests never assigned a post parent to that log type, so I'm not sure there was a way to actually query API logs in this manner. But user ID seemed like a reasonable option and object ID is certainly invalid.
2. Updates `get_log_count`, `delete_logs`, and `parse_args` methods to use the new helper method.
3. Adds a unit test to add a file download log and count it using the original `get_log_count` method.
You can test by generating some file download logs (CLI command: `wp edd download_logs create …
> Update object ID column for EDD logging class

- includes/orders/functions/orders.php
- includes/payments/class-edd-payment.php
- tests/orders/tests-edd-payment.php
Fixes #9157
1. Updates the `EDD_Payment` class to allow added downloads to set or inherit the order/payment status (this covers adding a payment and saving it directly as `complete` instead of as `pending` first).
2. Updates `edd_build_order` to account for missing/incomplete data.
> Update payment methods for incomplete data

- includes/class-edd-cli.php
- includes/payments/class-edd-payment.php
Fixes #9157
1. Updates the payment class and the CLI functionality to use `edd_get_download_name()` to record the product name.
> Update download name when adding as a payment

- includes/emails/email-summary/edd-email-summary-template.php
Responsive improvements for Email Summaries.
Made mobile fonts bigger and put `<style>` into `<head>` so that email clients are not stripping the CSS out of email.
> Responsive fixes for email summary

- includes/admin/reporting/reports.php
- includes/class-stats.php
- includes/models/Download.php
- tests/orders/tests-stats.php
- tests/phpunit/factories/class-edd-factory-for-orders.php
Fixes #9424
1. Updates the net sales/earnings calculations method in the download model to query order items that are complete, refunded, and partially refunded, and to use gross order statuses for calculating earnings.
2. Updates the stats class for querying order items to always do an inner join to the orders table, because we need to know what type and status the order has. So the count now gets complete/partially refunded counts for orders of the type sale which are also complete/partially refunded. _Reminder that the stats count is counting rows and the download model is doing quantities._
3. Fixes the order factory for unit tests to set a correct order item status.
4. Updates the stats tests to expect the correct number of order items.
> Update download sales/earning calculations

- includes/api/class-edd-api.php
Fixes #9435
- I have improved how the date range is looped over in the Stats API. Current integration had a `while` loop that could get stuck in certain situations. I have replaced the logic with Carbon methods. 
- Database is now using UTC converted dates and dates returned in the array are in a localized format.
- Documented code a little better.
> Improved looping through date range in the Stats API

- includes/admin/add-ons.php
- includes/admin/admin-bar.php
- includes/admin/discounts/contextual-help.php
- includes/admin/downloads/contextual-help.php
- includes/admin/downloads/metabox.php
- includes/admin/extensions/abstract-extension.php
- includes/admin/payments/contextual-help.php
- includes/admin/promos/notices/class-license-upgrade-notice.php
- includes/admin/reporting/contextual-help.php
- includes/admin/settings/contextual-help.php
- includes/admin/settings/display-settings.php
- includes/deprecated-functions.php
- includes/misc-functions.php
- readme.txt
This removes strings and logic around old promotional layouts. We should remove any translatable text we don't need any more so we can help translators out a bit.
> Cleanup product education and remove old promo strings

- includes/admin/downloads/metabox.php
- tests/downloads/tests-downloads.php
- tests/helpers/class-helper-download.php
Fixes #9343 
1. Adds a metabox save sanitization so that we ensure that we also re-index the bundle file conditions array as well.
> When saving  the bundle product conditions, ensure that the array keys are re-indexed, starting at 1 #9343

- includes/admin/downloads/metabox.php
Fixes #9343
1. Updates the bundled products and bundled product conditions to not use array_combine if the array is empty.
Note that the conditions are always going to have one array key/value, even for a download that's not a bundle, because the form is just hidden (so it's still submitted and the default is `all`). That feels a little wonky but it's how it's been forever.
> Update bundled product validation

- includes/emails/email-summary/class-edd-email-summary-cron.php
Small improvement, so that the next Email Summary cron is scheduled immediately after an email has been sent out, instead of waiting for the next `edd_daily_scheduled_events` event to be run.
> Schedule Email Summary event immediately after email is sent out

- includes/admin/tools/class-edd-tools-reset-stats.php
Fixes #9460
1. When resetting the store data, removes the `edd_adjustments` and `edd_adjustmentmeta` tables from the array of tables to reset.
> Skip adjustments, adjustmentmeta when resetting store

- includes/class-edd-cli.php
1. This runs the `maybe_upgrade` routine for the customers and customer meta tables at the beginning of the CLI customer migration, in case the migration is happening without having touched `admin_init`.
> Run maybe_upgrade for customers, customer meta during CLI

- includes/class-edd-download.php
Fixes #9343
1. Updates the `get_variable_priced_bundled_downloads` download method to not revise the bundled conditions array when matching to the bundled products. Also adds a defensive condition to ensure that the product exists.
I encountered this error with release/3.1 and trying to sell a bundled product with licenses. The last product in the bundle did not get a license generated and running the retroactive processor generated this error:
> PHP Warning:  Undefined array key 0 in \plugins\easy-digital-downloads\includes\class-edd-download.php on line 576
> Use price assignment keys as saved when getting bundled downloads

- includes/admin/dashboard-widgets.php
Fixes #9484 
1. Adjusts to use the `edd_get_orders` function instead of payments.
2. Changes uses of `$payment/s` to `$order/s`
3. Appends the order status after the date for clarity of status.
> Switch to get orders calls and respect order currency #9484

- includes/admin/reporting/class-base-logs-list-table.php
- includes/admin/tools.php
Fixes #9498 
1. Changes the `-1` call on the main `Downloads > Tools` page to use the default so we don't query all downloads.
2. Changes the Download Logs to use chosen and use the `30` default. Updates the filtering to accept the selected download.
> Limit the product_dropdown calls on the logs and main tools page to use chosen #9498

- includes/api/class-edd-api.php
- tests/tests-api.php
Fixes #9488 
1. Adds a new 'permalink' item to the product data for the `products` API Endpoint.
2. Adds unit tests for the `link` and `permalink` data endpoints.
> Add a permalink value to the products endpoint #9488

- includes/ajax-functions.php
Fixes #9508
1. Adds a filter on the `WHERE` clause for the ajax downloads search. This restricts the search to run on the download titles only, instead of including the content and excerpt.
> Restrict the ajax downloads search to titles only

- includes/admin/downloads/metabox.php
Fixes #9499
1. Updates the product selector for bundled downloads to include the overall product in addition to each variations.
> Allow entire variable product to be selected for a bundle

- includes/admin/upgrades/v3/class-customer-addresses.php
- includes/admin/upgrades/v3/class-data-migrator.php
- includes/class-edd-cli.php
Fixes #9480
This PR does a couple things:
1. Updates the customer address migration to use `edd_maybe_add_customer_address` to prevent duplicate addresses being added. On a test site, this reduced the number of addresses from 22k to 13.7k.
2. Updates the final query to check/update the address type.
> Update customer address migration

- includes/admin/downloads/metabox.php
- includes/class-edd-html-elements.php
1. Creates a new `get_products` method in the HTML elements class, to allow the products to be retrieved separately from rendering the product dropdown.
2. Implements the new method for the download metabox for bundled products.
> Separate product query for dropdowns

- includes/post-types.php
Related: https://github.com/awesomemotive/edd-fes/issues/1678
This just moves the closing `)` to where it should be in the empty check for the REST user query.
> Fix empty check for REST user query

- includes/widgets.php
Fixes #9533
1. Updates the checkbox setting validation for the legacy cart widget to use an `empty` check instead of `isset`.
> Update legacy cart widget instance validation

- includes/admin/payments/class-payments-table.php
Fixes #9548 
1. Runs the search query through `str_replace` to remove the `#` character for `product_id` searches, and then runs `trim` and `invtal`
> When searching orders by product ID, remove the hash before running intval #9548

- templates/history-downloads.php
- templates/history-purchases.php
Fixes #9556 
1. Removes `trash` orders from the Order History shortcode.
2. Removes `trash, refunded, abandoned` orders from the Download History shortcode.
3. Fixes pagination for Download history to also use the same statuses.
> Remove trashed orders from order history, and abandoned/trashed/refunded orders from download history #9556

- includes/admin/upgrades/v3/class-data-migrator.php
- includes/class-edd-cli.php
- includes/discount-functions.php
Fixes #9531
1. This updates the `discounts` method in the data migrator class to explicitly check any post meta with the `_edd_discount` prefix against the core meta/properties for discounts.
2. If existing meta is not a core property, it should be added to the new discount object's metadata.
To Test:
This could be tested by using the gist linked in the original issue to add some custom meta to a discount for handling discounts on subscriptions.
1. Create the discount in EDD 2.11, making sure that the custom meta is saved to the discount.
2. Migrate the discount to EDD 3.0. In the main branch, that custom meta will be lost; in this branch, it should persist (whether the linked code works in 3.0 is a separate issue as I think it uses some post functions which may not be …
> Update discount migration to allow for custom metadata

- includes/admin/reporting/export/class-batch-export-payments.php
- includes/admin/reporting/export/class-batch-export-taxed-orders.php
Fixes #9569 
I have excluded `trash` status from order query.
> Exclude trashed orders from exports

- includes/class-edd-download.php
Fixes #9542
1. Updates the `$download->can_purchase` check to check post status before capability.
> Revise can_purchase check for unpublished downloads

- includes/process-download.php
1. Updates our `edd_is_local_file` to also check the `home_url` if it is different than the `site_url`
2. Adds a filter allowing custom installations to still report this as local.
In 2.11.7 and lower, we used `home_url` as the basis for determining if a file was local. in 3.0+ we switched this to `site_url`. The problem with this is that in some custom setups, these are different and the content might not be in the same path as the WordPress installation.
> Improve local file detection

- includes/discount-functions.php
Fixes #9443 
1. Adds a default `$i_amount` to `0`
2. Adds checks for the `options` array key, else the `item_number - options` array keys.
> Add fallback to item_number and set a default i_amount #9443

- includes/orders/functions/orders.php
- tests/orders/tests-edd-payment.php
Fixes #9570
1. Removes the user info/email check from `edd_build_order`.
2. Adds an early return if no order ID was found or the order was not successfully added.
> Update early return in edd_build_order

- includes/emails/template.php
- includes/shortcodes.php
Fixes #9414
1. Updates the `edd_receipt_shortcode` parameters to include a redirect attribute, set to the `edd_get_current_page_url()` by default.
2. Updates `edd_render_receipt_in_browser()`:
* To use the `$data` parameter provided by the EDD hook.
* To return early if the login submission is detected so that the `edd_post_actions` will take precedence instead.
* To add the payment ID/EDD action to a URL to add to the shortcode as a custom redirect since this is not part of the `$wp->request`.
> Update receipt link email tag rendering

- SUPPORT.md
- easy-digital-downloads.php
- includes/admin/class-edd-notices.php
- includes/admin/downloads/contextual-help.php
- includes/admin/reporting/export/class-batch-export-payments.php
- includes/admin/reporting/export/class-batch-export-taxed-orders.php
- includes/admin/settings/register-settings.php
- includes/admin/tools.php
- includes/class-easy-digital-downloads.php
- includes/database/README.md
- includes/gateways/paypal-standard.php
- includes/gateways/paypal/admin/connect.php
- includes/gateways/paypal/admin/notices.php
- includes/gateways/paypal/admin/settings.php
- includes/gateways/paypal/class-paypal-api.php
- includes/gateways/paypal/ipn.php
- includes/process-purchase.php
- includes/users/login.php
- languages/easy-digital-downloads.pot
- readme.md
- readme.txt
- src/Downloads/Search.php
- tests/tests-login-register.php
* Improvement: Have the PayPal IPN backup include the order date in the information sent to Recurring.
* Improvement: Further improve the AJAX download search.
* Fix: Further work to create specific user-agent to send in PayPal requests to avoid 403/400 errors.
* Fix: Some plugins could conflict with the login URL filter to customize the login page.
* Fix: It is now possible to deselect a page in the settings after it's been set.
* Fix: All documentation links have been updated to use the new locations.
* Fix: Some passwords could not be validated when using the login form on the checkout page.
* Fix: The orders export did not allow only orders with a specific status to be exported.
> Adding EDD 3.1.0.6

- CONTRIBUTING.md
It looks like the `master` branch is abandoned as it hasn't been updated in years.
All the development is done in `main` now, so let the CONTRIBUTING.md mention the `main` branch.
> Update CONTRIBUTING.md with correct branch name

- easy-digital-downloads.php
- includes/class-easy-digital-downloads.php
- includes/process-purchase.php
- languages/easy-digital-downloads.pot
- readme.txt
- src/Sessions/PurchaseData.php
- tests/sessions/tests-purchase-data.php
Changelog:
* Checkout: Fixed a user's first/last name not saving to their WordPress account when registering during checkout.
* Checkout: Fixed purchase data being sent to some gateways which process credit cards from form data.
> Release 3.3.5.2
