includes/shortcodes.php
=> Don't output schema in downloads shortcode

assets/js/jquery.creditCardValidator.js
=> Remove CC header

includes/admin/reporting/graphing.php
=> Fixing custom report dates Dec 1 - Jan 31

includes/ajax-functions.php, includes/template-functions.php, tests/tests-shortcodes.php
Found another area where the Microdata was outputting, and then also fixed up some unit tests, as well as a test marked incomplete that is working now. Addresses #2777
=> Tests and additional Microdata checks

includes/shortcodes.php
Fixes issue #2783... I overcomplicated the CRAP out of that!
=> Add error check for invalid email in profile editor

includes/shortcodes.php
=> Revert "Add error check for invalid email in profile editor"

easy-digital-downloads.php, includes/admin/reporting/graphing.php
This is my first fork and merge request on github so forgive me if I've done this wrong. 
I'm wanting to create a hook that will let 3rd party developers perform additional calculations and echo the data under the earnings report graph; so am proposing new action hook called edd_reports_graph_additional_stats.
The appended arrays: dates, sales_data and earnings_data looks valuable for hook considerations. For example I could use $earnings_data and $sales_data to compute an estimated transaction fees paid for the given time and then echo the data into the report.
I am not sure how to docblock action hooks or I would have given it a try. Hope I'm submitting this the right way.
=> First merge request - Adding an action hook to the earnings report.

includes/shortcodes.php
=> Add check for invalid email in profile editor. Props @ghost1227. Fixes #2783

includes/shortcodes.php, templates/history-purchases.php
Issue #2037
Here's a few new actions and filters.
=> Additional actions and filters on downloads/purchase history shortcodes

assets/js/edd-checkout-global.js
=> Don't nest cart checkout forms when changing taxes

assets/js/edd-checkout-global.js
Addresses #2900 for cross browser compatibility.
=> Replacement of cart when taxes change, correctly.

includes/process-purchase.php
Addresses #2895. Will only apply if no discounts are on the cart OR multiple discounts are allowed.
=> Honor posted discounts when Apply isn't clicked

tests/tests-downloads.php
Adds onto #2918 by adding a check for getting a download by name.
=> Adding unit tests

includes/template-functions.php
=> Hide the 'Add to Cart' button on refresh for non-multi select variable price

includes/shortcodes.php
=> Fixing [downloads] pagination with default permalinks

includes/admin/downloads/metabox.php
=> Allow 0 to be the default price id

assets/js/edd-ajax.js
=> Correct cart count on widget when multiple price ids added

includes/emails/class-edd-email-tags.php
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/2930
=> Add {ip_address} email tag

includes/payments/functions.php
=> Set post_date_gmt from post_date if a date is supplied.

includes/class-edd-html-elements.php, tests/tests-html-elements.php
=> Make year_dropdown HTML element more flexible

templates/shortcode-profile-editor.php
=> Make profile editor template hookable

tests/tests-login-register.php
Hey,
Added unit tests for login-register.php file.
What do you guys think about checking both key and value?
https://github.com/JeroenSormani/Easy-Digital-Downloads/compare/login-register-tests?expand=1#diff-cbfadbcd384a876a9592f7dbb353c0e3R37
Cheers,
Jeroen
=> Login register tests

assets/js/edd-ajax.js, includes/scripts.php
=> Re-Show quantities if removed from cart

includes/country-functions.php
=> Add ALL the states!

includes/admin/reporting/class-sales-logs-list-table.php, includes/class-edd-download.php, includes/download-functions.php, includes/payments/actions.php, includes/payments/functions.php, tests/tests-downloads.php
=> Corrects issues in log descrepencies

includes/country-functions.php
Corrected 3 state names & added a new state for India.
=> Corrections in names of Indian states.

includes/admin/downloads/contextual-help.php
=> Inline Docs for edd_downloads_contextual_help

includes/admin/tracking.php, includes/gateways/paypal-standard.php
=> Converting calls to HTTP/1.1

includes/admin/payments/actions.php
=> Use existing functions to determine total earnings

tests/tests-install.php
Hey,
Adding tests for `includes/install.php`
Almost 100% testing the file, just not two lines; http://cl.ly/image/1t3F242Y0L08
I can't think of a way to test this, you guys have an idea?
Cheers,
Jeroen
=> Add install tests

includes/class-edd-session.php
=> Add a prefix to session index if on multisite. #2951

includes/country-functions.php, tests/tests-misc.php
Resolves duplicate keys as reported in #2971
=> Remove duplicate key in countries

includes/checkout/template.php
Not all of them, but a few. More to come soon!
=> A few action hook docs in template.php

includes/shortcodes.php
=> Fix [downloads] to work with multiple categories

includes/scripts.php
=> Filters to fix #2990

tests/tests-theme-compatibility.php
A clean Pull Request in favor of https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/2995
=> Tests themecompat

includes/checkout/functions.php
=> HTTPS restrictions for FORCE_SSL_LOGIN

includes/admin/reporting/graphing.php
=> Force Reports 'This Month' to look at this year

templates/shortcode-receipt.php
=> Bad Pippin. No double semi-colon for you!

includes/admin/reporting/class-export.php
=> revert to , for CSV and escape

tests/tests-query-filters.php
Hey :smile_cat: 
Unit tests for the query-filter.php file, covers it 100% :smile: 
Found this (nice?) construction to test the wp_die function https://github.com/JeroenSormani/Easy-Digital-Downloads/compare/easydigitaldownloads:master...JeroenSormani:query-filter-tests?expand=1#diff-64cd20412ba2e7f38a137e8500112304R233
Let me know what you guys think about that...
Cheers!
Jeroen
=> Query filter tests

assets/js/admin-scripts.js, includes/scripts.php
=> Remove notice on removing last file

includes/post-types.php, tests/tests-filters.php
=> Add bulk updated messages

.travis.yml
=> Slack Integration and used travis cli to generate yml

includes/admin/upgrades/upgrade-functions.php
=> Fixes for 2.2.6 upgrade routine

includes/payments/functions.php
=> Add check for $payment_data['cart_details']

includes/process-download.php
=> Add Content-Length header for #2983

includes/admin/payments/actions.php, includes/emails/actions.php
=> Correct capability check for editing payments. #3045

tests/tests-emails.php
=> Unit tests for #2817

assets/css/edd-admin.css
=> Middle vertical-align edd_repeatable_row

includes/process-purchase.php
Only add the posted discount if it's valid, as the setting of the discount does not verify this. #3057
=> Only apply a posted discount if it's valid

includes/EDD_SL_Plugin_Updater.php, includes/admin/class-edd-heartbeat.php, includes/class-edd-cache-helper.php, includes/class-edd-db.php, includes/class-edd-download.php, includes/class-edd-license-handler.php, includes/class-edd-roles.php, includes/class-edd-stats.php, includes/gateways/manual.php, includes/gateways/paypal-standard.php, includes/libraries/array2xml.php, includes/libraries/browser.php, includes/libraries/class-recursive-arrayaccess.php, includes/libraries/class-wp-session.php, includes/libraries/fpdf/edd_pdf.php, includes/libraries/fpdf/fpdf.php, includes/libraries/wp-session.php, includes/payments/class-payment-stats.php, includes/payments/class-payments-query.php
Hey guys,
Noticed some files were missing a check so added it to all missing...
Cheers!
Jeroen
=> Add abspath security check

assets/js/edd-ajax.js, includes/class-edd-download.php, includes/template-functions.php
Addresses the concerns of #3068
=> Free items do not go straight_to_gateway

includes/class-edd-cli.php
=> Issue/3061 - Allow customers to be created via WP CLI

includes/admin/settings/register-settings.php
=> Add allow_blank option for rich editor settings fields

includes/admin/customers/customers.php
Addresses further issues on #2548
=> Address Undefined Indexes and only for users

readme.txt
=> Add all languages with greater than 40% translation

includes/checkout/template.php
=> Restrict CVC to max 4 chars

includes/admin/tools.php, includes/checkout/functions.php, tests/tests-checkout.php
=> Add support for banning email domains

includes/admin/downloads/metabox.php, includes/admin/payments/actions.php, includes/admin/reporting/class-api-requests-logs-list-table.php, includes/admin/reporting/class-sales-logs-list-table.php, includes/class-edd-api.php, includes/class-edd-download.php, includes/class-edd-session.php, includes/discount-functions.php, includes/emails/class-edd-emails.php, includes/misc-functions.php, includes/template-functions.php
@chriscct7 requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/easydigitaldownloads/Easy-Digital-Downloads/
=> Scrutinizer Auto-Fixes

includes/admin/admin-pages.php, includes/admin/customers/customer-actions.php, includes/admin/customers/customers.php, includes/class-edd-customer.php, includes/payments/actions.php
Should address any issues in the PR of doom from Scrutinizer. This way they are directly tied to the related issues for tracking.
#2548 and #3018
=> Updates to EDD_Customer and Customer UI

includes/discount-functions.php
Solves #3138 and some broken docblocs
=> edd_get_cart_item_price called with too many arguments

includes/deprecated-functions.php
=> edd_get_cart_subtotal is called with too many arguments

includes/admin/reporting/pdf-reports.php, includes/admin/upgrades/upgrade-functions.php
=> Removes unused function calls

includes/cart/functions.php, includes/cart/template.php, templates/checkout_cart.php
Solves #3136.
Also fix some docblocs and remove a return false that can't be hit (unreachable)
=> Remove unused parameters

includes/admin/downloads/metabox.php, includes/admin/payments/actions.php, includes/admin/tracking.php, includes/class-edd-api.php, includes/class-edd-download.php, includes/class-edd-html-elements.php, includes/class-edd-session.php, includes/emails/class-edd-emails.php, includes/misc-functions.php, includes/payments/functions.php, includes/user-functions.php
=> Docblocs and array declarations

includes/shortcodes.php
=> Make the switch for column_width for the downloads shortcode sane

includes/class-edd-cli.php
=> Fix incorrect data in $purchase_data downloads key

includes/admin/class-edd-notices.php
=> Copyright notice in edd-notices is off

includes/admin/payments/class-payments-table.php, includes/admin/reporting/class-file-downloads-logs-list-table.php, includes/admin/reporting/class-gateway-error-logs-list-table.php, includes/admin/reporting/class-sales-logs-list-table.php
Solves #3125. Also removes some unused function calls
=> Corrects doc blocs for table

includes/admin/discounts/class-discount-codes-table.php, includes/admin/reporting/class-api-requests-logs-list-table.php, includes/admin/reporting/class-gateways-reports-table.php
=> Simplifies column_default function

includes/EDD_SL_Plugin_Updater.php
=> Fixes issues with non-existent keys in SL Plugin Updater. Solves #3122

includes/class-edd-cli.php
=> EDD CLI class fixes

.scrutinizer.yml
=> Upgrade Scrutinizer

includes/template-functions.php
@chriscct7 requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/easydigitaldownloads/Easy-Digital-Downloads/
=> Fixes a docblock in template-functions.php

includes/payments/actions.php
=> Only increase sale / earnings stats when not in test mode. #3101

includes/cart/functions.php
Hey guys,
Just a small PR to add a filter to the checkout price label.
Cheers!
=> add filter for edd_cart_item_price()

includes/class-edd-download.php
=> Issue #2558

includes/discount-functions.php
=> Don't apply discount when only excluded items in cart

includes/class-edd-download.php
Addresses Scrutinizer complaints in #3144
=> Adding default properties of WP_Post for EDD_Download

includes/gateways/paypal-standard.php
=> Pending payment notes for #3170

includes/admin/reporting/class-sales-logs-list-table.php
=> Making sure that the cart item matches the post_parent

includes/admin/upgrades/upgrade-functions.php, includes/payments/actions.php, includes/payments/functions.php, tests/tests-payments.php
=> Fixing taxes to be backwards compatible

assets/js/admin-scripts.js, includes/admin/payments/actions.php, includes/admin/payments/view-order-details.php, includes/admin/reporting/class-sales-logs-list-table.php, includes/class-edd-logging.php
=> Add/Delete sales logs when adding/deleting downloads from payments

includes/admin/settings/register-settings.php, tests/tests-cart.php, tests/tests-checkout.php, tests/tests-formatting.php, tests/tests-misc.php, tests/tests-payments.php, tests/tests-tax.php
=> Adds edd_update_option

assets/css/edd-admin.css, includes/admin/customers/customers.php
=> Add purchased products table

includes/ajax-functions.php
=> Fix bug re: download page dropdowns

includes/class-edd-download.php
=> Fallback check for buy now support

includes/class-edd-api.php
=> Fix undefined notices in PHP 5.4 when dynamically setting sales and earnings. Fixes #2979

assets/css/edd-admin.css, includes/user-functions.php
Fixes some performance issues we found in #3206 through issue #3209.
And a small CSS update for  #3206
=> Fixing performance issues in getting users purchased downloads

includes/template-functions.php, tests/tests-filters.php
=> Fixing schema errors

includes/admin/payments/view-order-details.php, includes/admin/settings/register-settings.php
Issue #2758 
If this doesn't clean up all of it, it at least cleans up enough to make the custom tab bug go away...
=> I THINK this cleans up the last of the select2 merge.

includes/cart/functions.php, tests/tests-cart.php
=> Allowing multiple Price IDs with custom URL

templates/checkout_cart.php
=> Quick fix for #3080

includes/shortcodes.php
=> Properly do exclude_* in [downloads] shortcode

includes/admin/class-edd-notices.php
=> Admin notice for NGINX

includes/admin/customers/customer-actions.php
=> Fix misspelled error ID #3228

tests/tests-tax.php
In favor of https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/3180 this pull request to merge with 2.3
=> Tax tests 2.3

assets/js/admin-scripts.js
=> Option name focus when adding new price.

Gruntfile.js, package.json, readme.md
Added new grunt task 
`grunt checktextdomain`
Cleanup code - update version number
Rename tasks
`grunt tx-push` 
and
`grunt tx-pull`
Add Transifex url
=> More Grunt Luv - grunt checktextdomain

includes/admin/upgrades/upgrade-functions.php, includes/install.php, tests/tests-upgrades.php
addresses concerns for new installs on #3248
=> Mark upgrades as completed upon install

assets/css/edd-admin.css, assets/js/admin-scripts.js, includes/admin/class-edd-notices.php, includes/admin/customers/customer-actions.php, includes/admin/customers/customer-functions.php, includes/admin/customers/customers.php, includes/class-edd-db-customers.php, includes/class-edd-html-elements.php, includes/payments/functions.php
=> Allow deleting a customer

includes/admin/settings/register-settings.php
Hey guys,
I was missing the `$args` argument here. 
Cheers!
=> Add args to settings hook callback

tests/tests-plugin-compatibility.php
Third try :smile: 
Adding 100% tests for plugin-compatibility.php :-)
=> Add tests for plugin-compatibility.php

includes/admin/downloads/dashboard-columns.php, includes/admin/downloads/metabox.php, includes/admin/payments/actions.php, includes/admin/reporting/class-download-reports-table.php, includes/admin/reporting/class-edd-graph.php, includes/admin/reporting/class-file-downloads-logs-list-table.php, includes/admin/reporting/class-sales-logs-list-table.php, includes/admin/reporting/reports.php, includes/admin/settings/display-settings.php, includes/admin/settings/register-settings.php, includes/ajax-functions.php, includes/cart/functions.php, includes/class-edd-api.php, includes/class-edd-html-elements.php, includes/class-edd-license-handler.php, includes/class-edd-session.php, includes/emails/functions.php, includes/payments/class-payments-query.php, includes/payments/functions.php, includes/process-download.php, includes/shortcodes.php, includes/template-functions.php, includes/widgets.php
Finds all mis-formatted array keys and fixes them
$x = $foo['bar']; // correct
$x = $foo[ 'bar' ]; // incorrect
=> Fix all misformatted array spacing and fix them

includes/admin/payments/view-order-details.php, includes/class-edd-html-elements.php
=> Show "No customer" message on View Order Details when customer ID is empty (#3272)

templates/edd.css
=> Add missing space before 'dashicons'. #3271

includes/ajax-functions.php
Pippin's requirement: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/commit/e9cef956d13ba594ca9eea804008929a790977ec
=> Airplane Mode Check: Change version_compare() for method_exists()

includes/download-functions.php
=> Untrailingshashit on home_url

includes/admin/tools.php, includes/download-functions.php
=> Allow clearing of edd_doing_upgrade notice

index.html
Just tidying up the fancy readme.
=> Add git clone command, & PR and zip file links

templates/shortcode-receipt.php
Minor fix to avoid a index not found notice.
=> Checks for discount property to avoid index not found notice.

includes/template-functions.php
Noticed that this line is exactly the same as line 225. :)
=> Dulicate variable declaration; no need for this.

assets/css/edd-admin.css, includes/admin/payments/view-order-details.php
=> Creating css for med-text order details

includes/template-functions.php, tests/tests-templates.php
=> Always populate data-price attribute on edd_get_purchase_link

includes/admin/payments/actions.php, includes/admin/payments/view-order-details.php
=> Remove 'number' and restrict values for editing time on purcahse

includes/admin/reporting/graphing.php
=> Fixing non-day-by-day calculations

includes/libraries/browser.php
See phase 1: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3345
=> Browser.php 2.4 update Phase 1: Cleanup

includes/class-edd-customer.php, tests/tests-customers.php
=> Don't increase stats when payment already in payment_ids

readme.txt
=> Improving Campaign Monitoring on Readme.txt

includes/payments/functions.php
=> Add filter for join clause in edd_count_payments function

includes/discount-functions.php, tests/tests-cart.php
=> Make sure edd_get_cart_item_discounted_amount has proper data needed

includes/admin/settings/register-settings.php, includes/payments/actions.php, includes/payments/functions.php
=> Move Test Mode and Always Increment

includes/payments/functions.php, tests/tests-payments.php
This addresses the concerns in #3367 by reducing the risk of a race condition as well as fully supporting changing the prefix/postfix.
=> Improve sequential order numbers performance

assets/js/admin-scripts.js
=> properly handle repeatable deletion for 'file' list

includes/class-edd-license-handler.php
=> Add support for item_id in EDD_License. #3386

includes/ajax-functions.php
Reverts easydigitaldownloads/Easy-Digital-Downloads#3397
=> Revert "Fix Airplane mode"

readme.md
=> Http to https on Readme.md file

readme.txt
Also might want to https the ones in the main plugin file
=> Links should go to https if they exist

easy-digital-downloads.php
=> https's the links in the main plugin file

includes/shortcodes.php, tests/tests-shortcodes.php
Addresses @SDavisMedia's issues outlined in #3348
=> Only show pagination when there's pagination

includes/class-edd-api.php
Reduces code-reuse and allows a product to be filterable #3407
=> Improve Products endpoint

includes/admin/upgrades/upgrade-functions.php, includes/install.php, tests/tests-api.php, tests/tests-cart.php, tests/tests-checkout.php
=> Set flush_rewrite_rules to use false

includes/admin/customers/customer-actions.php, includes/admin/customers/customers.php
=> Slash protection while editing customer

includes/ajax-functions.php
=> Fix airplane mode

assets/js/admin-scripts.js
=> Fixing global tax rate checkbox

assets/js/admin-scripts.js, includes/scripts.php
=> Don't allow all items to be delted from a payment

assets/css/edd-admin.css, includes/class-edd-html-elements.php, includes/discount-functions.php
=> Improve UI for adding downloads to payments

includes/admin/settings/register-settings.php
=> Grammar tweak

includes/class-edd-db-customers.php, includes/class-edd-db.php, includes/payments/actions.php, includes/payments/class-payment-stats.php
Some improvements as discussed :wink:
=> New improvements

includes/checkout/template.php
=> Fix checkout password labels

includes/admin/tools.php
Issue #3450 Properly handle clearing email field
=> No errors on save please!

includes/checkout/functions.php
=> Fallback for banned email check if no emails are set

includes/class-edd-api.php
=> Fix undefined index errors in API

includes/class-edd-api.php
Reverts easydigitaldownloads/Easy-Digital-Downloads#3443
=> Revert "Fix undefined index errors in API"

includes/admin/downloads/dashboard-columns.php, includes/admin/downloads/metabox.php
=> Move purchase shortcode to publish meta box

assets/js/admin-scripts.js
=> Don't improperly hide and uncheck Symlink File Download option.

includes/admin/welcome.php
=> Pull all contributors

includes/admin/settings/register-settings.php, includes/shortcodes.php, includes/template-functions.php
=> Add setting for Buy Now button text

includes/class-edd-cli.php
Minor fix to sprintf to resolve discrepancy in number of arguments.
=> Correct mismatch of arguments in sprintf

includes/ajax-functions.php, includes/class-edd-db-customers.php, includes/class-edd-db.php, includes/discount-functions.php, tests/tests-customers-db.php
=> Fix single use per user discounts

includes/emails/functions.php
=> Using different filters for the different emails

assets/css/edd-admin.css, includes/admin/reporting/graphing.php, includes/admin/reporting/reports.php, includes/payments/class-payment-stats.php, includes/payments/functions.php, tests/tests-stats.php
=> Allow showing reports excluding taxes

templates/checkout_cart.php
=> Adding hooks around fee rows

includes/gateways/functions.php, includes/gateways/paypal-standard.php, includes/process-purchase.php
=> Pass quantity to the straight to gateway

includes/process-purchase.php
=> better type handling for edd_get_purchse_form_user 

includes/scripts.php
=> Register our styles and scripts #3016

includes/gateways/functions.php
=> Also update subtotal to reflect quantity

assets/js/admin-scripts.js
=> First pass at caching selectors #3100

includes/admin/admin-pages.php
Implements `edd_is_admin` as defined in #2657
Supports new customer management ui and reports page
=> edd_is_admin_page updates see #2657

assets/css/edd-admin.css, assets/js/admin-scripts.js, includes/admin/reporting/class-edd-pie-graph.php
=> Improved legend support

assets/js/edd-ajax.js
=> Remove tax line when no items in cart after removal 

includes/admin/tracking.php
=> Fix tracking is always on even when the user doesn't want it to be

assets/css/edd-admin.css
=> overflow: auto on customer section class

includes/admin/payments/view-order-details.php
=> Fixing 0.00 items added to order

includes/gateways/amazon-payments.php, languages/edd.pot
Translations aren't ready yet, just pushed the new pot on Transifex.
Definitely for 2.4.1
=> Fix typo errors + new pot v2.4

includes/gateways/functions.php
=> Remove duplicate  variable and  loop to resolve #3551

templates/shortcode-login.php
=> Fix for attribute on the username label in shortcode-login.php. #3581.

templates/shortcode-profile-editor.php
=> Fixing invalid markup in profile editor

includes/ajax-functions.php
=> Allow ajax user search results to be filtered

includes/api/class-edd-api.php
=> Restore excerpt field in products endpoint. Resolves #3562

includes/gateways/paypal-standard.php
=> Add first_name and last_name to PayPal. #3590

includes/checkout/template.php, tests/tests-filters.php
=> Change priority of edd_filter_success_page_content to 99999. #3588

includes/admin/upgrades/upgrade-functions.php, includes/misc-functions.php
=> Moving upgrade check functions to non-admin include

includes/gateways/libs/amazon/Client.php, includes/gateways/libs/amazon/HttpCurl.php, includes/gateways/libs/amazon/Interface.php, includes/gateways/libs/amazon/IpnHandler.php, includes/gateways/libs/amazon/ResponseParser.php
=> Adding ABPATH check to Amazon gateway files

includes/admin/settings/register-settings.php, includes/admin/tracking.php
=> Update tracking message to be consistent

includes/cart/actions.php, includes/cart/functions.php
=> Remove item/fee URLs honor checkout and avoid cache 

assets/js/admin-scripts.js
=> Reindex the tax rates after we remove one 

includes/template-functions.php
=> Fix schema when sidebar is called first

includes/admin/reporting/class-sales-logs-list-table.php, includes/admin/tools.php
=> Sales report user column link now accounts for guest user purchases

includes/admin/admin-pages.php
=> Fixed variable typo

includes/admin/payments/class-payments-table.php
=> Use Customer not User on the payment list table.

includes/admin/customers/customers.php
I always want to see the user profile, not just the customer details.
Alternately, other user details like the username would be helpful.
=> Link the User ID to the Edit Profile page

includes/admin/settings/register-settings.php, includes/admin/tracking.php
=> Fix small typo with tracking message

includes/class-edd-db-customers.php
Sometimes, you don't know the email for a customer, but you do know, for example, their user_id
=> Implement exists by any field.

assets/js/admin-scripts.js
Prevents the batch processed export buttons from being clicked more than once by disabling them during export.
=> Disable submit button during batch-processed exports. #3647

includes/admin/dashboard-widgets.php
=> Added two action hooks for extending the Sales Summary dashboard widget

includes/api/class-edd-api.php
Add the product id in the sales api to fetch the product information after calling the sales api.
=> Add the product id in the sales api.

readme.txt
=> Adding @mindctrl and @topher1kenobe to readme

includes/user-functions.php, tests/tests-customers.php
=> Return 0 if we continue to no have a user

includes/admin/payments/actions.php
=> Fire action when deleting item from payment

includes/formatting.php, tests/tests-formatting.php
=> No decimals for HUF currency

includes/class-edd-stats.php, includes/payments/functions.php
=> Make sure it's a date we can parse

includes/gateways/amazon-payments.php
=> Better support for multiple word names on Amazon

includes/discount-functions.php
=> Don't store preset_discount when we're bulk deleting codes

includes/process-purchase.php
Splitted PR from https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/3693
=> Whitespace

assets/js/admin-scripts.js, includes/checkout/template.php
Splitted PR from https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/3693
=> Replace `$('body')` by more efficient `$(document.body)`

includes/class-edd-html-elements.php
Splitted PR from https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/3693
=> match the label 'for' attribute with the input 'id' attribute

includes/gateways/amazon-payments.php
=> Update Amazon connect URLs for DE and UK #3687

includes/admin/tracking.php
See how many people change it from the default "download"
=> Add Download Label to Tracking Data

includes/admin/tools.php, includes/admin/tracking.php
We don't support WordPress <= 3.4
=> Simplify theme checks

templates/shortcode-profile-editor.php
=> Add missing paragraph tag

includes/class-edd-stats.php, includes/payments/functions.php
Reverts easydigitaldownloads/Easy-Digital-Downloads#3684
=> Revert "Make sure it's a date we can parse"

includes/admin/welcome.php
=> update welcome page links and references #3723

includes/cart/functions.php
Would be nice to be able to filter the purchase summary (we need to include certain "fees" in the summary sent to the gateway).
=> Add filter to purchase summary

includes/admin/upload-functions.php
Video file formats should be allowed as well, in case a theme needs those files for showcase
=> .htaccess added filter for file formats

includes/shortcodes.php, tests/tests-shortcodes.php
Added parameter inside the download shortcode that will either display the pagination or not. E.g. [download pagination=yes/no]
=> Parameter added to disable pagination for [download] #3522

includes/post-types.php
=> adjust featured image wording to reflect post type labels #3422

assets/css/edd-admin.css, includes/admin/downloads/metabox.php
=> reformat/redesign Download Stats meta box #3385

assets/js/edd-checkout-global.js
=> Fix changing quantity in a custom cart

includes/user-functions.php
=> Fix bug in Purchased Downloads table with purchases without downloads

assets/css/edd-admin.css, assets/js/admin-scripts.js, includes/admin/reporting/export/class-batch-export-payments.php, includes/admin/reporting/export/class-batch-export.php, includes/admin/reporting/export/export-functions.php, includes/payments/functions.php
=> Unwritable and empty file check for batch exporter class

includes/api/class-edd-api.php
=> Move api off template_redirect

includes/api/class-edd-api.php
=> Clean merge for moving api to 'wp' hook props @ghost1227

includes/checkout/template.php
=> display checkout CC dates 30 years out #3779

includes/api/class-edd-api.php
=> Account for -1 as user_id on customer

includes/checkout/template.php, templates/shortcode-receipt.php
=> Add  to edd_receipt_show_download_files. #3758

includes/misc-functions.php, includes/payments/functions.php, includes/shortcodes.php, tests/helpers/class-helper-payment.php, tests/tests-payments.php
=> Fix receipt visibility issue under certain conditions. 

includes/user-functions.php
=> Updates to new user notifications

includes/cart/functions.php, includes/checkout/functions.php, includes/misc-functions.php, includes/plugin-compatibility.php, tests/tests-misc.php
=> Make url detection more universal and reliable

includes/api/class-edd-api.php
=> Add downloads endpoint to API

includes/misc-functions.php, tests/bootstrap.php, tests/helpers/shims.php
=> Fixing AJAX URL in some cases of Checkout page

includes/payments/functions.php
=> Removed unnecessary 'edd' in get_transient function

assets/js/admin-scripts.js
=> Possibly fix quick edit on All Downloads screen.

includes/admin/tools.php
=> Add update notifications to system info

includes/cart/actions.php
=> Fixing cart quantities with AJAX disabled 

includes/user-functions.php, tests/tests-customers.php
=> Detach user_id from customer when user is deleted 

includes/payments/class-payment-stats.php, includes/payments/functions.php
=> Prefix our stats cache keys and more sane logic for tax queries 

includes/class-edd-session.php, tests/tests-session.php
=> Allowing a constant to avoid setting items in cart cookie 

includes/user-functions.php
=> Set user_id for customer when user account is registered. 

includes/admin/discounts/class-discount-codes-table.php
=> Add sorting discounts by usage counts or expiration 

assets/js/admin-scripts.js
=> Load dashboard widget only when needed

assets/css/edd-admin.css, includes/admin/payments/view-order-details.php
=> Break Word on the payment metaboxes 

templates/edd.css
=> remove space

includes/admin/reporting/export/class-batch-export-payments.php
=> Clean up entities, quantities, and discounted prices 

includes/class-edd-stats.php
Changed 'Last Quater' to 'Last Quarter'
=> #3873 - Fixes typo in includes/class-edd-stats.php#L91

includes/admin/customers/class-customer-table.php
=> Allow searching customers by user_id 

includes/emails/class-edd-emails.php
=> Log email send failures in log file. #3883

includes/template-functions.php
=> Remove unnecessary code

includes/admin/welcome.php
=> refactor and restyle welcome page

readme.txt
=> Add a space between the `installedin`

includes/payments/functions.php
=> only attach to current user ID when processing checkout

includes/cart/functions.php, tests/tests-cart.php
=> Standardize edd_get_cart_contents return value 

includes/admin/downloads/metabox.php
=> Handle default variable price not being set

includes/formatting.php
=> Add inline docs for edd_sanitize_amount() 

assets/js/edd-checkout-global.js
=> Hide the payment method box when 100% discount applied. 

includes/emails/functions.php
=> Fix undefined variable . #3930

readme.txt
=> Set min version to WP 4.0. #3908

includes/template-functions.php
Include display_price in the purchase links $args for filter functions.
Fixes #3849
=> Include display_price in the purchase links $args for filter functions.

includes/admin/add-ons.php, includes/admin/reporting/reports.php, includes/admin/settings/display-settings.php, includes/admin/tools.php, includes/admin/welcome.php
=> #a11y changes for WordPress 4.4 which requires h1 tags

assets/js/admin-scripts.js, includes/admin/reporting/export/class-batch-export-customers.php, includes/admin/reporting/reports.php, includes/ajax-functions.php
=> Add chosen to product drop down and support All Prices in customer export

includes/admin/reporting/graphing.php
=> Issue 3482

templates/shortcode-receipt.php
Resubmitted to release/2.5 - Fixes #3919
=> filter_var and FILTER_VALIDATE_BOOLEAN for shortcode conditional checks

includes/download-functions.php, includes/plugin-compatibility.php, includes/process-download.php
=> Resolve file download errors with translation plugins - Issue 3635

includes/admin/add-ons.php
=> Fixing UTM mixup 

includes/admin/downloads/metabox.php
=> Convert bundled downloads to repeatable

includes/admin/payments/class-payments-table.php, includes/admin/payments/contextual-help.php, includes/payments/class-payments-query.php, includes/payments/functions.php, tests/helpers/class-helper-payment.php, tests/tests-payments.php
=> Allow searching a discount code on payment list table 

includes/admin/welcome.php
=> make EDD about page CSS more specific #3978

includes/admin/reporting/export/class-batch-export-downloads.php, includes/admin/reporting/export/class-batch-export.php, includes/admin/reporting/export/export-actions.php, includes/admin/reporting/reports.php
=> Add batch export UI / class for products - Issue/3985

readme.txt
Simply updating where people go to translate docs.
#3992
=> Change translation link in readme

includes/admin/settings/register-settings.php, includes/checkout/template.php, includes/process-download.php
=> Swap constant for content_url() 

includes/user-functions.php
=> Add plaintext URL to verification email. #3988

assets/js/admin-scripts.js
=> Use ID instead of class for dashboard length check 

includes/gateways/paypal-standard.php
=> Converting to mc_gross for payment_gross (deprecated) 

includes/admin/reporting/graphing.php
=> fix reports graphs spanning a over a month change 

includes/EDD_SL_Plugin_Updater.php, includes/admin/reporting/class-edd-graph.php
My server has been getting bombarded since releasing a version with EDD licensing support. I've included this change in the version of this class packaged with the plugin, but I'd love for it to be in the core. Thank you!
Fix https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3710
=> Fix Multiple API pings per page load

includes/process-download.php
=> Make symlink file downloads work with redirect download method

includes/payments/class-payments-query.php, includes/payments/functions.php
=> Allow pagination of payments searched by download ID 

includes/scripts.php
=> Only load inline-edit-post when not viewing a single item

includes/class-edd-customer.php
=> only update customer stats when payment being deleted is completed 

includes/cart/actions.php, includes/cart/functions.php, tests/tests-cart.php
=> Allow multi select quantities with variable pricing

assets/css/edd-admin.css, includes/admin/settings/display-settings.php, includes/admin/settings/register-settings.php, includes/class-edd-license-handler.php
=> Better license key activations and error messages - Issue/3889

includes/cart/functions.php, includes/discount-functions.php, tests/tests-discounts.php
=> Unit tests for issue/3473

easy-digital-downloads.php, includes/install.php, tests/tests-install.php
=> Better handling of multisite and network-activated EDD 

includes/admin/reporting/graphing.php
=> Better detection of week start and end

uninstall.php
This commit adds
- Better docs
- Long desc in the file header
=> Better Documentation and File Long Description

assets/css/edd-admin.css, includes/admin/settings/display-settings.php, includes/admin/settings/register-settings.php, includes/admin/tools.php, includes/class-edd-license-handler.php, includes/install.php
=> Subsections

includes/payments/class-edd-payment.php
=> Retrieve email from customer if meta is empty - #2667

includes/download-functions.php, includes/payments/class-edd-payment.php, tests/tests-payment-class.php
=> Mark ID as public but prevent ID from being saved - Issue/4060

includes/class-edd-fees.php, includes/payments/class-edd-payment.php, includes/payments/functions.php, tests/helpers/class-helper-payment.php, tests/tests-payment-class.php
=> Fixing fees added via old filter and items now added with per-item price not total amount

includes/admin/customers/customer-functions.php
=> Don't check if user is pending or remove menu items when running ajax - #4077

includes/gateways/paypal-standard.php, includes/payments/functions.php
=> Ensure cart_details is non-empty array before running foreach. #4073

includes/admin/settings/register-settings.php
=> Fix settings sanitize callback for new sections 

readme.txt
* Expanded description to talk about non-physical things like bookings.
* Fixed typo in desc
* Fixed non-ascii character in License Keys section
* Make demo data proper header
* Fixed 404 docs link in FAQ
* Added question where are docs
* Added question are recurring payments supported
* Added question is SSL required
* Added question about importing
* Added question about what themes work
=> WordPress.org docs and FAQ Update

includes/gateways/paypal-standard.php
=> Detect partially and encoded & characters in keys 

includes/payments/class-edd-payment.php
=> Set payment title if only a first name given at checkout. #4131.

includes/class-edd-customer.php
=> Ensure  is a string in get_raw_notes(). Fixes #4126

includes/admin/settings/register-settings.php, includes/class-edd-customer.php
=> Restore Deactivate button on old license keys - Issue/4133

includes/misc-functions.php, includes/payments/class-edd-payment.php
=> Add get_*() methods to EDD_Payment -  #4130

includes/payments/functions.php
=> Type cast payment IDs before strictly comparing them. #4150

includes/payments/functions.php
=> Set status in edd_insert_payment() if one is passed in the array. #4152

includes/payments/class-edd-payment.php, includes/payments/functions.php
=> Allow empty post_title

includes/admin/tools/class-edd-tools-recount-single-customer-stats.php
=> Fix missing second argument for wpdb()->prepare. #4169

includes/cart/actions.php
=> array index check hardening on process add to cart 

includes/payments/functions.php
=> Added logic to ensure that a currency is always associated to a payment

includes/payments/class-edd-payment.php, tests/tests-payment-class.php
=> Allow updating the date on EDD_Payment objects

includes/admin/settings/register-settings.php
=> Better backwards compat for settings subsections 

includes/payments/functions.php
=> Run date_default_timezone_set() at top of edd_insert_payment(). #4178

includes/payments/class-edd-payment.php, includes/payments/functions.php, includes/process-purchase.php
=> Force timezone to be set properly - Issue/4155

includes/payments/class-edd-payment.php, includes/payments/functions.php
=> Remove date_default_timezone_set(). #4178

includes/admin/discounts/add-discount.php
=> remove unused (huge) downloads query on adding discount screen

includes/emails/class-edd-emails.php, includes/payments/class-edd-payment.php, tests/bootstrap.php, tests/tests-payment-class.php
=> Force allowing a date edit in EDD_Payment and fix unit tests 

includes/admin/payments/view-order-details.php
Reverts easydigitaldownloads/Easy-Digital-Downloads#4188
=> Revert "If key not in payment status array then still show the correct payment status selected"

includes/payments/class-edd-payment.php
=> fix typo in `EDD_Payment`

includes/class-edd-license-handler.php
=> Don't show invalid / expired license keys message to non admins - #4204

includes/admin/reporting/reports.php, includes/admin/tools.php
=> Remove paragraph from form

includes/admin/tools.php
=> Add ABSPATH to system info 

includes/admin/payments/actions.php, includes/payments/class-edd-payment.php, tests/helpers/class-helper-download.php, tests/tests-payment-class.php
=> Ensure that proper items are removed with EDD_Payment::remove_download()

includes/emails/actions.php, includes/emails/functions.php
=> Fix notice on sending test purchase receipt & formatting 

includes/payments/class-edd-payment.php, tests/tests-payment-class.php
=> Make sure that user_info isn't serialized in EDD_Payment props: @norcross

includes/admin/upload-functions.php
=> Add .jpeg to protected directory allowed types. #4242.

assets/js/edd-ajax.js
=> Detect current query string in edd_load_gateway function 

includes/post-types.php, tests/tests-html-elements.php, tests/tests-post-type-labels.php, tests/tests-widgets.php
=> Improve category and tag taxonomy labels. #4232.

includes/plugin-compatibility.php
=> Prevent qTranslate-X from breaking download URLs. #4210.

includes/payments/class-edd-payment.php, includes/payments/functions.php
Ref. [#4164 - New feature - Filter for payment's default currency](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/4164).
=> Added new filter for payment's default currency

includes/admin/reporting/graphing.php
=> Use 'm' instead of 'n' for get_weekstartend() base 

includes/shortcodes.php
=> When profile editor changes name, change customer name

includes/payments/functions.php
=> Ensure that no infinite loop happens on 0 earnings stores 

assets/js/admin-scripts.js, includes/admin/class-api-keys-table.php, includes/api/class-edd-api.php
=> Add sanity check to API Key generation form and function 

includes/api/class-edd-api.php
=> Use 40x status correctly #4099

includes/download-functions.php, tests/tests-downloads.php
=> Add edd_price class and ID to price range. #3839

includes/class-edd-stats.php, tests/tests-stats.php
=> Force hour, minute, and second to end of day - #4030

includes/download-functions.php
=> Automatically remove non-permitted query args from the URL - #3981

includes/download-functions.php, includes/payments/class-edd-payment.php
=> Fix date sales logs are recorded when adding a download 

includes/discount-functions.php, includes/payments/actions.php, includes/payments/class-edd-payment.php, tests/tests-discounts.php, tests/tests-payment-class.php
Properly supports an array of discounts as well. #3859
=> Properly handle failed payments when counting discount code usages #3859

includes/admin/settings/register-settings.php, includes/class-edd-html-elements.php, includes/formatting.php
=> Add edd_sanitize_Key to fix broken settings

easy-digital-downloads.php
=> Update @return inline docs for EDD()

easy-digital-downloads.php
=> Update @return inline docs for Easy_Digital_Downloads class

templates/shortcode-receipt.php
=> Only show price ID  if item has variable pricing 

assets/js/admin-scripts.js
=> Use lastKey instead e.which. #4103

includes/download-functions.php
=> Show default price ID in edd_price() if no price ID is specified. #4070

includes/payments/class-edd-payment.php, tests/tests-payment-class.php
=> Allow an override item_price of 0 on EDD_Payment::add_download 

includes/process-download.php
=> Default $file_path to $requested_file -  #4246

includes/shortcodes.php
=> Check for payment key in session first - 4091

includes/process-download.php
=> Use realpath on doc root for nginx

includes/class-edd-download.php, includes/download-functions.php
Not a must-have, but would help the readability of some of my custom EDD filters.
=> Add download name helper function.

includes/class-edd-cache-helper.php, uninstall.php
=> Delete all transients on uninstall 

includes/admin/dashboard-widgets.php
=> Format sales counts uniformly 

includes/admin/payments/view-order-details.php
=> Only show hyphen if item has variable pricing

includes/ajax-functions.php
=> Harden the check for no_bundles in ajax download search

includes/admin/payments/actions.php, includes/ajax-functions.php
After #4249 the page to view customers is accessible. However the AJAX search however is broken. This PR fixes that.
=> Add filter for user AJAX search

includes/checkout/template.php
=> Default text state for logged in user with a state 

includes/checkout/functions.php, includes/deprecated-functions.php, includes/misc-functions.php
=> Deprecate edd_get_success_page_url()

includes/admin/class-edd-notices.php
=> Fix logic for dismissing checkout page missing 

includes/admin/welcome.php
=> Move submenu removing to earlier to avoid menu customizers 

includes/class-edd-html-elements.php, tests/tests-html-elements.php
=> Add a none item to discounts dropdown 

includes/user-functions.php
=> Use EDD_Emails class for new user emails

includes/admin/settings/display-settings.php
...to the first non-empty section #4211
=> Remove the main section if there are no settings registered and default

includes/admin/reporting/graphing.php
=> Fix day_by_day being incorrectly set on reports

includes/admin/reporting/export/class-batch-export-payments.php, includes/class-edd-stats.php
=> Date fixes for ranges

includes/admin/payments/class-payments-table.php
=> Fix counts for user serach in payment history list table 

includes/payments/class-edd-payment.php, tests/tests-payment-class.php
=> Fix Complete->Pending transition to alter stats and logs 

includes/cart/functions.php
=> Fix quantity opperand issue with multi-price 

includes/shortcodes.php
=> Set a default redirect for login and register to the purchase_history

includes/shortcodes.php
=> Allow ordering by post__in in the [downloads] shortcode.

includes/admin/class-api-keys-table.php
=> Overwrite display_tablenav() for API keys table to force bulk actions to show - #4417

includes/emails/template.php
=> Solves #4419 by defaulting edd_email_preview_template_tags to default gateway

includes/emails/class-edd-emails.php, includes/emails/template.php
=> add in filter to make wpautop optional per #4418

includes/class-edd-session.php, tests/tests-session.php
Includes edd_session_start_uri_blacklist filter and edd_start_session filter to provide ways to disable session starts. #4429 #4428
=> Introduce should_start_session(). Issues 4428 and 4429

includes/class-edd-logging.php, includes/payments/class-payment-stats.php
=> Fix download specific reports 

includes/widgets.php
=> Unset download_id on details widget when 'current' is selected 

assets/css/edd-admin.css, includes/admin/customers/customers.php
Also change HTML semantics, now links are inside LI element.
=> Set focus on icons in Customer details page

includes/admin/add-ons.php, includes/admin/customers/customers.php, includes/admin/dashboard-widgets.php, includes/admin/payments/view-order-details.php, includes/admin/reporting/class-api-requests-logs-list-table.php, includes/admin/reporting/class-gateway-error-logs-list-table.php, includes/admin/settings/display-settings.php, includes/admin/settings/register-settings.php, includes/admin/thickbox.php, includes/admin/tools.php, includes/admin/welcome.php, includes/class-edd-html-elements.php, includes/class-edd-license-handler.php, includes/emails/template.php, includes/payments/functions.php, includes/process-purchase.php, templates/shortcode-content-image.php, templates/shortcode-content-title.php, templates/shortcode-login.php
In this PR I tried to locate title attributes from links and remove them.
=> Remove title attributes

includes/discount-functions.php
Was already digging through to get more information on this hook.  Figured I would document it while I was here.  Not familiar with your doc standards, so feel free to do whatever with it.
=> Added docblock for edd_post_insert_discount action

includes/discount-functions.php
Hi;
Minor doc fix for edd_store_discount() which returns a post ID, not bool.
=> Fix return value in docblock for edd_store_discount()

includes/process-download.php
=> Restrict download links to 'published' payments

assets/css/edd-admin.css, assets/js/admin-scripts.js, includes/admin/payments/view-order-details.php
=> Move Resend Receipt and add Delete Payment button Issue/4203

includes/admin/tracking.php
=> Add additional data to EDD Tracking 

templates/shortcode-login.php
=> We can finally login by email in WP 4.5, so update label accordingly.

includes/admin/tracking.php
=> Add server type to the tracking payload 

includes/process-download.php
=> Suppress errors on filesize() call 

includes/payments/class-edd-payment.php
=> Ensure that we get user info from customer if the setup is empty 

includes/user-functions.php
=> Instantiate new instance of EDD_Emails to fix #4516

includes/payments/class-edd-payment.php
=> Remove final declaration from EDD_Payment. #4046

templates/shortcode-profile-editor.php
=> Remove logout on change password notice. #4376

includes/gateways/actions.php
Fixes #4026... Can it really be that simple?
=> Don't error if no gateway is selected!

includes/discount-functions.php
=> Set discounted_price to 0 if discounted amount is less than 0. - #4506

includes/shortcodes.php
=> Add strict type checks to term IDs in [downloads] shortcode - issue/3638

tests/tests-api.php, tests/tests-customers-db.php
Minor cleanup for 2 unit tests
=> Removed unused variables, duplicate array items and fixed typos

assets/js/admin-scripts.js, includes/class-edd-html-elements.php, includes/scripts.php, tests/tests-html-elements.php
=> Better placeholders for product drop downs. #4560

includes/class-edd-download.php
=> Add new actions for Download earnings/sales increase and decrease methods - Issue/3748

includes/admin/add-ons.php, includes/admin/discounts/contextual-help.php, includes/admin/downloads/contextual-help.php, includes/admin/payments/contextual-help.php, includes/admin/reporting/contextual-help.php, includes/admin/settings/contextual-help.php, includes/admin/settings/register-settings.php, includes/admin/tools.php, includes/admin/tracking.php, includes/admin/welcome.php
Some were missing campaign parameters and some had minor issues like pointing to `extensions` instead of `downloads`. resolves #4386 Some new parameter values had to be added so I studied existing ones and made my best guess at what was appropriate. Open to feedback on whether they could be tweaked to enhance analytics data.
=> Updating URLs to EDD site. 

includes/shortcodes.php
=> Disable pagination in [downloads] shortcode if orderby is set to rand issue/3600

includes/payments/functions.php, tests/tests-payments.php
=> Support payment IDs and objects in edd_get_payment_status() - Issue/4041

uninstall.php
=> improve uninstall transient removal performance 

.travis.yml
=> Only use master and release branches for branch builds 

includes/payments/class-edd-payment.php
=> Pull user ID from customer record if _edd_payment_user_id is empty - Issue/4435

easy-digital-downloads.php, includes/class-edd-customer.php, includes/class-edd-db-customer-meta.php, includes/class-edd-db-customers.php, includes/class-edd-db.php, includes/install.php, tests/tests-customer-meta.php, uninstall.php
=> Introduce customer meta table and EDD_Customer meta methods. #4311

assets/css/edd-admin.css
=> First pass at responsive CSS for item cards. #3798

assets/js/edd-ajax.js
=> Disable checkout submit button once clicked. #4194

includes/template-functions.php
=> Introduce edd_add_oembed_price(). #4064

includes/misc-functions.php, tests/tests-misc.php
=> Refactor edd_object_to_array 

templates/history-downloads.php, templates/history-purchases.php, templates/shortcode-receipt.php, tests/tests-shortcodes.php
=> Add edd-table class to front end tables 

includes/api/class-edd-api-v2.php
=> Add SKU to the product info in V2 

includes/gateways/paypal-standard.php
This pr fixes a spelling error
=> Corrects spelling error in edd_get_paypal_redirect

includes/payments/class-payment-stats.php
=> Remove test override and duplicate filters

includes/checkout/template.php
=> Convert cc and cvc fields to show number pad on mobile 

includes/template-functions.php, templates/shortcode-content-excerpt.php, templates/shortcode-content-full.php, templates/shortcode-content-price.php, templates/shortcode-content-title.php, tests/tests-templates.php
=> Only include itemprop and price meta schema if schema is enabled. #4373

includes/admin/upgrades/upgrade-functions.php
=> Introduce edd_do_automatic_upgrades() and edd_v26_upgrades(). #4311

includes/user-functions.php
=> Use EDD()->emails instead of a new instance. #4596

includes/gateways/amazon-payments.php
=> Switch to global vars instead of edd_vars for amazon ajax

includes/payments/class-payment-stats.php
=> Don't substring cache keys in get_earnings #4618

includes/libraries/browser.php
=> Fix error in system status report (Browser class)

includes/admin/tracking.php
=> Do numeric check not boolean check 

includes/cart/functions.php
=> Do not allow taxes to go negative or apply to negative fees - Issue/4632

includes/api/class-edd-api-v2.php
=> Remove id item, and add additional email support 

includes/gateways/paypal-standard.php
=> Update Buy Now purchase processing in PayPal Standard IPN to use EDD_Payment. Should resolve #4650

assets/css/edd-admin.css, assets/js/admin-scripts.js, includes/admin/customers/customers.php, includes/admin/downloads/metabox.php, includes/admin/payments/view-order-details.php, includes/admin/settings/register-settings.php, includes/scripts.php
=> Inline help text in admin and settings api

includes/payments/class-payment-stats.php
=> Add filters into EDD_Payment_Stats::get_earnings method 

includes/admin/customers/customers.php
=> Escape before wp_nonce_url is done 

includes/admin/reporting/graphing.php
=> Fixing missing estimated reports for this_month

includes/admin/tools.php
=> Do not always show Must-Use Plugins section - issue/4690

includes/discount-functions.php, tests/tests-discounts.php
=> Better discount status changes and a cleanup routine

includes/checkout/template.php, templates/checkout_cart.php
Replaces #3706 to merge directly into `release/2.6`
=> Fix (sub)total amount attributes

includes/template-functions.php
Replaces #4648 to fix #4592. Moving into this issue branch to fix a merge conflict and get merged into `release/2.6`. Commit history of @Defrothew is still in tact.
=> Remove comments button for download embeds #4592

includes/admin/settings/register-settings.php
Remove extra period.  
Valud -> value 
#4641
=> Edits to a few tooltips

assets/js/edd-ajax.js, assets/js/edd-checkout-global.js, templates/shortcode-profile-editor.php
=> Make state field select instead of text if possible

assets/js/admin-scripts.js
=> Allow self to show in download search #4711

includes/class-edd-download.php
Mostly replacing a function call which is a workaround to call a property, to just directly call the given property.
=> Small tweaks in EDD_Download

includes/admin/tracking.php, includes/admin/upgrades/upgrade-functions.php
=> Send check in during version updates. #4722

includes/template-functions.php
This change makes an array for the css classes which will be used for the edd_price_options div. It is filterable using "edd_price_options_classes" and sanitized using sanitize_html_class
=> Add "edd_price_options_classes" Filter

easy-digital-downloads.php, includes/admin/tracking.php
=> Resolve tracking not sending Issue/4720

includes/gateways/paypal-standard.php
=> Link transaction IDs to paypal sandbox if payment was made in test mode - issue/4608

includes/process-purchase.php
=> Remove customer ID requirement from checks on existing email #4733

assets/js/edd-checkout-global.js
=> Ensure that Address Line 2 doesn't have the required attr set after AJAX calls. #4645 

includes/download-functions.php
=> Improve inline docs for edd_get_download_file_url() 

includes/EDD_SL_Plugin_Updater.php
=> Update to the latest plugin updater class #4743

includes/admin/settings/register-settings.php, includes/shortcodes.php
=> Issue/4666: Add default page redirect option for [edd_login]

includes/shortcodes.php, tests/tests-templates.php
=> Don't assume the SKU provided returned a download

includes/gateways/paypal-standard.php
=> Do not add negative fees in PayPal Standard. #4770

includes/misc-functions.php, tests/tests-misc.php
addresses #4642, replacing #4643
=> Account for possible CSV list of IPs

includes/shortcodes.php, tests/tests-shortcodes.php
=> Add unit tests for login form #4666

includes/admin/import/class-batch-import-downloads.php
=> Products should map like statuses to publish #4764

includes/admin/import/class-batch-import-downloads.php, includes/admin/import/class-batch-import-payments.php
=> Reformat dates on payments and downloads imported for mysql format #4757

includes/cart/functions.php, includes/class-edd-download.php, includes/download-functions.php, tests/tests-downloads.php
=> Don't allow items in the cart that the user cannot purchase (or are deleted) #4539

phpunit.xml
=> Fix code report not being generated

includes/template-functions.php
- Correct `straght_to_gateway` to `straight_to_gateway`
- Correct  `apped` to `append` - twice
=> Fixes #4786 - Couple of typos in template-functions.php

includes/admin/payments/view-order-details.php
=> Only show entire receipt metabox when payment is complete

templates/edd.css
This will give the tel input the same padding as the other fields.
=> Add css rule to target the new tel input for the padding declaration

includes/admin/import/class-batch-import-downloads.php, includes/admin/import/class-batch-import-payments.php
=> Fix date string to be using leading zeros for month on imports #4795

includes/admin/payments/actions.php
=> Ensure user has correct permissions to delete payments. #4744

includes/admin/import/class-batch-import-downloads.php
=> Apply logic fixes to downloads import as well #4803

includes/checkout/template.php
=> Add filter on checkout labels allowing gateways to append info #4816

includes/login-register.php, templates/shortcode-login.php, tests/tests-login-register.php
=> Remember me option added on login form #4813

includes/class-edd-download.php, tests/tests-downloads.php
=> Do not return prices if variable pricing is disabled #4515

assets/js/edd-ajax.js
=> Fix for display:none to price options

includes/admin/settings/register-settings.php, includes/admin/tracking.php
=> Refactor settings sanitization for programmatically updating settings #4799

bin/install-wp-tests.sh, includes/class-edd-register-meta.php, tests/tests-register-meta.php
=> Update register_meta and don't allow negative prices by default #4807 #4523

includes/admin/import/class-batch-import.php
=> Do not use '/' delimiters if string is URL #4780

includes/shortcodes.php
=> Fix edd_login redirect logic for better fallback #4834

includes/discount-functions.php
=> Fix issues with discounts being marked as inactive during cron #4838

includes/tax-functions.php
=> Add check for card_state in POST when calculating taxes. #4835

includes/EDD_SL_Plugin_Updater.php
=> WIP, current changes for EDD SL updates #4827

readme.txt
=> Update codex link with developer docs link

includes/admin/settings/register-settings.php, includes/admin/thickbox.php, includes/admin/upgrades/upgrade-functions.php, includes/plugin-compatibility.php, includes/shortcodes.php, includes/template-functions.php, languages/easy-digital-downloads.pot, readme.txt
=> Issue/4891 - short code -> shortcode

includes/admin/tools/class-edd-tools-recount-single-customer-stats.php
=> Fixed variable name #4898

includes/tax-functions.php, tests/tests-tax.php
=> Don't do tax calculations on values less than 0 #4875

includes/payments/class-edd-payment.php, includes/payments/functions.php
=> Move Sequential order logic to EDD_Payment #4845

includes/class-edd-fees.php
=> Add actions to fee add and remove #4850

includes/api/class-edd-api-v2.php, includes/api/class-edd-api.php
Fixes #4866 
Pretty sure this doesn't actually belong in master, but there's no release branch for 2.6.7. Mind creating one or otherwise giving me direction?
=> Add filters to API

includes/admin/settings/register-settings.php
=> Catch errors properly and handle bundle license keys #4862

includes/api/class-edd-api-v2.php
=> Set returned data to null if it is empty. #4893

includes/process-download.php
=> Possible fix for windows local file downloads #4844

includes/emails/functions.php
=> run wp_specialchars_decode on the subject line #4853

includes/admin/customers/customer-actions.php, includes/admin/customers/customers.php
=> Allow customers with user to have address fields editable when empty #4777 #3784

includes/admin/tools.php, tests/tests-tools.php
Addresses #4657 and adds a unit test for the system info to make sure it nearly completes.
=> Add PHP Arg Separator to system info #4657

includes/admin/customers/customer-actions.php
=> Support login/email when changing customer user #4739

includes/admin/reporting/export/class-batch-export-payments.php
=> Use EDD_Payment in EDD_Batch_Payments_Export

includes/admin/settings/register-settings.php
=> Add default value of -1 to multicheck, gateway, and payment icon settings fields - issue/4928

readme.txt
=> update donation link #4930

includes/discount-functions.php
=> Disable edd_discount_status_cleanup(). #4932

assets/js/edd-ajax.js, includes/scripts.php
=> Force removal redirect when purchase links are present #4629

includes/payments/class-edd-payment.php, tests/tests-payment-class.php
=> Move payment meta filter to a location where data is maintained #4887

includes/admin/import/import-functions.php
=> Add a few additional mimetypes on CSV detection #4769

tests/tests-misc.php
=> Fixing typo for Philippines in tests

includes/country-functions.php
=> Fixing typo for Philippines

includes/country-functions.php, tests/tests-misc.php
=> Fix spelling of Philippines #4959

includes/payments/functions.php, tests/tests-payments.php
=> Do not try to update a non-existent payment record - Issue/4962

includes/widgets.php
=> Check for display_type existing #4912

assets/js/admin-scripts.js
=> Set data key for select items in repeatable rows

assets/css/edd-admin.css
=> Realign the upload a file text on the input #4975

includes/scripts.php
=> Check for post content prior to running checks on shortcodes #4952

includes/admin/reporting/class-categories-reports-table.php
=> Load psudo-bulk-actions for reports when no categories exist #4890

bin/install-wp-tests.sh
=> Allow a force download of the packages #4984

includes/admin/reporting/export/class-batch-export-payments.php
=> Use ->date for payment date. #4994

includes/payments/class-edd-payment.php
=> Ensure user_info is an array. #4998

includes/download-functions.php
I'm assuming this function is indeed supposed to return something? Lol.
=> edd_get_random_download() now actually returns a value

includes/api/class-edd-api.php
=> Add user_id and customer_id to /sales API response

includes/payments/class-edd-payment.php, tests/tests-payments.php
=> Fix date in payment meta - Issue/4918

assets/js/admin-scripts.js, includes/admin/payments/actions.php, includes/admin/payments/view-order-details.php, includes/payments/class-edd-payment.php
This addresses saving payment address changes on the view order details #4989. It also fixes a small bug  #5020
=> Fixing payment address and AJAX errors on payment details #4989

includes/emails/class-edd-emails.php, includes/user-functions.php
=> Add non-html log in link to new user notification. #5014

includes/ajax-functions.php, includes/class-edd-html-elements.php
=> Add EDD()->html->user_dropdown() method #5034

includes/class-edd-fees.php
=> Do not clear fees from session when status of payment is pending. #4987

includes/class-edd-html-elements.php
=> Add the 'chosen-rtl' class to dropdowns when using an RTL languange.

includes/admin/customers/customer-actions.php, includes/process-purchase.php
=> Lowercase emails before comparing them during checkout. #5030

templates/edd.css, templates/shortcode-profile-editor.php
=> First pass at standardizing the profile editor HTML. #3904

readme.md
=> Remove reference to forums

includes/payments/functions.php
=> Remove doubled email property

includes/api/class-edd-api-v2.php
=> Add missing s in products to fix return of products endpoint. #5057

assets/css/edd-admin.css
=> Bump our tooltips above the admin menu bar #5050

assets/js/admin-scripts.js, includes/admin/payments/view-order-details.php, includes/admin/tools/class-edd-tools-recount-all-stats.php, includes/admin/tools/class-edd-tools-recount-download-stats.php, includes/payments/actions.php, includes/payments/class-edd-payment.php, includes/payments/functions.php
=> Alternative approach to #5000 that affects earnings only

includes/class-edd-html-elements.php
=> Cannot rely on strict checks #3175

assets/js/admin-scripts.js
=> Check if fees exists before checking it's length #5075

includes/admin/settings/register-settings.php
=> Use sprintf for login redirect description

includes/api/class-edd-api.php, includes/class-edd-cli.php
- Add `--user_id` support for `wp edd customers` command
#5029
=> Issue #5029

includes/admin/reporting/export/class-batch-export-file-downloads.php, includes/admin/reporting/reports.php
- Option to choose product in exporting a download history
=> Issue #4964

includes/shortcodes.php
=> Add author attribute to downloads shortcode #4570

includes/payments/class-edd-payment.php
=> Add action when a payment is successfully saved #5068

includes/user-functions.php
=> Add to iOS App button on profile editor #4986

includes/discount-functions.php
=> Add some actions into the discount add/remove functions #5084

assets/js/admin-scripts.js, includes/admin/discounts/add-discount.php, includes/admin/discounts/edit-discount.php
=> Change jQuery toggle() to show/hide to account for DOM parsing lag #5019

includes/admin/reporting/export/class-batch-export-file-downloads.php, includes/admin/reporting/reports.php
=> Allow exporting download logs of specific download ID #4964

includes/api/class-edd-api.php, tests/tests-api.php
=> Bump VERSION to 2. #5059

includes/class-edd-fees.php, tests/tests-fees.php
=> Prevent item fees from being added when item is not in the cart #5004

includes/admin/settings/register-settings.php
=> Add tooltip for item price tax display on checkout. 

includes/admin/thickbox.php, includes/scripts.php, tests/tests-scripts.php
=> Switch thickbox download button to dashicons #5096

easy-digital-downloads.php, readme.txt
=> Change authorship and author URI to EDD

includes/admin/settings/register-settings.php
=> Append image url instead of echo #4917

includes/admin/class-api-keys-table.php
=> Define 'user' column as primary, since no 'id' column exists #5099

assets/js/edd-ajax.js
=> Fix adding to cart with multiple instances of cart widget #3593

includes/cart/functions.php
=> Add hook after cart quantity is updated #5080

includes/admin/tools/class-edd-tools-recount-all-stats.php
=> Set all downloads to 0 sales and earnings on first step of all downloads recount #4488

assets/css/edd-admin.css
=> Prevent tooltip style conflicts

includes/admin/tracking.php
=> Don't call checkin on self, and a filter for our other sites #5094

includes/admin/import/class-batch-import-downloads.php
=> Set file URL during import even if no condition value is available. #5077

includes/admin/customers/customers.php, includes/admin/tools.php
=> add missing class for batch process elements #5128

includes/payments/class-edd-payment.php
=> Move to using local payment meta #5100

includes/gateways/paypal-standard.php
=> Process PayPal refunds off parent_txn_id not custom payment ID #5136

includes/user-functions.php
=> make API key user profile fields readonly #5167

easy-digital-downloads.php, includes/admin/reporting/graphing.php, includes/class-edd-stats.php, includes/payments/class-payment-stats.php, includes/payments/functions.php
=> Move to single transient 

includes/EDD_SL_Plugin_Updater.php, includes/admin/tools.php, includes/class-edd-license-handler.php
=> Add framework for beta support

includes/EDD_SL_Plugin_Updater.php
=> Check if beta isset #5182

includes/admin/discounts/discount-actions.php
=> Save product in/exclusions when first creating a discount code #5145

includes/process-purchase.php
Check if the Customer's Country has been passed in and if it has no states. If the country has no states, remove the requirement for state. Otherwise leave it in.
Addresses: #5169
=> Check if the Customer's Country has no states.

includes/admin/class-edd-notices.php
=> point Test Mode admin notice to Payment Gateways tab #5192

templates/shortcode-profile-editor.php
=> Added edd_profile_editor_before_name action to profile editor

includes/admin/tracking.php
=> issue/5179 - Fix translation issue with sprintf

includes/user-functions.php
=> Update doc for edd_get_users_purchases() and allow array to be passed as $status

includes/payments/class-edd-payment.php
=> Type check to avoid string offset error #5206

includes/admin/reporting/graphing.php
=> Increase day if date does not exist #5155

includes/EDD_SL_Plugin_Updater.php
=> Use cached response in all places we can #5173

includes/admin/reporting/graphing.php
=> Fix earnings query so that it actually runs #5220

includes/admin/downloads/metabox.php
=> issue/5180 - Reword: Mark this product as tax-exempt

includes/admin/downloads/metabox.php
Reverts easydigitaldownloads/easy-digital-downloads#5181
=> Revert "issue/5180 - Reword: Mark this product as tax-exempt"

includes/payments/class-edd-payment.php, tests/tests-payment-class.php
=> Fix payment meta filters from creating a 0 index key #5228

includes/misc-functions.php, tests/tests-misc.php
=> Issue/5230 - Currency Misspelling

readme.txt
Fixing some broken links, updating some that redirect, deleting no longer available addons, adding some new extensions and adding some missing UTM arguments. Resolves #5235
=> Mostly correcting links in the readme.txt

includes/payments/class-edd-payment.php, tests/tests-payment-class.php
=> Allow EDD_Payment to be looked up by Transaction ID #5135

includes/admin/settings/register-settings.php, includes/ajax-functions.php
=> Remove option to disable AJAX. Let hell break loose. #4758

includes/payments/functions.php
=> Fix earnings values being doubled #5242

includes/discount-functions.php
=> Add  parameter to discount helper functions. #5245

includes/template-functions.php
=> Do not show includes / excludes tax rate if product is exclusive of tax - issue/5227

includes/shortcodes.php
=> Register [edd_downloads] shortcode. #3641

includes/admin/reporting/graphing.php
=> Fix This Week and Last Week reports not displaying #5250
