awesomemotive/easy-digital-downloads

includes/admin/tools.php
includes/admin/tracking.php
includes/admin/upgrades/upgrade-functions.php

Remove more uses of $edd_options. #5160

---

includes/cart/template.php

add hooks to checkout cart form element #5272

---

assets/js/edd-ajax.js

[Issue/4423] Fix purchase button in multi-option purchase mode

---

includes/admin/import/class-batch-import-downloads.php

Detect missing users while importing #4824

---

includes/post-types.php

add download-specific label for attributes metabox #5289

---

includes/admin/reporting/class-edd-graph.php
includes/admin/reporting/graphing.php

Set end day to 1 when not in day_by_day mode on reports for the last month - issue/5274

---

includes/admin/tools.php

Show parent theme in System Info when child theme is active #5269

---

tests/bootstrap.php

Stop HTTP Requests during unit tests #5132

---

includes/payments/functions.php
templates/history-downloads.php

Improve performance of edd_get_payment_by() -  Issue/5234

---

includes/payments/class-edd-payment.php

Use logging class to query for sale logs when removing items from a payment - issue/5252

---

includes/cart/functions.php

Account for unset item quantities. #5299

---

includes/process-download.php

Confirm file exists before setting it to $requested_file - #5268

---

includes/EDD_SL_Plugin_Updater.php

Replace transients with options as caching mechanism in EDD_SL_Plugin_Updater - issue/5294

---

includes/process-download.php

Only check edd_check_file_url_head() if not is local file. #5308

---

includes/admin/tools.php

Fix checked check on beta items

---

includes/EDD_SL_Plugin_Updater.php

Update plugin updater to 1.6.8

---

includes/admin/class-edd-notices.php
includes/admin/discounts/add-discount.php
includes/admin/discounts/discount-actions.php
includes/admin/discounts/edit-discount.php

[Issue/4485] - Harden Discount Creation Process

---

templates/shortcode-login.php

Add 'edd-' prefix to the classes on our login form #3854

---

includes/admin/downloads/metabox.php
includes/admin/settings/register-settings.php
includes/gateways/functions.php
tests/tests-gateways.php

Disable buy now text and checkboxes when multiple gateways enabled #3516

---

assets/css/edd-admin.css
includes/admin/customers/customer-functions.php
includes/admin/customers/customers.php

redesign admin card item view

---

assets/js/edd-ajax.js
includes/checkout/template.php
includes/gateways/functions.php
includes/template-functions.php

This is a new PR for #5082 that is cleaner, something in the commit history got mixed up in the previous PR.

Show gateway selector on error #5082 Issue/5082

---

assets/css/edd-admin.css
includes/admin/admin-pages.php
includes/admin/reporting/reports.php
includes/admin/settings/display-settings.php
includes/admin/tools.php

Issue/3795 - Add heading to Settings page

---

templates/history-downloads.php

Look for a numeric price ID, as empty is true for 0 price IDs #4638

---

assets/js/admin-scripts.js
includes/admin/payments/view-order-details.php

Improve customer metabox on view order details #4197

---

includes/process-download.php

Only resort to attachment ID if file is local #4444

---

includes/admin/dashboard-widgets.php

Addresses #5338 and replaces PR #5352 (contained extra commits). Props @sanketio

Fix undefined Index in dashboard widget #5338 issue/5338

---

includes/process-purchase.php

Update South Korean postal code regex #5056 issue/5056

---

includes/admin/payments/view-order-details.php

Link discounts codes to their edit view on #5325 issue/5325

---

includes/admin/reporting/class-export-payments.php
includes/admin/reporting/export/class-batch-export-payments.php
includes/emails/template.php
includes/process-download.php
templates/shortcode-receipt.php
tests/tests-payment-class.php
tests/tests-payments.php
tests/tests-register-meta.php

Change use of get_post_meta to edd_get_payment_meta #4580

---

includes/payments/functions.php

Stop payments notes from affecting comment counts #4493

---

assets/js/edd-ajax.js

Respect filter for individual redirect to cart #4227

---

includes/gateways/amazon-payments.php

If Amazon Payments is not configured, don't allow scripts to load #4542

---

assets/js/edd-ajax.js
includes/cart/template.php
includes/widgets.php
templates/edd.css
tests/tests-widgets.php

Allow hiding of cart widget instances when cart is empty #3305

---

includes/class-edd-discount.php

adjust discount start date error and add context #5387

---

includes/admin/payments/view-order-details.php

Addressing formatting issues of #5325

Make the label pluralized if more than 1 discount was used #5325

---

assets/js/admin-scripts.js
includes/admin/downloads/metabox.php
includes/process-download.php

Support file attachment thumbnails for images #3341

---

assets/js/edd-ajax.js

Fixing misspelling in edd-ajax 'cart-state' #5396

---

includes/process-purchase.php

Don't default to the PayPal gateway for buy now #4981

---

includes/admin/settings/register-settings.php

Add notice if selected gateway was not enabled #3554

---

includes/admin/payments/view-order-details.php
includes/cart/functions.php
includes/gateways/paypal-standard.php
includes/payments/actions.php
includes/payments/class-edd-payment.php
includes/payments/functions.php
includes/post-types.php
templates/history-purchases.php

Complete abandoned and pending payments #2714

---

assets/css/edd-admin.css

Enforce width on card titles

---

includes/gateways/paypal-standard.php

Update PayPal IPN verification endpoint to use ipnpb.paypal.com. #4422

---

includes/class-edd-license-handler.php

Issue/5232 - Add item_id parameter

---

assets/css/edd-admin.css
includes/admin/payments/view-order-details.php

Re-commit of new customer metabox UI #4197

---

includes/cart/class-edd-cart.php

Allow fees to affect cart total #2283

---

includes/EDD_SL_Plugin_Updater.php

Update plugin updater #5425

---

includes/admin/reporting/export/class-batch-export.php

Make file protected instead of private

---

includes/payments/class-edd-payment.php

Make sure we have an array before assuming array #5433

---

includes/admin/reporting/graphing.php

Ensure key exists before checking its value

---

includes/class-edd-fees.php

issue/2283 - Negative fees not working with EDD_Cart

---

includes/payments/class-payment-stats.php

Allow payment statuses to be filtered #1980

---

includes/admin/import/class-batch-import-downloads.php

issue/5447 - Fix featured image not importing

---

includes/admin/import/class-batch-import-downloads.php
includes/class-edd-html-elements.php

issue/5443 - EDD()->html->select doesn't support 0 as selected key

---

includes/admin/settings/register-settings.php

fix support link typo #5460

---

includes/cart/class-edd-cart.php
tests/tests-cart.php

Retrieve all fees during initial cart setup. #5463

---

includes/admin/plugins.php

remove plugin row link to about page. #5466

---

includes/cart/class-edd-cart.php
includes/class-edd-fees.php
tests/tests-cart.php

Fixing merge conflict

---

includes/admin/reporting/export/export-actions.php

https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5465

Set priority of edd_register_batch_exporters to 99

---

includes/admin/reporting/export/export-actions.php

Register the sales export batch process. Fixes #5475

---

includes/payments/class-payments-query.php

Store initial args for use in filters #5477

---

assets/js/admin-scripts.js

show price options after add download select #5483

---

templates/shortcode-login.php
templates/shortcode-profile-editor.php

Issue 5409

---

includes/admin/payments/view-order-details.php
includes/emails/actions.php

use sanitize_email() instead of sanitize_text_field(). Fixes 5482

---

includes/template-functions.php

use aria-label for screen reader text on front end #5495

---

includes/gateways/paypal-standard.php

Only add fees as PayPal line items when download_id is empty. #5505

---

includes/emails/class-edd-email-tags.php
templates/history-downloads.php

fix condition for outputting price option on download history #5504

---

includes/class-edd-db.php

Set ID variable to prevent unintended ID changes 

---

includes/gateways/actions.php

Remove billing fields if no gateway is active

---

includes/admin/import/class-batch-import.php

Quick fix for space bug in filter_var

---

includes/scripts.php

Fix CSS registration version 

---

includes/api/class-edd-api.php

Fix invalid variable

---

includes/error-tracking.php

Add missing add_action for edd_print_errors. Fixes #5537

---

includes/class-edd-discount.php

Issue/5533 and issue/5534

---

includes/emails/class-edd-email-tags.php

https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5500

Add message to email receipts for no downloads

---

includes/user-functions.php

Include actual verification URL in expired token notice. #5519

---

assets/js/admin-scripts.js

issue/5405 - Set the data-key attribute properly when adding new downloads to an order

---

includes/checkout/template.php

Fix user info in checkout form

---

includes/checkout/template.php

Convert payment label to legend #5339

---

includes/checkout/template.php

remove extra purchase form wrap element #5545

---

includes/class-edd-html-elements.php

Fix bug in user_dropdown when selected user isnt in the first load

---

includes/class-edd-html-elements.php

Fix undeclared function bug

---

includes/gateways/amazon-payments.php

Introduce maybe_hide_gateway_select() to resolve Amazon payment methods not showing

---

includes/emails/functions.php

Add template tag support to email header

---

includes/template-functions.php

Issue/5572 - remove edd-page body class

---

templates/edd.css

Issue/5574 - CSS tweaks

---

includes/checkout/template.php

Fix gateway select with ajax disabled 

---

templates/shortcode-profile-editor.php

Readd profile editor markup

---

includes/payments/class-edd-payment.php

Update class property after updating status #5310

---

includes/class-edd-download.php

Return all bundled downloads if conditions do not exist #5567

---

includes/checkout/template.php

Fix case of the placeholder for `First Name` and `Last Name` #5313

---

includes/admin/customers/customers.php

Adding 2 hooks into customer card view #5560

---

includes/checkout/template.php
includes/scripts.php

Add helper function for retrieving purchase label

---

includes/cart/class-edd-cart.php

Display correct price options for `Add to Cart` links #5345

---

includes/cart/class-edd-cart.php
tests/tests-cart.php

Item fee tax is calculated separately. #5549

Exclude fees from item subtotals when setting up tax calculations. issue/5549

---

includes/shortcodes.php

Added hook filter edd_download_inner_class

---

includes/user-functions.php

Ref. https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5511

New action and filter in `edd_has_user_purchased()` function - #5511

---

includes/checkout/template.php
includes/process-purchase.php

Allow log in by email on checkut. #5311

---

includes/class-edd-stats.php

Reset  to  when passed as false. Partial revert of #4988 for #5603

---

includes/country-functions.php
tests/tests-misc.php

Change Czech Republic to Czechia #5581

---

includes/class-edd-html-elements.php

See https://github.com/easydigitaldownloads/edd-fes/issues/1152
#5610

Empty check breaks file assignments for variation price index 0 on old downloads

---

includes/EDD_SL_Plugin_Updater.php

update the plugin updater #5615 issue/5615

---

includes/admin/reporting/class-export-customers.php
includes/admin/reporting/class-export-download-history.php
includes/admin/reporting/class-export-payments.php
includes/admin/reporting/class-export.php
includes/admin/reporting/export/class-batch-export-earnings-report.php
includes/admin/tools.php
includes/admin/tools/class-edd-tools-recount-all-stats.php
includes/admin/tools/class-edd-tools-recount-customer-stats.php
includes/admin/tools/class-edd-tools-recount-download-stats.php
includes/admin/tools/class-edd-tools-recount-single-customer-stats.php
includes/admin/tools/class-edd-tools-recount-store-earnings.php
includes/admin/tools/class-edd-tools-reset-stats.php
includes/admin/upgrades/upgrade-functions.php
includes/class-edd-session.php
includes/process-download.php
tests/tests-tools.php

Remove instances of safe_mode #5625 issue/5625

---

includes/discount-functions.php
tests/tests-cart.php

unset_cart_discount checks all with strtoupper #5634 issue/5634

---

includes/class-edd-discount.php
tests/tests-discounts.php

Uppercase discount codes before comparing in check if discount is used - issue/5642

---

includes/template-functions.php
tests/tests-shortcodes.php

Add filter in place to allow stopping loading of a template #5561 issue/5561

---

includes/admin/reporting/class-edd-graph.php

Graphing improvements #5654

---

templates/shortcode-profile-editor.php

Add hooks to profile editor

---

includes/admin/reporting/graphing.php

issue/5662 - Introduce `Last 30 Days` reporting view

---

includes/payments/class-payments-query.php
tests/helpers/class-helper-payment.php
tests/tests-payments.php

issue/5637 - Fix payment history date filter not working as expected

---

includes/admin/settings/register-settings.php
includes/tax-functions.php
tests/tests-tax.php

Allow tax rates lower than 1% #5635 issue/5635

---

includes/checkout/template.php

Set  to false in edd_receipt_show_download_files() when re-download is disabled - issue/5424

---

includes/admin/import/class-batch-import.php

Do not use / as a delimiter if the string starts with a /. #5620

---

includes/checkout/template.php

Add filter to billing address details on checkout form #5659

---

includes/admin/payments/view-order-details.php

Fix type casting on item tax #5699

---

includes/cart/class-edd-cart.php

Cart tax should be 0 when cart subtotal is 0 #5709

---

includes/admin/tools.php

Add download expiration length to system info #5685

---

includes/admin/settings/register-settings.php
includes/checkout/template.php

Add setting for the text for a free purchase button #5614

---

includes/payments/actions.php

Changed check for payment user ID: empty() to >0

---

includes/process-purchase.php

User 0 instead of -1 for payment user ID #5727

---

includes/admin/tools.php

Issue/5717 – Self-striping admin tables for importers

---

includes/admin/customers/customers.php

Use is_callable instead of function_exists #5687 issue/5687

---

includes/admin/settings/register-settings.php
includes/emails/class-edd-emails.php
includes/emails/template.php
tests/tests-emails.php
tests/tests-filters.php

Issue/5724 and issue/4233

---

includes/payments/class-edd-payment.php

Fallback to date property in setup_completed_date(). #5729

---

assets/js/admin-scripts.js

Target the select element inside of our chosen container and no others - issue/5731

---

includes/admin/settings/register-settings.php

Add link to other gateways in gateway settings list #5736

---

includes/class-edd-html-elements.php
includes/deprecated-functions.php
includes/gateways/paypal-standard.php

Change to using image_url instead of page_style #5291

---

includes/admin/import/class-batch-import-payments.php

Remove _canonical_import_id from customer meta when payment import is complete #5743

---

includes/admin/tools.php

Export/Import the tax rates as well #5673

---

assets/js/admin-scripts.js

don't count the header towards number of rows #5738

---

includes/payments/class-edd-payment.php
tests/tests-payment-class.php

Add delete and add meta methods #5744

---

includes/class-edd-customer.php

Add a raw_notes internal property so we can only get it once and update it when needed #5239

---

includes/process-download.php

Convert fopen to binary mode #5748

---

includes/admin/reporting/graphing.php

Set start day to 1 for quarterly and yearly report views. #5749

---

.travis.yml

Remove HHVM and do multisite testing on PHP 5.6 #5770

---

includes/api/class-edd-api.php
tests/tests-api.php

Branched from #5784 so it could be a clean merge for `release/2.8`. All props @DevinWalker 
1. Fixed `test_get_queried_version()`
2. Fixed `test_missing_auth()  `
3. Fixed `test_invalid_key() `
4. Fixed `test_invalid_auth()`
5. Fixed `test_info()`
6. Fixed `test_process_query()`

Fix incomplete unit tests (props @devinwalker)

---

easy-digital-downloads.php

Remove extra include of includes/misc-functions.php #5762

---

includes/admin/reporting/class-categories-reports-table.php

Don't hide empty categories in earnings report. #5711

---

includes/payments/actions.php

Add post-completion payment actions hook via scheduled single event #5453

---

includes/class-edd-cli.php

Randomize the number of items on payments and fix price_id definitions #5798

---

includes/plugin-compatibility.php

Avoid Really Simple SSL mixed content buffer on file delivery #5802

---

includes/admin/admin-footer.php

Update URL to "Rate Us" and link entire phrase.

---

includes/gateways/amazon-payments.php

Check for Amazon config during purchase processing instead of on init - issue/5716

---

includes/admin/reporting/graphing.php

Set day value to 1 for “last month”

---

includes/admin/settings/register-settings.php

and remove section labels on tabs that only have one section. See #5404

Add consistency to settings labels 

---

easy-digital-downloads.php
includes/admin/customers/customer-actions.php
includes/class-edd-customer-query.php
includes/class-edd-db-customers.php
tests/tests-customers-db.php

Addresses #5448 and replaces #5514

Introduce EDD_Customer_Query class #5448

---

easy-digital-downloads.php
includes/login-register.php
includes/template-actions.php
templates/shortcode-login.php
templates/shortcode-profile-editor.php
templates/shortcode-register.php

and shortcodes.
Add backwards compatibility for output of logged in/out messages on
various shortcakes, and introduces the ability to add a message on the
register form.
See #4922

Introduce template-actions.php to facilitate actions for templates

---

includes/admin/settings/register-settings.php

Modify description of Login Redirect Page setting

---

includes/admin/reporting/class-file-downloads-logs-list-table.php

Add filters to allow for custom logs information

---

includes/admin/downloads/metabox.php
includes/admin/thickbox.php

issue/5791 - Add `Enable Product Reviews` button

---

includes/payments/actions.php

Respect DISABLE_WP_CRON constant #5453

---

includes/payments/class-payments-query.php

Store and restore any existing globals for post and wp_query #5636

---

assets/js/admin-scripts.js
includes/admin/payments/view-order-details.php
includes/class-edd-html-elements.php
includes/scripts.php
tests/tests-html-elements.php

issue/5357 - Allow dynamic search placeholder for select elements

---

includes/admin/import/class-batch-import-payments.php
includes/admin/reporting/export/class-batch-export-payments.php

Allow variable price IDs in import/export of payments #5841

---

includes/admin/settings/register-settings.php

Support 'multiple' in select settings API #4736

---

includes/shortcodes.php
includes/template-functions.php
templates/shortcode-download.php

Introduce a single template file for use inside of the [downloads] shortcode

---

templates/shortcode-profile-editor.php

fix incorrect class name

---

includes/payments/functions.php

Remove extra } #5857

---

includes/class-edd-license-handler.php

Add function_exists() check to auto_updater() call for edd_extension_has_beta_support()

---

assets/js/edd-ajax.js

Change the state field name depending on if the form is the checkout or the profile editor #5489

---

assets/js/edd-checkout-global.js

Add negative luhn check on the card name field #5845

---

includes/process-purchase.php

Reverts easydigitaldownloads/easy-digital-downloads#5728

Revert "User 0 instead of -1 for payment user ID #5727"

---

includes/EDD_SL_Plugin_Updater.php

Update EDD_SL_Plugin_Updater #5882

---

assets/css/edd-admin.css
assets/js/admin-scripts.js

add legacy remove row class back to JS

---

includes/EDD_SL_Plugin_Updater.php

Do not autoload the api responses for the plugin updater #5897

---

assets/js/edd-ajax.js
includes/scripts.php
includes/template-functions.php
tests/tests-templates.php

Revert  #5657 with #5900

---

templates/edd.css

issue/5756 - Plain text links still look like buttons

---

includes/payments/functions.php

use a global to prevent getting the same purchase ID in the same thread #5896

---

includes/admin/tools.php

Swap WPLANG for get_locale()

---

includes/process-purchase.php

issue/5846 - Unneeded validation of billing fields when cart total is $0

---

includes/admin/payments/class-payments-table.php

add bulk action and count to payments table for Processing payments

---

includes/class-edd-customer-query.php

issue/5921 – Add a search_columns argument to EDD_Customer_Query

---

includes/admin/discounts/add-discount.php
includes/admin/settings/register-settings.php

add missing periods to settings labels

---

includes/admin/settings/register-settings.php

improve Item Quantities setting label and description 

---

templates/widget-cart-item.php

conditionally show item quantities in cart widget

---

assets/css/edd-admin.css

remove download taxonomy page styles

---

includes/class-edd-db-customers.php

issue/5911 - Remove offset when counting all customers

---

SUPPORT.md

Introduces a SUPPORT.md file, per https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5928

Create SUPPORT.md (#5928)

---

.travis.yml
includes/class-edd-discount.php
tests/tests-discounts.php
tests/tests-payments.php

issue/5684 - Discounts with multiple exclusions can be applied to excluded products

---

includes/checkout/template.php

Updating pattern on included form

---

includes/scripts.php

don't enqueue jquery.payment #5935

---

templates/history-downloads.php

Use download name instead of get_the_title()

---

includes/cart/class-edd-cart.php
tests/tests-cart.php

Adjust subtotal_for_tax with negative product fees. #5940

---

assets/css/edd-admin.css

Use same #excerpt styles for product notes field #5937

---

assets/js/admin-scripts.js
includes/payments/class-edd-payment.php
includes/scripts.php
tests/tests-payment-class.php

Remove decimal separators from values before calculating amounts when editing payments #5946

---

includes/widgets.php

Change "Show Title" text on Download Details widget #5953

---

includes/error-tracking.php
includes/payments/actions.php
includes/payments/class-edd-payment.php
includes/payments/functions.php
tests/tests-payments.php

Flex recovery rules when guest checkout is enabled #5926

---

includes/admin/reporting/class-sales-logs-list-table.php

Use per_page property for per_page and pagination #5938

---

includes/admin/discounts/add-discount.php
includes/admin/discounts/edit-discount.php

issue/5795 - Make discount input wider

---

includes/login-register.php

issue/5761 - Fix reference to login

---

includes/payments/class-edd-payment.php

Add inline doc for why edd_payment_meta filter runs twice #5838

---

includes/template-functions.php
templates/shortcode-download.php

Change @since from 2.9 to 2.8 #5982

---

templates/edd.css
templates/shortcode-login.php
templates/shortcode-register.php

issue/5757 - Update login and register form styling

---

assets/css/edd-admin.css
includes/admin/payments/view-order-details.php
includes/payments/class-edd-payment.php

Allow removing a deleted download from a payment #5959

---

includes/process-purchase.php

Use like datatypes for address info, to avoid odd type checks #5995

---

includes/class-edd-discount.php
includes/discount-functions.php

EDD_Discount::add should check for a code before creating #5974

---

includes/payments/functions.php

Make URLs in payment notes clickable #5421

---

includes/admin/settings/register-settings.php
tests/tests-misc.php

Unset the option being deleted in edd_delete_option #5647

---

includes/gateways/amazon-payments.php
includes/scripts.php

Add in a filter to load the scripts in the header #5996

---

includes/admin/reporting/export/class-batch-export-sales.php

Add customer_id to the sales export #5850

---

includes/template-functions.php

Only show the checkout not set error once on the front end #5815

---

includes/process-download.php

Check for supported stream wrappers before delivering #5725

---

includes/admin/discounts/add-discount.php
includes/admin/discounts/discount-actions.php
includes/admin/discounts/edit-discount.php

Allow hyphens in discount codes #5839

---

includes/payments/class-edd-payment.php
tests/tests-payment-class.php

Add discounted_amount property and unit test #5580

---

assets/js/admin-scripts.js

issue/6023 - Use default search placeholder if none is set

---

.travis.yml
includes/class-edd-customer.php
includes/misc-functions.php
includes/payments/functions.php
tests/tests-tax.php

Strict type casting for stats updates.

---

includes/cart/class-edd-cart.php

Type issues for quantity math #5981

---

includes/admin/reporting/export/class-batch-export-payments.php
includes/country-functions.php
tests/tests-misc.php

Add country name to the payments export, with helper function and tests #5629

---

includes/class-edd-logging.php

From https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4864#issuecomment-332023921 discussion this adds better, more comprehensive, and unit testable code to the clear function of the debug logs's class clear log function.

Better clear routine for issue 4864

---

includes/payments/class-payments-query.php
includes/user-functions.php
tests/tests-customers.php

edd_get_users_purchased_products should respect the status #5671

---

assets/css/edd-admin.css
includes/admin/payments/view-order-details.php

issue/5714 - Make billing address fields larger

---

includes/checkout/template.php

Wrap discount fields in span tag #6041

---

includes/class-edd-html-elements.php

Account for possibility that selected is an array #6010

---

includes/payments/class-edd-payment.php

Set name to email only if first and last name are empty. #6046

---

assets/css/edd-admin.css
includes/admin/discounts/add-discount.php
includes/admin/discounts/edit-discount.php
includes/admin/payments/class-payments-table.php
includes/admin/settings/register-settings.php

More responsive fixes for administration #5644

---

includes/user-functions.php
tests/tests-customers.php

issue/6031 - Newly register user's ID is not set on pre-existing payments

---

assets/js/admin-scripts.js
includes/admin/settings/register-settings.php

issue/5905 - Add `hidden` class to `base_state` if no states exist for country

---

includes/admin/settings/register-settings.php
includes/admin/tools.php
includes/class-edd-logging.php
includes/misc-functions.php

Debug mode - Issue/4864

---

includes/admin/downloads/metabox.php
includes/class-edd-html-elements.php

Fix product dropdown with variable pricing support #5991

---

includes/admin/reporting/export/class-batch-export-payments.php

remove undefined function call edd_get_country(). #6058

---

includes/process-download.php

Add args array to edd_requested_file_name. #6060

---

includes/admin/settings/register-settings.php
includes/class-edd-register-meta.php

issue/6006 - Fix typos

---

assets/css/edd-admin.css
includes/admin/add-ons.php
includes/admin/admin-actions.php
includes/admin/admin-pages.php

Move the 'Extensions' tab to a more visible location #6088

---

includes/process-download.php

Avoid stream detection on Windows servers due to conflict with file paths #6081

---

includes/admin/add-ons.php
includes/admin/admin-actions.php

issue/6093 - Fix incorrect URL 

---

includes/payments/class-edd-payment.php

Fix apply_filters call #6095

---

templates/shortcode-receipt.php

Issue/6080 - Product notes div being rendered when no product notes added to download

---

includes/class-edd-discount.php

issue/6111 - Discount validation error when recovering pending payment

---

includes/error-tracking.php

Use case: show enhanced error messages based on gateway error codes.
Closes #6109

Add `edd_errors` filter to modify error messages 

---

includes/template-functions.php

Remove unused display_price argument. #6106

---

includes/api/class-edd-api.php
includes/libraries/array2xml.php
includes/libraries/class-ArrayToXML.php

Update array to xml class and deprecate old one #5826

---

includes/admin/reporting/graphing.php

issue/6128 - Fix earnings reports for downloads not outputting the correct data

---

includes/admin/reporting/graphing.php

Issue/6128 - Custom date ranges for detailed product earnings break on multi-month views

---

includes/class-edd-customer.php

Cache customers retrieved in a static instances array

---

includes/class-edd-customer.php

Only load additional emails when requested

---

includes/user-functions.php

Use null as default value for edd_user_pending_verification() #6157

---

assets/css/edd-admin.css
includes/admin/tools.php

Issue/6067 - Improve Debug Log View Usability

---

includes/class-edd-customer.php

Only load notes for customer if they aren't already loaded
Part of #6124

Only load notes for customer if they aren't already loaded

---

includes/class-edd-discount.php

issue/6159 - Fix discount validation message

---

includes/admin/payments/class-payments-table.php

Issue/6063 - Add filters for payment gateways on payments table

---

includes/admin/downloads/metabox.php

Fix spelling of edd_render_down_tax_options(). #5101

---

includes/payments/class-edd-payment.php

Reverting part 1 of #6124

---

includes/class-edd-customer.php

Revert part 4 of #6124

---

includes/class-edd-customer.php
includes/class-edd-db-customers.php

Revering part 3 of #6124

---

includes/admin/discounts/add-discount.php

adjust discount Minimum Amount label 

---

includes/process-purchase.php

Fix translation call #6163

---

includes/payments/class-payments-query.php

Remove dependency on prefix and post fix when searching by payment number - issue/6178

---

assets/js/admin-scripts.js

Issue/5952 - Use delegation handler

---

readme.txt

Remove MercadoPago from readme.txt #6181

---

includes/user-functions.php

Issue/6185 - Defensive coding for edd_add_past_purchases_to_new_user 

---

templates/shortcode-receipt.php

Add : to purchase receipt taxes and subtotal #6196

---

includes/gateways/paypal-standard.php

Add a filter for the web accept variables #6184

---

includes/gateways/paypal-standard.php

Add debug logging to PayPal IPN. #6195

---

includes/cart/class-edd-cart.php

Force quantity to 1 no matter what. #6193

---

includes/gateways/paypal-standard.php

Add support for PayPal PDT. #6197

---

includes/admin/add-ons.php

Fix campaigns on extensions list #6208

---

includes/cart/class-edd-cart.php
includes/class-edd-fees.php

Only apply a matching amount + label to a cart item once with fees #6205

---

includes/admin/reporting/export/class-batch-export-sales.php

issue/6126 - Fix bug with sales exports with date range of same day

---

includes/class-edd-stats.php

issue/6213 - array_key_exists() warning in EDD_Stats::convert_date()

---

includes/payments/functions.php

Be sure to send price ID when looking at bundle products issue/6215

---

includes/template-functions.php

Issue/6232 - Change span to div for schema markup

---

includes/class-edd-cli.php

Allow random generation of first and last names, domain and TLD #6239

---

includes/process-purchase.php

http://grammarist.com/spelling/log-in-login/
see #2385 😄

When used as a verb, it is two words: "log in"

---

includes/admin/settings/register-settings.php

issue/3056 - Add hidden field to settings API

---

easy-digital-downloads.php
includes/admin/reporting/class-edd-reports.php
includes/class-edd-reports.php
tests/tests-easy-digital-downloads.php

issue/6260 – EDD_Reports stub

---

includes/admin/admin-pages.php
includes/admin/customers/class-customer-table.php
includes/admin/downloads/dashboard-columns.php
includes/admin/downloads/metabox.php
includes/admin/payments/view-order-details.php
includes/admin/reporting/logs.php
includes/admin/reporting/reports.php
includes/admin/tools.php
includes/admin/tools/logs.php
includes/misc-functions.php

Issue/6265 – Move Logs to the Tools screen

---

includes/template-functions.php

Reverts easydigitaldownloads/easy-digital-downloads#6233
Resolves #6271

Revert "Issue/6232 - Change span to div for schema markup"

---

includes/admin/admin-pages.php
includes/admin/customers/class-customer-table.php
includes/admin/downloads/dashboard-columns.php
includes/admin/downloads/metabox.php
includes/admin/payments/view-order-details.php
includes/admin/reporting/logs.php
includes/admin/reporting/reports.php
includes/admin/tools.php
includes/admin/tools/logs.php
includes/misc-functions.php

Previously implemented against `issue/6236` via #6266.
Issue: #6265

Issue/6265 – Move the logs tab from reports to tools

---

assets/css/edd-admin.css
assets/js/admin-scripts.js
includes/admin/settings/register-settings.php

Improve responsive design for tax rate settings. #6034

---

includes/admin/customers/customer-functions.php

issue/5848 - Display `Customer` column on Users page

---

includes/admin/payments/class-payments-table.php
includes/admin/reporting/class-sales-logs-list-table.php

issue/5461 - Display `Unnamed Customer` if customer has no name

---

includes/admin/reporting/class-report.php
includes/admin/reporting/class-reports-registry.php
includes/admin/reporting/data/class-endpoint-registry.php
includes/admin/reporting/reports.php
includes/class-edd-reports.php
tests/admin/reports/tests-endpoint-registry.php
tests/admin/reports/tests-report.php

issue/6284 – Report object API

---

easy-digital-downloads.php

Formatting cleanup. There wasn't a space before the asterisk on line 473.

Line 473 - Missing space before * @return

---

includes/admin/reporting/data/class-endpoint.php
includes/admin/reporting/data/class-report.php
includes/admin/reporting/data/class-reports-registry.php
includes/admin/reporting/data/class-tile-endpoint.php
includes/admin/reporting/graphing.php
includes/admin/reporting/reports.php
includes/class-edd-reports.php
includes/misc-functions.php
tests/admin/reports/data/tests-report.php

issue/6284 – (WIP) Render reports

---

includes/class-edd-register-meta.php

Always force files to sanitize to the array data type #6294

---

includes/admin/tracking.php

send active gateways for opt-in tracking #6341

---

includes/class-edd-session.php

Do not start sessions in the admin unless it is an ajax request. #6240

---

tests/bootstrap.php
tests/helpers/class-edd-unittestcase.php
tests/phpunit/class-edd-unittestcase.php
tests/phpunit/factories/class-edd-factory.php
tests/phpunit/factory.php

issue/6346 - Introduce factory for unit tests

---

includes/admin/settings/register-settings.php

issue/6249 - Fix typo in upload callback

---

includes/admin/reporting/export/class-batch-export-earnings-report.php

Rework the earnings export to be more clear and add support for additional order statuses #6269

---

includes/admin/settings/register-settings.php
includes/template-functions.php

introduce setting for Checkout button text #6340

---

includes/admin/reporting/reports.php
includes/deprecated-functions.php
includes/reports/data/class-base-object.php
includes/reports/data/class-report.php
includes/reports/reports-functions.php
tests/reports/data/tests-base-object.php
tests/reports/data/tests-report.php
tests/tests-utilities.php

Issue/6360 – Report display method and callback

---

assets/js/admin-scripts.js

issue/6306 - manually uncheck checkboxes when cloning repeatable row #6306

---

includes/user-functions.php

Add filters to the new user registration emails sent #5146

---

assets/js/admin-scripts.js
includes/admin/reporting/graphing.php
includes/admin/reporting/reports.php
includes/deprecated-functions.php
includes/reports/class-init.php
includes/reports/data/class-endpoint-registry.php
includes/reports/data/class-report.php
includes/reports/reports-functions.php
tests/reports/data/tests-report.php
tests/reports/tests-reports-functions.php

Issue/6257 – (WIP) Endpoint Filters API

---

includes/admin/discounts/discount-actions.php

look up discount by ID instead of code #6389

---

includes/payments/class-edd-payment.php
includes/payments/functions.php

issue/6082 - Wrap payment note in esc_html()

---

includes/admin/tracking.php

issue/6391 - Use get_locale() for EDD tracking

---

includes/admin/tracking.php

Ignore the reqeust for checkin, and just move on #6367

---

includes/cart/class-edd-cart.php
includes/widgets.php

issue/6317 - PHP 7.2 compatibility for unit tests

---

includes/process-download.php

Clear the output buffer before reading files in download process. #6387

---

includes/widgets.php

Make sure there are tags, before we try and count them #6372

---

includes/admin/add-ons.php

fix incorrect link paths #6410

---

includes/emails/class-edd-emails.php

Add make_clickable and fix broken links #6413

---

includes/process-download.php

issue/5087 - Add support to resume downloads of large files

---

includes/admin/settings/register-settings.php

issue/6437 - fix incorrect setting title

---

includes/admin/class-edd-notices.php
includes/admin/discounts/add-discount.php
includes/admin/discounts/edit-discount.php
includes/admin/payments/class-payments-table.php
includes/admin/settings/register-settings.php
includes/template-functions.php
tests/bootstrap.php

issue/6443 - fix missing or incorrect textdomains

---

includes/admin/settings/display-settings.php
includes/admin/settings/register-settings.php

Always treat sections data as an array, instead of mixed #6434

---

Gruntfile.js
package-lock.json
package.json

Issue/6439 (WIP) - update Grunt configuration

---

assets/css/edd-admin.css
assets/js/admin-scripts.js
includes/admin/customers/customer-actions.php
includes/admin/customers/customers.php
includes/ajax-functions.php
includes/class-edd-component.php
includes/class-edd-html-elements.php

Issue/6417 - (WIP) Customer editing improvements

---

assets/js/admin-scripts.js
includes/scripts.php

Fixes #6495
1. Require confirmation before disconnecting user from customer record.

issue/6495 - require confirmation before disconnecting user from customer

---

includes/shortcodes.php

As per #6376, add a download list before the download grid

Add action hook before download grid

---

assets/css/edd-admin.css
includes/reports/class-init.php
includes/reports/class-registry.php
includes/reports/data/charts/v2/class-dataset.php
includes/reports/data/charts/v2/class-manifest.php
includes/reports/data/charts/v2/class-pie-dataset.php
includes/reports/data/class-report.php
includes/reports/data/class-reports-registry.php
includes/reports/reports-functions.php
tests/reports/data/tests-reports-registry.php
tests/reports/tests-reports-functions.php

Issue/6511 – Pie/doughnut chart support

---

includes/checkout/template.php

Issue/6537 - Remove duplicate “button” class

---

easy-digital-downloads.php
includes/class-edd.php
includes/gateways/amazon-payments.php

Work in progress.
See #6290, #6311.

issue/6290 - (WIP) - Handle PHP versions lower than 5.3

---

assets/js/admin-scripts.js
includes/admin/customers/class-customer-table.php
includes/admin/customers/customers.php
includes/admin/discounts/add-discount.php
includes/admin/discounts/class-discount-codes-table.php
includes/admin/discounts/discount-functions.php
includes/admin/discounts/edit-discount.php
includes/admin/payments/class-payments-table.php
includes/admin/payments/view-order-details.php
includes/admin/reporting/graphing.php
includes/admin/settings/register-settings.php
includes/class-edd-utilities.php
includes/date-functions.php
includes/emails/class-edd-email-tags.php
includes/emails/template.php
includes/misc-functions.php
includes/payments/functions.php
includes/reports/reports-functions.php
includes/scripts.php
includes/utils/class-date.php
templates/history-purchases.php
templates/shortcode-receipt.php
tests/phpunit/class-edd-unittestcase.php
tests/tests-date-functions.php
tests/tests-date-object.php
tests/tests-utilities.php

(WIP) issue/6513 - Date/Time/Format/Zone improvements:

---

includes/admin/settings/register-settings.php
includes/checkout/template.php

Allow payment icons to be filtered by key.

---

includes/admin/admin-actions.php
includes/privacy-functions.php
languages/easy-digital-downloads.pot

Fixes #6586
1. Adds missing full stops to the exporter and erasure messages.
2. Adds missing text domain to the privacy policy and agreement terms exporter

Adding full stops and adding missing text domains #6586

---

includes/database/queries/class-order-adjustment.php
includes/orders/class-order-adjustment.php
includes/orders/class-order-item.php
includes/orders/class-order.php

issue/4576 - Migrate payments to a custom table

---

includes/admin/settings/register-settings.php
readme.txt

Fixes some minor strings
1. short code to shortcode in readme
2. Consistency between the new Privacy Policy checkbox options and Terms checkbox options

Minor strings

---

includes/admin/reporting/class-file-downloads-logs-list-table.php
includes/admin/reporting/export/class-batch-export-file-downloads.php
includes/class-edd-logging.php
includes/database/queries/class-log-file-download.php
includes/database/schemas/class-logs-file-downloads.php
includes/database/tables/class-logs-file-downloads.php
includes/logs/class-file-download-log.php

issue/5617 - Add user agent to file download logs

---

includes/admin/reporting/export/class-batch-export-downloads.php
includes/admin/reporting/reports.php

issue/5114 - Add a single download product export option

---

includes/database/tables/class-base.php
includes/database/tables/class-customer-meta.php
includes/database/tables/class-customers.php

**WIP - Do not merge**
#6310 
#6447

issue/6310 - Customers table improvements

---

assets/js/edd-checkout-global.js
includes/tax-functions.php

issue/6621 - Expose entire customer address to tax rate filter

---

includes/emails/template.php

issue/5965 - Display correct gateway name.

---

includes/admin/discounts/add-discount.php
includes/admin/discounts/discount-actions.php
includes/admin/discounts/edit-discount.php

issue/5766 - Allow discount expiration time to be set

---

assets/js/admin-scripts.js

Fixes #6630 
1. Update selector for counting notes.

Update note selector to fix "No notes" issue. #6630

---

assets/css/edd-admin.css
includes/admin/payments/class-order-items-table.php
includes/admin/payments/view-order-details.php
includes/gateways/functions.php
includes/orders/functions.php

Please do not merge.
This PR is a work in progress.
See #2721.

(WIP) - Issue/2721 - Partial order refunds

---

includes/class-edd-session.php

Allow EDD Session to start in wp-admin

---

includes/gateways/functions.php
includes/orders/class-order-item.php
includes/orders/functions.php
includes/payments/class-edd-payment.php
includes/payments/functions.php
tests/orders/tests-edd-payment.php
tests/tests-post-types.php
tests/tests-tax.php

issue/6079 - Add tax rate for each order item.

---

includes/class-edd.php
includes/compat/class-base.php
includes/compat/class-payment.php
includes/orders/class-order.php
includes/payments/class-edd-payment.php
includes/payments/functions.php
tests/orders/tests-edd-payment.php
tests/orders/tests-payments-back-compat.php
tests/tests-cart.php
tests/tests-checkout.php
tests/tests-register-meta.php
tests/tests-shortcodes.php

See #4576.
**Phase 3 of payments migration**
* Backwards compatibility with WordPress Core methods.

(WIP) issue/4576 - Phase 3 of payments migration

---

includes/admin/payments/class-payments-table.php
includes/payments/class-payments-query.php

issue/6628 - Payment history status filters don't work within searches

---

includes/admin/reporting/class-export.php

Fixes #4859
1. Add a BOM to all CSV exports so that Excel knows that the CSV is in Unicode.

issue/4859 - Fix CSV formatting for Excel

---

includes/class-edd-logging.php
includes/class-edd.php
includes/compat/class-log.php
includes/compat/class-payment.php

issue/6324 - Group back compat code together.

---

assets/js/edd-checkout-global.js

Show ajax loading indicator while taxes are being recalculated. #6682

---

includes/admin/reporting/reports.php
includes/class-edd-logging.php
includes/download-functions.php
includes/logs/functions.php
includes/orders/class-stats.php

issue/6297 - 3.0 Reports: Overview Tab

---

includes/admin/reporting/reports.php
includes/orders/class-stats.php
includes/reports/data/payment-gateways/class-gateway-stats-list-table.php
includes/reports/reports-functions.php

issue/6300 - 3.0 Reports: Payment Gateways

---

includes/admin/reporting/reports.php
includes/class-edd-html-elements.php
includes/orders/class-stats.php
includes/reports/data/discounts/class-top-five-discounts-list-table.php
includes/reports/reports-functions.php

issue/6303 - 3.0 Reports: Discounts

---

includes/admin/reporting/reports.php
includes/class-edd-html-elements.php
includes/orders/class-stats.php
includes/reports/reports-functions.php

issue/6301 - 3.0 Reports: Taxes Tab

---

includes/admin/reporting/class-file-downloads-logs-list-table.php
includes/admin/reporting/reports.php
includes/admin/upgrades/upgrade-functions.php
includes/class-edd-cli.php
includes/class-edd-logging.php
includes/database/queries/class-log-file-download.php
includes/database/schemas/class-logs-file-downloads.php
includes/database/tables/class-logs-file-downloads.php
includes/download-functions.php
includes/logs/class-file-download-log.php
includes/logs/functions.php
includes/orders/class-stats.php
includes/reports/data/file-downloads/class-top-five-most-downloaded-list-table.php

issue/6302 - 3.0 Reports: File Downloads Tab

---

includes/admin/reporting/reports.php
includes/orders/class-stats.php
includes/reports/data/downloads/class-earnings-by-taxonomy-list-table.php
includes/reports/data/downloads/class-top-selling-downloads-list-table.php

issue/6298 - 3.0 Reports: Products tab

---

assets/css/edd-admin.css
assets/js/admin-scripts.js
includes/admin/payments/class-payments-table.php
includes/class-edd.php
includes/database/queries/class-advanced-query.php
includes/database/queries/class-base.php
includes/payments/class-payments-query.php

isuse/6086 - Advanced Filters

---

includes/admin/reporting/export/class-batch-export-file-downloads.php

Fixes #6643 
1. Switches the file download export to use the customer ID or payment email address in the export file

Fix downloaded by column in file download export #6643

---

includes/admin/downloads/metabox.php

fix Purchase Shortcode metabox typo #6721

---

includes/admin/settings/register-settings.php
includes/class-edd-html-elements.php

issue/6518 - Use EDD_HTML_Elements for checkboxes in settings

---

includes/process-purchase.php

Remove checks for user by email during checkout. #6771

---

includes/admin/upgrades/classes/class-file-download-log-migration.php

Fixes https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6769

Remove space between MYSQL function `COUNT` and parenthesis.

---

includes/discount-functions.php
includes/orders/functions.php
includes/privacy-functions.php

issue/6793 - Add `edd_insert_payment` hook.

---

includes/admin/settings/register-settings.php

issue/6814 - Display correct tax rate fields

---

includes/orders/functions.php

issue/6834 - Only store tax rate if tax is applied

---

includes/admin/reporting/export/class-batch-export-customers.php
includes/admin/reporting/export/export-functions.php
includes/admin/reporting/reports.php

issue/3964 - (WIP) Export customers by taxonomy

---

assets/js/admin-scripts.js
includes/ajax-functions.php
includes/tax-functions.php

**WIP - Do not merge**
See #6788

issue/6788 - Recalculate taxes dynamically when adding an order

---

assets/js/admin-scripts.js

issue/6833 - Re-initialise datepickers after cloning

---

includes/admin/payments/actions.php
includes/admin/payments/class-payments-table.php

issue/6766 - Process bulk actions outside of list table.

---

includes/admin/discounts/discount-actions.php

issue/6849 - Allow `0` to be passed as discount amount

---

assets/css/edd-admin.css

issue/6718 - Report content erroneously toggles display of browser scroll bar

---

includes/EDD_SL_Plugin_Updater.php

Fixes #6850
1. Brings the plugin updater to the latest version that's pending for SL 3.6.5

Update the plugin updater for #6850

---

assets/js/admin-scripts.js
includes/admin/upgrades/upgrade-functions.php

Fixes #6782.
1. Remove 'dismissable' notices from batch processor.
2. Fix grammar for the upgrade notice.

issue/6782 - Remove dismissable upgrade notices & fix grammar

---

includes/database/tables/class-customer-addresses.php
includes/database/tables/class-customers.php
includes/database/tables/class-logs-api-requests.php
includes/database/tables/class-logs-file-downloads.php
includes/database/tables/class-logs.php
includes/database/tables/class-notes.php
includes/database/tables/class-order-addresses.php
includes/database/tables/class-order-adjustments.php
includes/database/tables/class-order-items.php
includes/database/tables/class-order-transactions.php

Change date_refundable to date_modified in upgrade functions. #6867

---

includes/admin/tools.php

Fixes #6799
1. Adds the current date and time to the top of the system info.

Add "Generated Date" to System Info.

---

includes/EDD_SL_Plugin_Updater.php

Fixes #6850
1. Moves the health check logic out of the `__construct` and into the `api_request` method so it does not run on every page load, just when the API is being requested. h/t @DevinWalker

Updating the health check in the Plugin updater to be only during the API Calls #6850

---

includes/orders/functions.php

Fixes #6887
1. Add "Order" to "+New" admin bar menu item.

Add "Order" to the "+ New" admin bar menu item.

---

includes/checkout/template.php

Issue/6909 - Incorrect label "for" attributes on checkout login form

---

includes/api/class-edd-api-v2.php
includes/api/class-edd-api.php

Issue/6861 - Add order and orderby parameters

---

assets/js/edd-checkout-global.js

Fixes #6779
1. Adds Javascript to update `data-subtotal` and `data-total` attributes on elements with the `edd_cart_amount` class when changing quantities.

Update data attributes for subtotal and total on .edd_cart_amount elements #6779

---

includes/EDD_SL_Plugin_Updater.php

Brings the plugin updater included with EDD Core up to date with the one delivered with our SL samples. This includes support for the plugin icons in WP 4.9.

Update EDD_SL_Plugin_Updater to support icons.

---

templates/edd.css

Issue/6926 - Remove erroneous clearfix rule

---

easy-digital-downloads.php

Fixes #6935
1. Updated comment for locale determination.

Fix reference to AffiliateWP in the comments #6935

---

templates/edd.css

Implement CSS Grid

---

includes/cart/class-edd-cart.php
tests/tests-discounts.php

Fixes #6901 
1. Do not attempt to apply discounts to free cart items

only apply discounts to non-free cart items #6901

---

templates/edd.css

Add float to legend element.
Fixes #6924

Issue/6924 - Add float to legend element

---

includes/formatting.php

Fixes #6966
1. Corrects the docblock on `edd_currency_filter` for the proper return type.

Fixing docblock #6966

---

includes/payments/class-edd-payment.php

Fixes #6859
1. Loop through the fees and add them to the total
2. Negative fees will decrease total.

Account for Fees of Cart Item Price

---

templates/edd-rtl.css
templates/edd.css

Issue/6928 - Remove vendor prefixes from CSS

---

assets/js/edd-ajax.js

Fixes #6987
1. Before calling out for the state fields, checks that state fields are present.

Only call for state fields when state fields are present #6987

---

templates/edd-rtl.css
templates/edd.css

Issue/6984 - Remove invalid CSS selector

---

assets/css/edd-admin.css

Set move cursor just on the icon. #6872

---

includes/class-edd-discount.php

Restore discount getters Issue/6956

---

includes/adjustments/functions.php
includes/customer-functions.php
includes/database/schemas/class-adjustments.php
includes/database/tables/class-adjustment-meta.php
includes/database/tables/class-adjustments.php
includes/logs/functions.php
includes/notes/functions.php
includes/orders/functions/addresses.php
includes/orders/functions/adjustments.php
includes/orders/functions/items.php
includes/orders/functions/orders.php
includes/orders/functions/transactions.php

**WIP - Do not merge.**
See #7010.

issue/7010 - Document arguments accepted by all new 3.0 functions

---

includes/admin/downloads/metabox.php
languages/easy-digital-downloads.pot

Restore phrasing of empty for global and 0 for unlimited. Fixes #6720

---

assets/css/edd-admin.css

3:0 Ellipsis long tile values in reports

---

includes/checkout/template.php

Issue/7025 - Correct default agree to privacy policy text

---

includes/adjustments/functions.php
includes/customer-functions.php
includes/database/schemas/class-adjustments.php
includes/database/tables/class-adjustment-meta.php
includes/database/tables/class-adjustments.php
includes/logs/functions.php
includes/notes/functions.php
includes/orders/functions/addresses.php
includes/orders/functions/adjustments.php
includes/orders/functions/items.php
includes/orders/functions/orders.php
includes/orders/functions/transactions.php

Restore 3.0 documentation updates - Issue/7010

---

includes/admin/settings/register-settings.php

Issue/7029 - Set "Default Button Color" to blue

---

includes/admin/class-edd-notices.php
includes/template-functions.php

Issue/7031 - Link to “Pages” section when no checkout page has been configured

---

includes/class-edd-logging.php

Add function exists check to mb_convert_encoding(). #6243

---

includes/admin/reporting/reports.php
includes/class-stats.php

Fixes #7083
1. Fixes the column being quoted for the AVG and SUM calculations.
2. Fixes the order by for getting the most popular discounts.

Fix average, total, and most popular discount report tiles #7083

---

includes/admin/reporting/reports.php
includes/class-stats.php
includes/reports/data/payment-gateways/class-gateway-stats-list-table.php

Fixes #7076
1. Adds 'type' support to the stats class.
2. Allows sending in `any` for the status of the stats class
3. Makes the gateway list table respect the date range provided.
4. Thanks to the first change, allows showing a more accurate list table with a refunded sales column

Improve stats and gateway reports.

---

includes/gateways/paypal-standard.php

Add multi-step determination of payment gross in PDT validation. Resolves #7105

---

includes/class-stats.php

Fixes #7148
1. Updates `$this->query['table']` to `$this->query_vars['table']`

Fix DB error for get_average_refund_time #7148

---

includes/privacy-functions.php

Fixes #7178
1. Adds checks to return no data if no customer Id is found for an email address.

Return no customer data when customer Id is 0 #7178

---

assets/js/edd-ajax.js

Fixes #7183 
1. Adds the `id="card_state"` to the text input

Add ID to the state input text field #7183

---

includes/admin/customers/class-customer-table.php
includes/admin/payments/view-order-details.php

Fixes #6746 
1. use customer id instead of wp user id

Customer download log show all logs

---

assets/js/admin-scripts.js
includes/admin/payments/view-order-details.php
includes/scripts.php

Fixes #7132 
1. Make sure the JS targets the correct element for cloning
2. Make sure an element always exists for cloning

Make it possible to add products to product-less payments

---

includes/admin/payments/class-payments-table.php
includes/admin/upgrades/v3/class-base.php
includes/admin/upgrades/v3/class-data-migrator.php
includes/class-edd-cli.php

Migration updates for hardening, improved compatiblity and catching some data errors

---

includes/admin/upgrades/v3/class-data-migrator.php

Unserialize extra payment meta

---

readme.txt

Resolves #5676
- Add relevant testimonials in existing description sections
- Add new testimonials section
- Add new FAQ about product types and include testimonials within
- Remove links to gateways we no longer support
- Add All Access to the list of notable extensions

Update readme.txt (#7159). See #5676.

---

includes/EDD_SL_Plugin_Updater.php

Update EDD_SL_Plugin_Updater.php to version 1.6.19

---

includes/admin/payments/orders.php
includes/admin/payments/view-order-details.php

Move hook outside metaboxes

---

includes/database/tables/class-adjustments.php

Issue/7263-2: Adds `column_exists()` check before attempting to remove column

---

includes/gateways/paypal-standard.php

Enable paypal as a safe redirect before redirecting to PayPal.

---

includes/admin/reporting/reports.php
includes/class-edd-cli.php
includes/class-stats.php
includes/database/queries/class-order-address.php
includes/database/schemas/class-customer-addresses.php
includes/database/schemas/class-order-addresses.php
includes/orders/functions/orders.php
includes/reports/data/customers/class-most-valuable-customers-list-table.php
includes/reports/data/taxes/class-tax-collected-by-location-list-table.php

Fixes found when prepping for office hours.

---

includes/admin/payments/class-order-items-table.php

Remove the ability to 'reverse' a refund.

---

includes/database/README.md

Add README.md describing all custom tables.

---

includes/payments/functions.php
tests/bootstrap.php
tests/tests-payments.php

Reverts easydigitaldownloads/easy-digital-downloads#7316

Revert "Refactor how edd_get_payment_status finds the status, with unit tests  #7292"

---

includes/admin/class-edd-notices.php

Add filter around nginx redirect warning

---

includes/misc-functions.php
tests/tests-misc.php

Add polyfills for is_countable and is_iterable #7219

---

includes/process-download.php

Fixes #7279
1. Adds a check to see if we've gotten the file by attachment ID (which will try and resolve to a path in some cases, and not URL).

Possible fix for unique hosting platforms putting content in directories #7279

---

includes/payments/functions.php
tests/bootstrap.php
tests/tests-payments.php

Refactor how edd_get_payment_status finds the status, with unit tests #7292

---

easy-digital-downloads.php
languages/easy-digital-downloads.pot
package-lock.json
package.json
readme.txt

Version bump and build for 2.9.19

Version bump and build for 2.9.19

---

tests/tests-logging.php

Fix EDD_Logging->delete_logs unit test

---

includes/database/engine/class-column.php

Remove date_i18n() usage in datetime column validation #7436

---

includes/admin/settings/register-settings.php

Set the “type” attribute for the SendWP button to be “button”

---

includes/admin/settings/display-settings.php

Make sure wrapper_class is always an array

---

includes/payments/actions.php

Add missing params to edd_after_payment_actions

---

includes/admin/import/class-batch-import-downloads.php

Set index and condition when creating files array uring Download import. #7226

---

includes/formatting.php
tests/tests-formatting.php

Convert empty strings to 0 before multiplying. #7470

---

assets/css/edd-admin.css
assets/js/admin-scripts.js
includes/admin/settings/register-settings.php

Built off of #7467 
Updates UI to:

Adjust 3rd Party Connection CTA Buttons

---

includes/database/engine/class-query.php
includes/database/queries/class-order-address.php
includes/database/queries/class-order.php

Allow querying orders by country/region #7397

---

includes/admin/settings/display-settings.php

Fixes #7483 
1. Just fixing a typo now so it doesn't show up again later. And also making it available in case we push an update before the current BFCM sale is over.

correct typo in admin promotional area #7483

---

includes/misc-functions.php

Check if status key is set before using #7497

---

assets/css/edd-admin.css
assets/css/edd-admin.css.rej
assets/js/admin-scripts.js
includes/admin/settings/register-settings.php
includes/emails/functions.php

Add Jilt link in settings

---

includes/component-functions.php

Correct schema class names for all components #7499

---

includes/download-functions.php

Fixes #7546
1.Takes the query to get the log counts after the logic to see if we even need to check the log counts.

Moving query to get file download logs to conditionally run #7546

---

readme.txt

PR for #7514: Add min php version to readme.txt

---

includes/admin/admin-actions.php
includes/admin/reporting/class-base-logs-list-table.php
includes/component-functions.php
includes/database/engine/class-base.php
includes/database/engine/class-query.php
includes/database/engine/class-schema.php
includes/database/engine/class-table.php

issue/7501 - Update return types in PHPDocs to be more specific #7501

---

includes/admin/settings/register-settings.php

Fixes #7476 
1. Ensure "Styles" tab sections are deprecated properly.

issue/7476 - Ensure "Styles" Tab Sections are Deprecated Properly

---

includes/admin/settings/register-settings.php

Fixes #7531 
1. Updates link to the privacy policy to `options-privacy.php`.

Fixing privacy policy link in privacy settings #7531

---

includes/admin/payments/class-payments-table.php

Fixes #7617
Proposed Changes to orders table:
1. Adds `Resend Receipt` row action.
2. Applies `edd_payment_row_actions` filter to allow extensions to add row actions.

issue/7617 - Apply filter to order row actions & add Resend Receipt action

---

includes/admin/payments/orders.php

Correct closing label tag #7622

---

includes/class-edd-db-customers.php

Allows finding customer records via other methods (other tables, etc).
1. Adds a `edd_pre_get_customer` for short-circuiting the search.
2. Adds a `"edd_get_customer_by_{$field}"` and `edd_get_customer` filter at the bottom for filtering the result.

Add get_customer pre/post filters.

---

includes/country-functions.php
tests/tests-misc.php

Fixes #7432 
1. Define a set list of provinces for Netherlands.

issue/7432 - Define Netherland's Provinces

---

includes/admin/reporting/reports-callbacks.php

Fixes #7660 
1. Ensure amounts for Refunds are positive when constructing the Report chart.

issue/7660 - Invert Refund Amounts in Report Chart

---

includes/class-edd-db-customers.php

Fixes #7677 
1. Document `edd_pre_get_customer`, `edd_get_customer_by_{$field}`, `edd_get_customer`

issue/7677 - Document Customer Retrieval Filters

---

includes/template-functions.php

Fixes #7619 
1. Verified that is `$post` is instance of `WP_Post`
2. Fixed Yoda conditions
3. Fixed PHPCS

verified that post is wp_post #7619

---

includes/admin/settings/register-settings.php

See #7583 
1. Remove Chosen usage on setting's that don't have many options.
Some of these should still be converted to radios, but this is a start.

issue/7583 - Remove Unneeded Chosen Usage in Settings

---

includes/admin/dashboard-widgets.php

Remove incorrect comma from dashboard widget

---

includes/admin/views/tmpl-tax-rates-table-add.php

Fixes #7769 
1. Ensure proper closing tag is used in `tmpl-tax-rates-table-add.php`

Update <th> closing tag in tmpl-tax-rates-table-add.php

---

includes/class-edd-cli.php

Fixes #7690
1. Updates function used for getting discount count in WP CLI command.

issue/7690 Use new function for counting number of discounts

---

templates/payment-processing.php

Update payment processing icon markup

---

includes/admin/upgrades/v3/class-data-migrator.php

Ensure that both the customer ID and meta_value are available to migrate emails

---

includes/admin/upgrades/v3/class-data-migrator.php

Fix check for EDD_Customer migrator script

---

includes/admin/payments/orders.php

Remove edd_payment_personal_details_list hook from add order screen

---

includes/admin/upgrades/upgrade-functions.php

Deactivate the manual purchases addon

---

includes/admin/reporting/class-edd-graph.php
includes/admin/reporting/class-edd-pie-graph.php
includes/scripts.php

Fixes #7714 
1. Prefix Flot script handles with `edd-`

Prefix Flot script handles with edd-

---

assets/css/edd-admin.css

Fixes #7849
1. Adds the min-height present in EDD 2.9 back to the initial customer profile section
2. Removes floats from the stats list

Fix customer screen CSS

---

assets/css/edd-admin.css
includes/admin/payments/orders.php

Fixes #7843 
1. Added `edd-admin-box-inside--row` to transaction id
2. Added `flex-wrap` and `word-break` rules to class

Wrap Transaction ID

---

includes/admin/payments/orders.php

Fixes #7842
1. Uncommented out `edd-order-address-country-wrap` and `edd-order-address-state-wrap`
2. The select ids are now connected with their related JavaScript
3. Select fields now connected with id specific CSS
(Sorry, this one was my bad from the form-group project)

Region Updates with Country Update #7842

---

includes/class-edd-cli.php

Fixes #7841
1. Moves all database install logic to one single method.
2. This method installs all registered components rather than a fixed list.
3. This method runs once at the start of the full migration, but is also run in each separate method (since they can technically be run individually). However, a static variable is used to ensure it only actually executes the first time.

Move database install to one single method that runs once at start #7841

---

includes/database/tables/class-customers.php

Update `date_created` column modification on update to 3.0

---

includes/admin/notes/note-functions.php

Fix error when viewing notes associated with a deleted user

---

includes/admin/settings/register-settings.php

Update terms description

---

includes/admin/upgrades/upgrade-functions.php

Fix UI check for email address migration

---

includes/admin/reporting/export/class-batch-export-payments.php

Fixes #7877
Should be merged after #7879

Fix Exports when "All Statuses" is selected

---

includes/admin/reporting/class-sales-logs-list-table.php

Fix PHP warning on sales log table

---

includes/admin/reporting/reports-callbacks.php

Fix graph/tick values for reports

---

includes/admin/dashboard-widgets.php

Remove report view filters when getting dashboard widget data

---

includes/customer-functions.php

Prevent empty addresses from being added to the database

---

includes/admin/reporting/export/class-batch-export-sales-and-earnings.php

Fix ambiguous date query when exporting a single download report

---

assets/css/edd-admin.css

Fixes #7928
1. adjusted margins on edd-reports-tiles-wrap id
I'm not crazy about how hacky this solution looks, but is this what you were thinking visually @spencerfinnell?

Align tiles 

---

includes/admin/payments/class-payments-table.php

Fix orders list table when viewing for a specific customer

---

includes/database/tables/class-customers.php

Fixes #8000 
1. Updates the customers DB table version
2. Removes the `payment_ids` column during upgrades to 3.0
3. Removes the `payment_ids` column on existing 3.0 installs

Removing the payments_ids column #8000

---

includes/orders/functions/actions.php
includes/orders/functions/orders.php

Add name to manually created order addresses

---

assets/js/edd-ajax.js

Fixes #
I've fixed the code as described on #8070. Thanks

fixed: Use on() instead of change() #8070

---

includes/admin/discounts/class-discount-codes-table.php

Fixed Typos

---

includes/download-functions.php

Fixes #8102
1. Adds `$price_id` variable to `edd_is_file_at_download_limit` filter.
2. Adds/fixes some docblocks.

Add price_id variable to edd_is_file_at_download_limit filter #8102

---

includes/admin/settings/register-settings.php
includes/emails/functions.php

Fixes #8115
1. Add additional check for `install_plugins` capability.

Ensure user has install_plugins capability to install Jilt #8115

---

assets/js/admin/discounts/index.js

Fixes #8068 
1.  Changed event to `show` rather than `toggle` when items are added to list
I would have liked to have these fields revert back to `hidden` when all items are removed from the list, but I haven't been able to figure that out with jQuery yet.

#8068 "Download Requirements" Toggle

---

includes/user-functions.php

Fixes #8128 
1. Check if array key exists before using.

Check if total_spent is set before using #8128

---

includes/admin/import/class-batch-import-payments.php
includes/admin/tools.php

Fixes #8137
1. Update `customer_id` database column usage to `edd_customer_id`.
2. Update tool title to Import Orders instead of Payment History.
3. Use `name` column from CSV when present (#8143).

Fix orders import tool

---

assets/css/edd-admin.css
includes/admin/payments/orders.php
includes/admin/views/tmpl-order-adjustment-discount.php
includes/admin/views/tmpl-order-adjustment.php
includes/admin/views/tmpl-order-item.php

Fixes #7796 
1. Add ~aria-label~ screen reader label to empty button
2. Update headings to not skip levels

Issue/7796 Accessibility on Orders Screens

---

includes/reports/reports-functions.php

Fixes #8165
1. Remove all imported classes, as they're either unused, non-existent, or not needed.

Remove unused class imports #8165

---

assets/css/edd-admin.css

Fixes #7967 
1. Update specificity in CSS selector

issue/7967 Checkbox Width

---

includes/admin/customers/customers.php
includes/admin/payments/orders.php

Fixes #8204
1. Adds `regular-text` class to email text fields.

Increase size of email text fields on orders, customers

---

includes/admin/reporting/class-base-logs-list-table.php

Fixes #8273 
1.  Remove markup for more button in Tools > Logs

#8273 Remove Blank "More" Button

---

includes/admin/reporting/class-gateway-error-logs-list-table.php

Fixes #8307
1. Use the correct log data for the payment errors table.

Fix payment error log table output

---

includes/database/queries/class-log-api-request.php
includes/database/queries/class-log-file-download.php

Fixes #8297
1. Updates the `$item_name` and `$item_name_plural` for the File Downloads and API Request database classes.

Update item_name, item_name_plural for custom log classes

---

composer.json
easy-digital-downloads.php
readme.txt

Fixes #8301 
1. Add PHP version requirement

#8301 PHP version requirement

---

includes/admin/reporting/class-base-logs-list-table.php

Fixes #8321
1. Update query arg parameter
2. Fix docblock return comment

#8321 Filter Log by Order ID

---

includes/orders/functions/refunds.php

Fixes #8324
1. Introduce `edd_refundable_order_statuses` filter to supported refund statuses can be changed.

Introduce edd_refundable_order_statuses filter #8324

---

includes/class-edd-html-elements.php

Cast $args['selected'] to array before using as one

---

includes/database/schemas/class-order-items.php
includes/database/tables/class-order-items.php
includes/orders/functions/items.php

Change default order_item status to pending #8313

---

includes/admin/reporting/class-file-downloads-logs-list-table.php
includes/database/queries/class-adjustment.php
includes/database/queries/class-customer-address.php
includes/database/queries/class-customer-email-address.php
includes/database/queries/class-customer.php
includes/database/queries/class-log-api-request.php
includes/database/queries/class-log-file-download.php
includes/database/queries/class-log.php
includes/database/queries/class-note.php
includes/database/queries/class-order-address.php
includes/database/queries/class-order-adjustment.php
includes/database/queries/class-order-item.php
includes/database/queries/class-order-transaction.php
includes/database/queries/class-order.php
includes/database/schemas/class-adjustments.php
includes/database/schemas/class-logs-file-downloads.php
includes/database/schemas/class-notes.php
includes/database/schemas/class-order-items.php
includes/database/schemas/class-order-transactions.php
includes/logs/api-request-log/class-api-request-log.php
includes/logs/api-request-log/functions.php
includes/logs/file-download-log/class-file-download-log.php
includes/logs/file-download-log/functions.php
includes/logs/log/functions.php

Fixes #8315 
1. Review and update all query docblocks for accuracy.
2. Change file download log namespace from `EDD\File_Download_Logs\File_Download_Log\File_Download_Log` to `EDD\Logs\File_Download_Log`
3. Change API request log namespace from `EDD\Api_Request_Logs\Api_Request_Log` to `EDD\Logs\Api_Request_Log`

Update query docblocks & log namespaces #8315

---

includes/class-easy-digital-downloads.php

Execute edd_setup_components in the plugins_loaded hook

---

includes/admin/upgrades/v3/class-data-migrator.php

Fixes #8352 
1. Check if region key exists before using.

Check if region isn't empty before using #8352

---

includes/admin/tools/logs.php

Move logs table display outside of filter bar form

---

includes/class-edd-logging.php

Fixes #8385
1. Update implementation of `paged` to get the value from `$r['paged']`

Check for paged argument in args array #8385

---

includes/scripts.php

Remove inline-edit-post dependency

---

includes/deprecated-functions.php

Fixes #8389
1. Removes defaults from parameters that come before required ones.

Remove optional parameters before required #8389

---

includes/compat/class-tax.php

Specify the tax_rate type when retrieving adjustments (compat)

---

.buildkite/pipeline.yml
bin/install-wp-tests.sh
tests/orders/tests-payments.php

Attempting to throw an automatic retry when we get an exit status of 2 on SVN checkout failure.

Attempt to retry on SVN failures

---

includes/class-edd-cli.php

Update CLI migration completed messages

---

includes/admin/customers/customers.php

Update last payment to use edd_get_orders

---

includes/compat/class-customer.php
includes/customers/customer-actions.php

Do not update past order emails when updating customer's primary email

---

assets/js/admin/settings/tax-rates/views/table-add.js
includes/admin/settings/register-settings.php

Fixes #8401
1. Check for selected country and show alert if missing
2. Check for tax rate of 0 or less and show alert

#8401 Check for missing input before adding tax rate

---

includes/payments/class-edd-payment.php

Fixes #8421 
1. Correct object key in user_id case
2. Format array

#8421 Correct object key

---

includes/admin/reporting/reports.php

Fixes #8438 
1. Change the title of Export Downloads to mirror the title of Import Product Downloads

#8438 Export Download Products Title

---

readme.txt

Update "Tested up to" WordPress version

---

includes/compat/class-customer.php

Fixes #8434
1. Add a magic getter for properties that no longer exist.

Fix backwards compatibility for old customers DB properties #8434

---

includes/admin/customers/class-customer-addresses-table.php

Fixes #8437
1. Change fallback for name to be address id.

#8437 Prevent PHP warning if no email address

---

includes/admin/settings/register-settings.php

Fixes #8452 
1. Correct link to tracking usage
2. Add numbered placeholders and information for translators

#8452 Link to Usage Tracking Info

---

includes/admin/downloads/metabox.php
includes/download-functions.php

Fixes #8481
1. Remove default values from required parameters.

Remove defaults from required parameters #8481

---

includes/admin/upgrades/upgrade-functions.php

Add missing </div> to legacy data removal tool

---

includes/database/schemas/class-orders.php
includes/database/tables/class-orders.php

Fixes #8522
1. Increase length of `gateway` column to `100`.

Increase length of gateway column to 100 #8522

---

includes/admin/import/class-batch-import-downloads.php

Fixes #8519
1. Removes the `GLOB_BRACE` flag and reworks the pattern a bit to account for the removal. Output should be exactly the same as before.

Remove GLOB_BRACE flag #8519

---

includes/login-register.php
includes/misc-functions.php

Fixes #6115 
1. adds a check for the `edd_honeypot` field to the registration form validation.

Add edd_honeypot to the registration form validation.

---

includes/gateways/.stripe-hash
languages/easy-digital-downloads.pot

Fixes #8561 
1. Updates the Stripe dependency.

Update Stripe dependency for v2.8.6 #8561

---

includes/orders/classes/class-order.php

Fixes #8576
1. Ensure adjustments exists and then continue with discount logic

#8576 Ensure adjustments exists

---

includes/discount-functions.php

Fixes #8613 
1. Correct since version number.
2. Document 3.0 function ch anges.

Update docblock to reflect function history & correct since version #8613

---

includes/admin/downloads/metabox.php
includes/admin/payments/payments-history.php
includes/class-edd-customer.php
includes/class-edd-db-customer-meta.php
includes/download-functions.php
includes/payments/functions.php

Fixes #8628
1. Removes default values from required parameters.

Remove default values from required parameters #8628

---

includes/admin/payments/orders.php

Set manual as the default gateway for manual orders

---

includes/admin/reporting/graphing.php

Fixes #8650 
1. Removes unused variables.
2. Validates the input dates prior to saving. If they're not valid, an error message is shown.

Validate input dates before saving #8650

---

includes/plugin-compatibility.php

Fixes #8460
1. Detects Hummingbird plugin. See https://plugins.svn.wordpress.org/hummingbird-performance/trunk/wp-hummingbird.php

Add Hummingbird to list of caching plugins #8460

---

includes/template-functions.php

Fixes #
Added filter to edd_pagination args.

Add filter to pagination function

---

includes/api/class-edd-api.php

Fixes https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7418
1. excluded_products added in the Discount REST

Display excluded_products in Discount REST

---

includes/admin/upgrades/v3/class-data-migrator.php

Fixes #8673
1. Create the `edd_30_core_payment_meta` filter, similar to the user info filter immediately following.

Add a filter on core payment meta keys

---

includes/gateways/paypal/admin/connect.php
languages/easy-digital-downloads.pot

1. Changes how merchant status is retrieved.

Fetch status from Sandhills Connect.

---

includes/EDD_SL_Plugin_Updater.php

Fixes #8585
1. Copy missing check for iterable from SL plugin updater.

#8585 Check for iterable

---

includes/admin/discounts/add-discount.php

Fixes #
Added new action to add discount screen.

Introduce new edd_add_discount_form_after_use_once action

---

includes/admin/discounts/class-discount-codes-table.php

Added filters to allow new columsn to be easily added to discounts table class. Kept in line with payments table.

Add filters to discounts table class

---

includes/EDD_SL_Plugin_Updater.php
includes/class-edd-license-handler.php

Fixes #8790
1. Update the EDD_SL_Plugin_Updater class to version 1.9.0.
2. Use the new `edd_sl_plugin_updater_api_params` filter to add the EDD version to the API request parameters for EDD extensions.

Update EDD_SL_Plugin_Updater to version 1.9.0

---

readme.txt

1. Free gateways: Replaces "PayPal Standard" with just "PayPal".
2. Extension gateways: Replaces the four PayPal options with "PayPal Commerce Pro" (and brief overview of what it includes, to mimic Stripe Pro).
3. Descriptions for two new screenshots.

Update readme for EDD 2.11

---

includes/EDD_SL_Plugin_Updater.php

Fix version_compare for multisite in plugin updater class

---

includes/class-component.php
includes/class-easy-digital-downloads.php
includes/compat/class-customermeta.php

Fixes #8819
1. Introduces a new class `EDD\Compat\CustomerMeta` for handling rerouting of the old `EDD_DB_Customer_Meta` class.
2. `EDD()->customermeta` and `EDD()->customer_meta` now get rerouted to the above mentioned class.
2. Update docblocks in the `Component` class to clarify exactly which objects they are.

Introduce CustomerMeta compat class #8819

---

includes/admin/settings/register-settings.php

Change EDD license input type to password

---

includes/class-edd-license-handler.php

Use correct license key for pass data during activation

---

includes/admin/settings/contextual-help.php

Fixes #8960
1. Changes "Payment Gateways" tab to "Payments" to match new settings screen tabs.
2. Updates content to match new settings locations.

Update settings screen contextual help tabs, content

---

includes/admin/reporting/export/class-batch-export-customers.php

Add user ID, payment IDs, and date created to customer export

---

composer.json
composer.lock
tests/bootstrap.php

Fixes #8990
1. Includes the `yoast/phpunit-polyfills` library.
2. Includes the `vendor/autoload.php` file during tests bootstrapping.

Use PHPUnit Polyfills library #8990

---

includes/ajax-functions.php

Fixes #
1. Added a filter while removing discount code via ajax call just like the way you did in adding discount code.

new: Added a filter inside AJAX remove discount function.

---

includes/admin/promos/class-promo-handler.php

Replace FILTER_SANITIZE_STRING

---

includes/gateways/paypal-standard.php

Remove www from PayPal Standard transaction links

---

easy-digital-downloads.php
languages/easy-digital-downloads.pot
readme.txt

1. Version bump for 2.11.4.
2. Changelog entry for 2.11.4 (currently dated 12/27).

Update readme, version for release

---

tests/tests-languages.php

Remove easy-digital-downloads-ar.mo assertion from unit tests

---

includes/admin/payments/class-refund-items-table.php
includes/formatting.php
includes/scripts.php

Fixes #9050
1. Make the conditional a bit less strict so it can apply to the refund UI as well.

Generalize condition so it can apply to refund UI as well #9050

---

includes/class-edd-discount.php
includes/payments/class-edd-payment.php

Fixes #7248
1. Adds property tags to the `EDD_Discount` class.
2. Adds property tags to the `EDD_Payment` class.

Add property tags to docblock #7248

---

includes/admin/extensions/product-education/class-email-marketing.php

Remove Mailchimp version check from product education

---

includes/admin/promos/notices/class-license-upgrade-notice.php

1. Includes the URL to the new pass doc.
2. Adds logic to also suggest MonsterInsights if AffilaiteWP license is active.

Add new doc link for pass help, and include MonsterInsights in notice list

---

includes/discount-functions.php

Add filter to edd_get_discount_by_code

---

includes/admin/payments/actions.php

Fix variable name when updating an order

---

includes/admin/discounts/class-discount-codes-table.php

Add filter to discount row title

---

includes/admin/tools.php

Fixes #9183
Note that all this PR does is correct the link. We could move the information/link to a more relevant place, but I think we could also improve the wording and make the link accessible, but that would affect the translatable string.

Fix export to report settings link

---

includes/class-stats.php

1. Fixes 3 references to `aallowed_functions` which should be `accepted_functions`

Fixing references to 'allowed_functions' for proper 'accepted_functions'

---

includes/class-stats.php

1. Fixes the check for `AVG` to `AVG(id)` which is what the actual function is when determining average number of orders per customer.

Fixing the function being looked for when doing average number of orders

---

includes/admin/settings/register-settings.php

Fixes #
Fix a typo in the settings...

Fix "regisitered" typo in settings

---

includes/admin/reporting/reports-callbacks.php

Fixes hour by hour graphs from grouping everything on a single data point.

Fixing hour by hour graphing

---

includes/gateways/paypal/admin/connect.php

Run sprintf on debug log message

---

includes/admin/payments/class-payments-table.php
includes/admin/reporting/reports-callbacks.php
includes/reports/reports-functions.php

@robincornett have a look at this for me. It makes a couple small tweaks to reporting graphs and the list table to account for UTC offset when doing queries for grouping.

Fixing list table date ranges, and fixing report graph groupings to account for UTC Offset

---

includes/admin/settings/register-settings.php

Fixes #9044
Small change in the contextual help for Debug Mode.

Updated debug mode contextual help

---

readme.txt

Adding 3.0 changelog

---

includes/login-register.php

1. Updates `edd_get_lostpassword_url` to add parameters to the redirect parameter for the lost password URL, and also adds a query arg to the returned URL.
2. Adds a new function, `edd_set_lostpassword_session`, to set the correct redirect as session data.
3. Updates `edd_login_register_error_message` to conditionally get the correct redirect URL from the session. If the session data is not available, then the message is modified to be a little more generic.
4. The session variable is unset before outputting the errors.

Refactor lost password flow

---

includes/admin/reporting/class-file-downloads-logs-list-table.php

Fixes #9287
Added small check if `$file_id` is set in the list of files.

Fixed "Undefined array key" on the File downloads log page

---

includes/class-edd-discount.php

1. Updates the product requirements check to evaluate independently of the current "is met" status.
2. Moves the error message logic.

Improve discount validation for product requirements

---

includes/reports/reports-functions.php

Fixes #9371 
1. Runs `$function` through `strtoupper` as MySQL functions are always upper case.
2. When the `$function` is `MONTH`, adjusts the query to include `YEAR` and `MONTH` in order to avoid grouping the same month from different years as the same data point.

Reporting groupby should determine the difference between months in multiple years #9371

---

includes/user-functions.php

Fixes #9344 
1. Switches the hook for linking a customer to a user from `edd_customer_post_attach_payment` to `edd_customer_post_create` as that is more accurate of when we should link them.

Swtich from linking customer/user on customer creation, not payment attachment #9344

---

includes/class-edd-license-handler.php

1. Adds an `admin_init` function in the license class to check for the new/old Stripe license keys and status. If the old one is saved and the new one doesn't exist, then the new ones are updated with the old value and the old ones are deleted.
To Test:
1. Make sure you do not have a license key saved for Stripe.
2. Switch to Stripe Pro 2.8, before the name change.
3. Save the license key.
4. Update to Stripe's master branch and reload the licenses screen. The license key should be populated. (The license container for Stripe may have also moved.)

Add an admin check for the original Stripe license key

---

includes/post-types.php

Fixes #5133
1. Adds filter for the `display_post_states` filter to include matching with the EDD Page Settings

Adds page states to the list table when it aligns with the EDD page settings #5133

---

includes/api/class-edd-api-v2.php
includes/api/class-edd-api.php

Fixes #9400 
1. Brings in `EDD\Stats` and `EDD\Reports` to the V2 API
2. Refactors the `get_customers` method to correct date queries for EDD 3.0
3. Refactors the arguments for EDD 3.0.
4. Updates the `purchase_value` of the customer to use `edd_format_amount` with the currency helper.

Re-factor api/v2 customers endpoint to use new arguments #9400

---

includes/admin/tools.php

Fixes #6405
1. Adds a section to the system info for dropins.

Add dropins to the system ifno #6405

---

includes/reports/reports-functions.php

Additional checks for empty `range` and `relative_range` GET parameters.

Fix undefined relative range index

---

includes/emails/email-summary/class-edd-email-summary.php
includes/emails/email-summary/edd-email-summary-template.php

Store URL was showing the wrong URL protocol because of `esc_url`.

Fix store URL in email summary

---

includes/user-functions.php

Fixes #9456
1. Updates the database function to query only orders that are a type `sale` and order items that have a deliverable status.

Update edd_has_user_purchased to filter order item status, order type

---

includes/post-types.php

Fixes #9489 
1. Filters the `rest_user_query` to return an array of users who have the `edit_product` capability for the author dropdown. This is a different solution than we did in FES, but the same filter (it runs earlier than FES).
Note: I'm not convinced this is really a bug in EDD but possibly one in WP Core--in 2.11, WordPress properly honors the custom capabilities EDD registers and shows only the custom roles (and admin) in the author dropdown. The REST API authors query doesn't have the post type context.

Update block editor author selection for download capabilities

---

easy-digital-downloads.php
i18n/states.php
includes/admin/discounts/discount-actions.php
includes/class-easy-digital-downloads.php
languages/easy-digital-downloads.pot
package.json
readme.txt
src/Admin/Settings/Tabs/Taxes.php

* Fix: India Regions were not being properly loaded.
* Fix: Fixed compatibility with PHP 7.1 when adding a new discount.
* Dev: Tax settings tab was overriding the base class method for getting the ID.

Adding 3.1.5 changes

---

easy-digital-downloads.php
includes/class-easy-digital-downloads.php
languages/easy-digital-downloads.pot
package.json
readme.txt
src/HTML/ProductSelect.php

* Orders: When searching orders, a Product ID was being erroneously added to the filter arguments when it shouldn't have been.

Adding EDD 3.2.11
